/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {8, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_expl_ode_fun:(i0[11],i1[4],i2[8])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w02, w03, w04, w05, w07, w08, w09, w10, w11, w12;
  casadi_real w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24;
  casadi_real w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, *w36=w+53;
  const casadi_real *cs, *wr01, *wr06;
  /* #0: @0 = 0.00333333 */
  w00 = 3.3333333333333335e-03;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[1] */
  w02 = wr01[1];
  /* #3: @3 = @1[2] */
  w03 = wr01[2];
  /* #4: @4 = (@2*@3) */
  w04  = (w02*w03);
  /* #5: @5 = 1.5 */
  w05 = 1.5000000000000000e+00;
  /* #6: @6 = input[2][0] */
  wr06 = arg[2] ? arg[2] : casadi_zeros;
  /* #7: @7 = @6[3] */
  w07 = wr06[3];
  /* #8: @8 = 10 */
  w08 = 10.;
  /* #9: @7 = fmax(@7,@8) */
  w07  = casadi_fmax(w07,w08);
  /* #10: @7 = (@5*@7) */
  w07  = (w05*w07);
  /* #11: @9 = 1.3 */
  w09 = 1.3000000000000000e+00;
  /* #12: @10 = 9 */
  w10 = 9.;
  /* #13: @11 = 0.193 */
  w11 = 1.9300000000000000e-01;
  /* #14: @12 = @1[3] */
  w12 = wr01[3];
  /* #15: @13 = (@11*@12) */
  w13  = (w11*w12);
  /* #16: @14 = 0.01 */
  w14 = 1.0000000000000002e-02;
  /* #17: @15 = @1[0] */
  w15 = wr01[0];
  /* #18: @16 = 0.621 */
  w16 = 6.2100000000000000e-01;
  /* #19: @17 = (@16*@3) */
  w17  = (w16*w03);
  /* #20: @18 = (@15-@17) */
  w18  = (w15-w17);
  /* #21: @19 = @6[1] */
  w19 = wr06[1];
  /* #22: @20 = cos(@19) */
  w20 = cos( w19 );
  /* #23: @21 = (@18*@20) */
  w21  = (w18*w20);
  /* #24: @22 = 0.765 */
  w22 = 7.6500000000000001e-01;
  /* #25: @23 = (@22*@3) */
  w23  = (w22*w03);
  /* #26: @24 = (@2+@23) */
  w24  = (w02+w23);
  /* #27: @19 = sin(@19) */
  w19 = sin( w19 );
  /* #28: @25 = (@24*@19) */
  w25  = (w24*w19);
  /* #29: @21 = (@21+@25) */
  w21 += w25;
  /* #30: @21 = sq(@21) */
  w21 = casadi_sq( w21 );
  /* #31: @21 = (@14+@21) */
  w21  = (w14+w21);
  /* #32: @21 = sqrt(@21) */
  w21 = sqrt( w21 );
  /* #33: @13 = (@13-@21) */
  w13 -= w21;
  /* #34: @13 = (@13/@21) */
  w13 /= w21;
  /* #35: @13 = (@10*@13) */
  w13  = (w10*w13);
  /* #36: @25 = 0.7 */
  w25 = 6.9999999999999996e-01;
  /* #37: @26 = atan(@13) */
  w26 = atan( w13 );
  /* #38: @26 = (@13-@26) */
  w26  = (w13-w26);
  /* #39: @26 = (@25*@26) */
  w26  = (w25*w26);
  /* #40: @13 = (@13-@26) */
  w13 -= w26;
  /* #41: @13 = atan(@13) */
  w13 = atan( w13 );
  /* #42: @13 = (@9*@13) */
  w13  = (w09*w13);
  /* #43: @13 = sin(@13) */
  w13 = sin( w13 );
  /* #44: @13 = (@7*@13) */
  w13  = (w07*w13);
  /* #45: @26 = (@13*@20) */
  w26  = (w13*w20);
  /* #46: @27 = (@24*@20) */
  w27  = (w24*w20);
  /* #47: @28 = (@18*@19) */
  w28  = (w18*w19);
  /* #48: @27 = (@27-@28) */
  w27 -= w28;
  /* #49: @27 = atan2(@27,@21) */
  w27  = atan2(w27,w21);
  /* #50: @27 = (@10*@27) */
  w27  = (w10*w27);
  /* #51: @21 = atan(@27) */
  w21 = atan( w27 );
  /* #52: @21 = (@27-@21) */
  w21  = (w27-w21);
  /* #53: @21 = (@25*@21) */
  w21  = (w25*w21);
  /* #54: @27 = (@27-@21) */
  w27 -= w21;
  /* #55: @27 = atan(@27) */
  w27 = atan( w27 );
  /* #56: @27 = (@9*@27) */
  w27  = (w09*w27);
  /* #57: @27 = sin(@27) */
  w27 = sin( w27 );
  /* #58: @7 = (@7*@27) */
  w07 *= w27;
  /* #59: @27 = (@7*@19) */
  w27  = (w07*w19);
  /* #60: @26 = (@26-@27) */
  w26 -= w27;
  /* #61: @4 = (@4+@26) */
  w04 += w26;
  /* #62: @27 = @6[4] */
  w27 = wr06[4];
  /* #63: @27 = fmax(@27,@8) */
  w27  = casadi_fmax(w27,w08);
  /* #64: @27 = (@5*@27) */
  w27  = (w05*w27);
  /* #65: @21 = @1[4] */
  w21 = wr01[4];
  /* #66: @28 = (@11*@21) */
  w28  = (w11*w21);
  /* #67: @17 = (@15+@17) */
  w17  = (w15+w17);
  /* #68: @29 = @6[2] */
  w29 = wr06[2];
  /* #69: @30 = cos(@29) */
  w30 = cos( w29 );
  /* #70: @31 = (@17*@30) */
  w31  = (w17*w30);
  /* #71: @29 = sin(@29) */
  w29 = sin( w29 );
  /* #72: @32 = (@24*@29) */
  w32  = (w24*w29);
  /* #73: @31 = (@31+@32) */
  w31 += w32;
  /* #74: @31 = sq(@31) */
  w31 = casadi_sq( w31 );
  /* #75: @31 = (@14+@31) */
  w31  = (w14+w31);
  /* #76: @31 = sqrt(@31) */
  w31 = sqrt( w31 );
  /* #77: @28 = (@28-@31) */
  w28 -= w31;
  /* #78: @28 = (@28/@31) */
  w28 /= w31;
  /* #79: @28 = (@10*@28) */
  w28  = (w10*w28);
  /* #80: @32 = atan(@28) */
  w32 = atan( w28 );
  /* #81: @32 = (@28-@32) */
  w32  = (w28-w32);
  /* #82: @32 = (@25*@32) */
  w32  = (w25*w32);
  /* #83: @28 = (@28-@32) */
  w28 -= w32;
  /* #84: @28 = atan(@28) */
  w28 = atan( w28 );
  /* #85: @28 = (@9*@28) */
  w28  = (w09*w28);
  /* #86: @28 = sin(@28) */
  w28 = sin( w28 );
  /* #87: @28 = (@27*@28) */
  w28  = (w27*w28);
  /* #88: @32 = (@28*@30) */
  w32  = (w28*w30);
  /* #89: @24 = (@24*@30) */
  w24 *= w30;
  /* #90: @33 = (@17*@29) */
  w33  = (w17*w29);
  /* #91: @24 = (@24-@33) */
  w24 -= w33;
  /* #92: @24 = atan2(@24,@31) */
  w24  = atan2(w24,w31);
  /* #93: @24 = (@10*@24) */
  w24  = (w10*w24);
  /* #94: @31 = atan(@24) */
  w31 = atan( w24 );
  /* #95: @31 = (@24-@31) */
  w31  = (w24-w31);
  /* #96: @31 = (@25*@31) */
  w31  = (w25*w31);
  /* #97: @24 = (@24-@31) */
  w24 -= w31;
  /* #98: @24 = atan(@24) */
  w24 = atan( w24 );
  /* #99: @24 = (@9*@24) */
  w24  = (w09*w24);
  /* #100: @24 = sin(@24) */
  w24 = sin( w24 );
  /* #101: @27 = (@27*@24) */
  w27 *= w24;
  /* #102: @24 = (@27*@29) */
  w24  = (w27*w29);
  /* #103: @32 = (@32-@24) */
  w32 -= w24;
  /* #104: @4 = (@4+@32) */
  w04 += w32;
  /* #105: @24 = @6[5] */
  w24 = wr06[5];
  /* #106: @24 = fmax(@24,@8) */
  w24  = casadi_fmax(w24,w08);
  /* #107: @24 = (@5*@24) */
  w24  = (w05*w24);
  /* #108: @31 = @1[5] */
  w31 = wr01[5];
  /* #109: @33 = (@11*@31) */
  w33  = (w11*w31);
  /* #110: @18 = sq(@18) */
  w18 = casadi_sq( w18 );
  /* #111: @18 = (@14+@18) */
  w18  = (w14+w18);
  /* #112: @18 = sqrt(@18) */
  w18 = sqrt( w18 );
  /* #113: @33 = (@33-@18) */
  w33 -= w18;
  /* #114: @33 = (@33/@18) */
  w33 /= w18;
  /* #115: @33 = (@10*@33) */
  w33  = (w10*w33);
  /* #116: @34 = atan(@33) */
  w34 = atan( w33 );
  /* #117: @34 = (@33-@34) */
  w34  = (w33-w34);
  /* #118: @34 = (@25*@34) */
  w34  = (w25*w34);
  /* #119: @33 = (@33-@34) */
  w33 -= w34;
  /* #120: @33 = atan(@33) */
  w33 = atan( w33 );
  /* #121: @33 = (@9*@33) */
  w33  = (w09*w33);
  /* #122: @33 = sin(@33) */
  w33 = sin( w33 );
  /* #123: @33 = (@24*@33) */
  w33  = (w24*w33);
  /* #124: @4 = (@4+@33) */
  w04 += w33;
  /* #125: @34 = @6[6] */
  w34 = wr06[6];
  /* #126: @34 = fmax(@34,@8) */
  w34  = casadi_fmax(w34,w08);
  /* #127: @5 = (@5*@34) */
  w05 *= w34;
  /* #128: @34 = @1[6] */
  w34 = wr01[6];
  /* #129: @8 = (@11*@34) */
  w08  = (w11*w34);
  /* #130: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #131: @14 = (@14+@17) */
  w14 += w17;
  /* #132: @14 = sqrt(@14) */
  w14 = sqrt( w14 );
  /* #133: @8 = (@8-@14) */
  w08 -= w14;
  /* #134: @8 = (@8/@14) */
  w08 /= w14;
  /* #135: @8 = (@10*@8) */
  w08  = (w10*w08);
  /* #136: @17 = atan(@8) */
  w17 = atan( w08 );
  /* #137: @17 = (@8-@17) */
  w17  = (w08-w17);
  /* #138: @17 = (@25*@17) */
  w17  = (w25*w17);
  /* #139: @8 = (@8-@17) */
  w08 -= w17;
  /* #140: @8 = atan(@8) */
  w08 = atan( w08 );
  /* #141: @8 = (@9*@8) */
  w08  = (w09*w08);
  /* #142: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #143: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #144: @4 = (@4+@8) */
  w04 += w08;
  /* #145: @17 = 0.957 */
  w17 = 9.5700000000000007e-01;
  /* #146: @35 = sq(@15) */
  w35 = casadi_sq( w15 );
  /* #147: @17 = (@17*@35) */
  w17 *= w35;
  /* #148: @4 = (@4-@17) */
  w04 -= w17;
  /* #149: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #150: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #151: @19 = (@13*@19) */
  w19  = (w13*w19);
  /* #152: @7 = (@7*@20) */
  w07 *= w20;
  /* #153: @19 = (@19+@7) */
  w19 += w07;
  /* #154: @15 = (@15*@3) */
  w15 *= w03;
  /* #155: @15 = (@19-@15) */
  w15  = (w19-w15);
  /* #156: @29 = (@28*@29) */
  w29  = (w28*w29);
  /* #157: @27 = (@27*@30) */
  w27 *= w30;
  /* #158: @29 = (@29+@27) */
  w29 += w27;
  /* #159: @15 = (@15+@29) */
  w15 += w29;
  /* #160: @2 = (@2-@23) */
  w02 -= w23;
  /* #161: @18 = atan2(@2,@18) */
  w18  = atan2(w02,w18);
  /* #162: @18 = (@10*@18) */
  w18  = (w10*w18);
  /* #163: @23 = atan(@18) */
  w23 = atan( w18 );
  /* #164: @23 = (@18-@23) */
  w23  = (w18-w23);
  /* #165: @23 = (@25*@23) */
  w23  = (w25*w23);
  /* #166: @18 = (@18-@23) */
  w18 -= w23;
  /* #167: @18 = atan(@18) */
  w18 = atan( w18 );
  /* #168: @18 = (@9*@18) */
  w18  = (w09*w18);
  /* #169: @18 = sin(@18) */
  w18 = sin( w18 );
  /* #170: @24 = (@24*@18) */
  w24 *= w18;
  /* #171: @15 = (@15+@24) */
  w15 += w24;
  /* #172: @2 = atan2(@2,@14) */
  w02  = atan2(w02,w14);
  /* #173: @10 = (@10*@2) */
  w10 *= w02;
  /* #174: @2 = atan(@10) */
  w02 = atan( w10 );
  /* #175: @2 = (@10-@2) */
  w02  = (w10-w02);
  /* #176: @25 = (@25*@2) */
  w25 *= w02;
  /* #177: @10 = (@10-@25) */
  w10 -= w25;
  /* #178: @10 = atan(@10) */
  w10 = atan( w10 );
  /* #179: @9 = (@9*@10) */
  w09 *= w10;
  /* #180: @9 = sin(@9) */
  w09 = sin( w09 );
  /* #181: @5 = (@5*@9) */
  w05 *= w09;
  /* #182: @15 = (@15+@5) */
  w15 += w05;
  /* #183: @0 = (@0*@15) */
  w00 *= w15;
  /* #184: output[0][1] = @0 */
  if (res[0]) res[0][1] = w00;
  /* #185: @0 = 0.00787092 */
  w00 = 7.8709169618260532e-03;
  /* #186: @19 = (@19+@29) */
  w19 += w29;
  /* #187: @19 = (@22*@19) */
  w19  = (w22*w19);
  /* #188: @24 = (@24+@5) */
  w24 += w05;
  /* #189: @22 = (@22*@24) */
  w22 *= w24;
  /* #190: @19 = (@19-@22) */
  w19 -= w22;
  /* #191: @32 = (@32-@26) */
  w32 -= w26;
  /* #192: @32 = (@32+@8) */
  w32 += w08;
  /* #193: @32 = (@32-@33) */
  w32 -= w33;
  /* #194: @16 = (@16*@32) */
  w16 *= w32;
  /* #195: @19 = (@19+@16) */
  w19 += w16;
  /* #196: @0 = (@0*@19) */
  w00 *= w19;
  /* #197: output[0][2] = @0 */
  if (res[0]) res[0][2] = w00;
  /* #198: @0 = @1[7] */
  w00 = wr01[7];
  /* #199: @13 = (@11*@13) */
  w13  = (w11*w13);
  /* #200: @0 = (@0-@13) */
  w00 -= w13;
  /* #201: @13 = 0.1 */
  w13 = 1.0000000000000001e-01;
  /* #202: @12 = (@12/@13) */
  w12 /= w13;
  /* #203: @12 = tanh(@12) */
  w12 = tanh( w12 );
  /* #204: @12 = (@13*@12) */
  w12  = (w13*w12);
  /* #205: @0 = (@0-@12) */
  w00 -= w12;
  /* #206: @12 = 0.15 */
  w12 = 1.4999999999999999e-01;
  /* #207: @0 = (@0/@12) */
  w00 /= w12;
  /* #208: output[0][3] = @0 */
  if (res[0]) res[0][3] = w00;
  /* #209: @0 = @1[8] */
  w00 = wr01[8];
  /* #210: @28 = (@11*@28) */
  w28  = (w11*w28);
  /* #211: @0 = (@0-@28) */
  w00 -= w28;
  /* #212: @21 = (@21/@13) */
  w21 /= w13;
  /* #213: @21 = tanh(@21) */
  w21 = tanh( w21 );
  /* #214: @21 = (@13*@21) */
  w21  = (w13*w21);
  /* #215: @0 = (@0-@21) */
  w00 -= w21;
  /* #216: @0 = (@0/@12) */
  w00 /= w12;
  /* #217: output[0][4] = @0 */
  if (res[0]) res[0][4] = w00;
  /* #218: @0 = @1[9] */
  w00 = wr01[9];
  /* #219: @33 = (@11*@33) */
  w33  = (w11*w33);
  /* #220: @0 = (@0-@33) */
  w00 -= w33;
  /* #221: @31 = (@31/@13) */
  w31 /= w13;
  /* #222: @31 = tanh(@31) */
  w31 = tanh( w31 );
  /* #223: @31 = (@13*@31) */
  w31  = (w13*w31);
  /* #224: @0 = (@0-@31) */
  w00 -= w31;
  /* #225: @0 = (@0/@12) */
  w00 /= w12;
  /* #226: output[0][5] = @0 */
  if (res[0]) res[0][5] = w00;
  /* #227: @0 = @1[10] */
  w00 = wr01[10];
  /* #228: @11 = (@11*@8) */
  w11 *= w08;
  /* #229: @0 = (@0-@11) */
  w00 -= w11;
  /* #230: @34 = (@34/@13) */
  w34 /= w13;
  /* #231: @34 = tanh(@34) */
  w34 = tanh( w34 );
  /* #232: @13 = (@13*@34) */
  w13 *= w34;
  /* #233: @0 = (@0-@13) */
  w00 -= w13;
  /* #234: @0 = (@0/@12) */
  w00 /= w12;
  /* #235: output[0][6] = @0 */
  if (res[0]) res[0][6] = w00;
  /* #236: @36 = input[1][0] */
  casadi_copy(arg[1], 4, w36);
  /* #237: @0 = @36[0] */
  for (rr=(&w00), cs=w36+0; cs!=w36+1; cs+=1) *rr++ = *cs;
  /* #238: output[0][7] = @0 */
  if (res[0]) res[0][7] = w00;
  /* #239: @0 = @36[1] */
  for (rr=(&w00), cs=w36+1; cs!=w36+2; cs+=1) *rr++ = *cs;
  /* #240: output[0][8] = @0 */
  if (res[0]) res[0][8] = w00;
  /* #241: @0 = @36[2] */
  for (rr=(&w00), cs=w36+2; cs!=w36+3; cs+=1) *rr++ = *cs;
  /* #242: output[0][9] = @0 */
  if (res[0]) res[0][9] = w00;
  /* #243: @0 = @36[3] */
  for (rr=(&w00), cs=w36+3; cs!=w36+4; cs+=1) *rr++ = *cs;
  /* #244: output[0][10] = @0 */
  if (res[0]) res[0][10] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 57;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 57*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
