/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_impl_dae_fun:(i0[11],i1[11],i2[4],i3[],i4[8])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *w00=w+0, w01, *w02=w+12, w03, w04, w05, w06, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  casadi_real w24, w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35;
  casadi_real w36, *w37=w+64;
  const casadi_real *cr, *cs, *wr00, *wr02, *wr07;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: @1 = 0.00333333 */
  w01 = 3.3333333333333335e-03;
  /* #2: @2 = input[0][0] */
  wr02 = arg[0] ? arg[0] : casadi_zeros;
  /* #3: @3 = @2[1] */
  w03 = wr02[1];
  /* #4: @4 = @2[2] */
  w04 = wr02[2];
  /* #5: @5 = (@3*@4) */
  w05  = (w03*w04);
  /* #6: @6 = 1.5 */
  w06 = 1.5000000000000000e+00;
  /* #7: @7 = input[4][0] */
  wr07 = arg[4] ? arg[4] : casadi_zeros;
  /* #8: @8 = @7[3] */
  w08 = wr07[3];
  /* #9: @9 = 10 */
  w09 = 10.;
  /* #10: @8 = fmax(@8,@9) */
  w08  = casadi_fmax(w08,w09);
  /* #11: @8 = (@6*@8) */
  w08  = (w06*w08);
  /* #12: @10 = 1.3 */
  w10 = 1.3000000000000000e+00;
  /* #13: @11 = 9 */
  w11 = 9.;
  /* #14: @12 = 0.193 */
  w12 = 1.9300000000000000e-01;
  /* #15: @13 = @2[3] */
  w13 = wr02[3];
  /* #16: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #17: @15 = @2[0] */
  w15 = wr02[0];
  /* #18: @16 = 0.621 */
  w16 = 6.2100000000000000e-01;
  /* #19: @17 = (@16*@4) */
  w17  = (w16*w04);
  /* #20: @18 = (@15-@17) */
  w18  = (w15-w17);
  /* #21: @19 = @7[1] */
  w19 = wr07[1];
  /* #22: @20 = cos(@19) */
  w20 = cos( w19 );
  /* #23: @21 = (@18*@20) */
  w21  = (w18*w20);
  /* #24: @22 = 0.765 */
  w22 = 7.6500000000000001e-01;
  /* #25: @23 = (@22*@4) */
  w23  = (w22*w04);
  /* #26: @24 = (@3+@23) */
  w24  = (w03+w23);
  /* #27: @19 = sin(@19) */
  w19 = sin( w19 );
  /* #28: @25 = (@24*@19) */
  w25  = (w24*w19);
  /* #29: @21 = (@21+@25) */
  w21 += w25;
  /* #30: @25 = fabs(@21) */
  w25 = casadi_fabs( w21 );
  /* #31: @26 = 1 */
  w26 = 1.;
  /* #32: @25 = (@25<@26) */
  w25  = (w25<w26);
  /* #33: @27 = (@25?@26:0) */
  w27  = (w25?w26:0);
  /* #34: @25 = (!@25) */
  w25 = (! w25 );
  /* #35: @25 = (@25?@21:0) */
  w25  = (w25?w21:0);
  /* #36: @27 = (@27+@25) */
  w27 += w25;
  /* #37: @14 = (@14-@27) */
  w14 -= w27;
  /* #38: @14 = (@14/@27) */
  w14 /= w27;
  /* #39: @14 = (@11*@14) */
  w14  = (w11*w14);
  /* #40: @25 = 0.7 */
  w25 = 6.9999999999999996e-01;
  /* #41: @21 = atan(@14) */
  w21 = atan( w14 );
  /* #42: @21 = (@14-@21) */
  w21  = (w14-w21);
  /* #43: @21 = (@25*@21) */
  w21  = (w25*w21);
  /* #44: @14 = (@14-@21) */
  w14 -= w21;
  /* #45: @14 = atan(@14) */
  w14 = atan( w14 );
  /* #46: @14 = (@10*@14) */
  w14  = (w10*w14);
  /* #47: @14 = sin(@14) */
  w14 = sin( w14 );
  /* #48: @14 = (@8*@14) */
  w14  = (w08*w14);
  /* #49: @21 = (@14*@20) */
  w21  = (w14*w20);
  /* #50: @28 = (@24*@20) */
  w28  = (w24*w20);
  /* #51: @29 = (@18*@19) */
  w29  = (w18*w19);
  /* #52: @28 = (@28-@29) */
  w28 -= w29;
  /* #53: @28 = atan2(@28,@27) */
  w28  = atan2(w28,w27);
  /* #54: @28 = (@11*@28) */
  w28  = (w11*w28);
  /* #55: @27 = atan(@28) */
  w27 = atan( w28 );
  /* #56: @27 = (@28-@27) */
  w27  = (w28-w27);
  /* #57: @27 = (@25*@27) */
  w27  = (w25*w27);
  /* #58: @28 = (@28-@27) */
  w28 -= w27;
  /* #59: @28 = atan(@28) */
  w28 = atan( w28 );
  /* #60: @28 = (@10*@28) */
  w28  = (w10*w28);
  /* #61: @28 = sin(@28) */
  w28 = sin( w28 );
  /* #62: @8 = (@8*@28) */
  w08 *= w28;
  /* #63: @28 = (@8*@19) */
  w28  = (w08*w19);
  /* #64: @21 = (@21-@28) */
  w21 -= w28;
  /* #65: @5 = (@5+@21) */
  w05 += w21;
  /* #66: @28 = @7[4] */
  w28 = wr07[4];
  /* #67: @28 = fmax(@28,@9) */
  w28  = casadi_fmax(w28,w09);
  /* #68: @28 = (@6*@28) */
  w28  = (w06*w28);
  /* #69: @27 = @2[4] */
  w27 = wr02[4];
  /* #70: @29 = (@12*@27) */
  w29  = (w12*w27);
  /* #71: @17 = (@15+@17) */
  w17  = (w15+w17);
  /* #72: @30 = @7[2] */
  w30 = wr07[2];
  /* #73: @31 = cos(@30) */
  w31 = cos( w30 );
  /* #74: @32 = (@17*@31) */
  w32  = (w17*w31);
  /* #75: @30 = sin(@30) */
  w30 = sin( w30 );
  /* #76: @33 = (@24*@30) */
  w33  = (w24*w30);
  /* #77: @32 = (@32+@33) */
  w32 += w33;
  /* #78: @33 = fabs(@32) */
  w33 = casadi_fabs( w32 );
  /* #79: @33 = (@33<@26) */
  w33  = (w33<w26);
  /* #80: @34 = (@33?@26:0) */
  w34  = (w33?w26:0);
  /* #81: @33 = (!@33) */
  w33 = (! w33 );
  /* #82: @33 = (@33?@32:0) */
  w33  = (w33?w32:0);
  /* #83: @34 = (@34+@33) */
  w34 += w33;
  /* #84: @29 = (@29-@34) */
  w29 -= w34;
  /* #85: @29 = (@29/@34) */
  w29 /= w34;
  /* #86: @29 = (@11*@29) */
  w29  = (w11*w29);
  /* #87: @33 = atan(@29) */
  w33 = atan( w29 );
  /* #88: @33 = (@29-@33) */
  w33  = (w29-w33);
  /* #89: @33 = (@25*@33) */
  w33  = (w25*w33);
  /* #90: @29 = (@29-@33) */
  w29 -= w33;
  /* #91: @29 = atan(@29) */
  w29 = atan( w29 );
  /* #92: @29 = (@10*@29) */
  w29  = (w10*w29);
  /* #93: @29 = sin(@29) */
  w29 = sin( w29 );
  /* #94: @29 = (@28*@29) */
  w29  = (w28*w29);
  /* #95: @33 = (@29*@31) */
  w33  = (w29*w31);
  /* #96: @24 = (@24*@31) */
  w24 *= w31;
  /* #97: @32 = (@17*@30) */
  w32  = (w17*w30);
  /* #98: @24 = (@24-@32) */
  w24 -= w32;
  /* #99: @24 = atan2(@24,@34) */
  w24  = atan2(w24,w34);
  /* #100: @24 = (@11*@24) */
  w24  = (w11*w24);
  /* #101: @34 = atan(@24) */
  w34 = atan( w24 );
  /* #102: @34 = (@24-@34) */
  w34  = (w24-w34);
  /* #103: @34 = (@25*@34) */
  w34  = (w25*w34);
  /* #104: @24 = (@24-@34) */
  w24 -= w34;
  /* #105: @24 = atan(@24) */
  w24 = atan( w24 );
  /* #106: @24 = (@10*@24) */
  w24  = (w10*w24);
  /* #107: @24 = sin(@24) */
  w24 = sin( w24 );
  /* #108: @28 = (@28*@24) */
  w28 *= w24;
  /* #109: @24 = (@28*@30) */
  w24  = (w28*w30);
  /* #110: @33 = (@33-@24) */
  w33 -= w24;
  /* #111: @5 = (@5+@33) */
  w05 += w33;
  /* #112: @24 = @7[5] */
  w24 = wr07[5];
  /* #113: @24 = fmax(@24,@9) */
  w24  = casadi_fmax(w24,w09);
  /* #114: @24 = (@6*@24) */
  w24  = (w06*w24);
  /* #115: @34 = @2[5] */
  w34 = wr02[5];
  /* #116: @32 = (@12*@34) */
  w32  = (w12*w34);
  /* #117: @35 = fabs(@18) */
  w35 = casadi_fabs( w18 );
  /* #118: @35 = (@35<@26) */
  w35  = (w35<w26);
  /* #119: @36 = (@35?@26:0) */
  w36  = (w35?w26:0);
  /* #120: @35 = (!@35) */
  w35 = (! w35 );
  /* #121: @35 = (@35?@18:0) */
  w35  = (w35?w18:0);
  /* #122: @36 = (@36+@35) */
  w36 += w35;
  /* #123: @32 = (@32-@36) */
  w32 -= w36;
  /* #124: @32 = (@32/@36) */
  w32 /= w36;
  /* #125: @32 = (@11*@32) */
  w32  = (w11*w32);
  /* #126: @35 = atan(@32) */
  w35 = atan( w32 );
  /* #127: @35 = (@32-@35) */
  w35  = (w32-w35);
  /* #128: @35 = (@25*@35) */
  w35  = (w25*w35);
  /* #129: @32 = (@32-@35) */
  w32 -= w35;
  /* #130: @32 = atan(@32) */
  w32 = atan( w32 );
  /* #131: @32 = (@10*@32) */
  w32  = (w10*w32);
  /* #132: @32 = sin(@32) */
  w32 = sin( w32 );
  /* #133: @32 = (@24*@32) */
  w32  = (w24*w32);
  /* #134: @5 = (@5+@32) */
  w05 += w32;
  /* #135: @35 = @7[6] */
  w35 = wr07[6];
  /* #136: @35 = fmax(@35,@9) */
  w35  = casadi_fmax(w35,w09);
  /* #137: @6 = (@6*@35) */
  w06 *= w35;
  /* #138: @35 = @2[6] */
  w35 = wr02[6];
  /* #139: @9 = (@12*@35) */
  w09  = (w12*w35);
  /* #140: @18 = fabs(@17) */
  w18 = casadi_fabs( w17 );
  /* #141: @18 = (@18<@26) */
  w18  = (w18<w26);
  /* #142: @26 = (@18?@26:0) */
  w26  = (w18?w26:0);
  /* #143: @18 = (!@18) */
  w18 = (! w18 );
  /* #144: @18 = (@18?@17:0) */
  w18  = (w18?w17:0);
  /* #145: @26 = (@26+@18) */
  w26 += w18;
  /* #146: @9 = (@9-@26) */
  w09 -= w26;
  /* #147: @9 = (@9/@26) */
  w09 /= w26;
  /* #148: @9 = (@11*@9) */
  w09  = (w11*w09);
  /* #149: @18 = atan(@9) */
  w18 = atan( w09 );
  /* #150: @18 = (@9-@18) */
  w18  = (w09-w18);
  /* #151: @18 = (@25*@18) */
  w18  = (w25*w18);
  /* #152: @9 = (@9-@18) */
  w09 -= w18;
  /* #153: @9 = atan(@9) */
  w09 = atan( w09 );
  /* #154: @9 = (@10*@9) */
  w09  = (w10*w09);
  /* #155: @9 = sin(@9) */
  w09 = sin( w09 );
  /* #156: @9 = (@6*@9) */
  w09  = (w06*w09);
  /* #157: @5 = (@5+@9) */
  w05 += w09;
  /* #158: @18 = 0.957 */
  w18 = 9.5700000000000007e-01;
  /* #159: @17 = sq(@15) */
  w17 = casadi_sq( w15 );
  /* #160: @18 = (@18*@17) */
  w18 *= w17;
  /* #161: @5 = (@5-@18) */
  w05 -= w18;
  /* #162: @5 = (@1*@5) */
  w05  = (w01*w05);
  /* #163: @19 = (@14*@19) */
  w19  = (w14*w19);
  /* #164: @8 = (@8*@20) */
  w08 *= w20;
  /* #165: @19 = (@19+@8) */
  w19 += w08;
  /* #166: @15 = (@15*@4) */
  w15 *= w04;
  /* #167: @15 = (@19-@15) */
  w15  = (w19-w15);
  /* #168: @30 = (@29*@30) */
  w30  = (w29*w30);
  /* #169: @28 = (@28*@31) */
  w28 *= w31;
  /* #170: @30 = (@30+@28) */
  w30 += w28;
  /* #171: @15 = (@15+@30) */
  w15 += w30;
  /* #172: @3 = (@3-@23) */
  w03 -= w23;
  /* #173: @36 = atan2(@3,@36) */
  w36  = atan2(w03,w36);
  /* #174: @36 = (@11*@36) */
  w36  = (w11*w36);
  /* #175: @23 = atan(@36) */
  w23 = atan( w36 );
  /* #176: @23 = (@36-@23) */
  w23  = (w36-w23);
  /* #177: @23 = (@25*@23) */
  w23  = (w25*w23);
  /* #178: @36 = (@36-@23) */
  w36 -= w23;
  /* #179: @36 = atan(@36) */
  w36 = atan( w36 );
  /* #180: @36 = (@10*@36) */
  w36  = (w10*w36);
  /* #181: @36 = sin(@36) */
  w36 = sin( w36 );
  /* #182: @24 = (@24*@36) */
  w24 *= w36;
  /* #183: @15 = (@15+@24) */
  w15 += w24;
  /* #184: @3 = atan2(@3,@26) */
  w03  = atan2(w03,w26);
  /* #185: @11 = (@11*@3) */
  w11 *= w03;
  /* #186: @3 = atan(@11) */
  w03 = atan( w11 );
  /* #187: @3 = (@11-@3) */
  w03  = (w11-w03);
  /* #188: @25 = (@25*@3) */
  w25 *= w03;
  /* #189: @11 = (@11-@25) */
  w11 -= w25;
  /* #190: @11 = atan(@11) */
  w11 = atan( w11 );
  /* #191: @10 = (@10*@11) */
  w10 *= w11;
  /* #192: @10 = sin(@10) */
  w10 = sin( w10 );
  /* #193: @6 = (@6*@10) */
  w06 *= w10;
  /* #194: @15 = (@15+@6) */
  w15 += w06;
  /* #195: @1 = (@1*@15) */
  w01 *= w15;
  /* #196: @15 = 0.00787092 */
  w15 = 7.8709169618260532e-03;
  /* #197: @19 = (@19+@30) */
  w19 += w30;
  /* #198: @19 = (@22*@19) */
  w19  = (w22*w19);
  /* #199: @24 = (@24+@6) */
  w24 += w06;
  /* #200: @22 = (@22*@24) */
  w22 *= w24;
  /* #201: @19 = (@19-@22) */
  w19 -= w22;
  /* #202: @33 = (@33-@21) */
  w33 -= w21;
  /* #203: @33 = (@33+@9) */
  w33 += w09;
  /* #204: @33 = (@33-@32) */
  w33 -= w32;
  /* #205: @16 = (@16*@33) */
  w16 *= w33;
  /* #206: @19 = (@19+@16) */
  w19 += w16;
  /* #207: @15 = (@15*@19) */
  w15 *= w19;
  /* #208: @19 = @2[7] */
  w19 = wr02[7];
  /* #209: @14 = (@12*@14) */
  w14  = (w12*w14);
  /* #210: @19 = (@19-@14) */
  w19 -= w14;
  /* #211: @14 = 0.1 */
  w14 = 1.0000000000000001e-01;
  /* #212: @13 = (@13/@14) */
  w13 /= w14;
  /* #213: @13 = tanh(@13) */
  w13 = tanh( w13 );
  /* #214: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #215: @19 = (@19-@13) */
  w19 -= w13;
  /* #216: @13 = 0.15 */
  w13 = 1.4999999999999999e-01;
  /* #217: @19 = (@19/@13) */
  w19 /= w13;
  /* #218: @16 = @2[8] */
  w16 = wr02[8];
  /* #219: @29 = (@12*@29) */
  w29  = (w12*w29);
  /* #220: @16 = (@16-@29) */
  w16 -= w29;
  /* #221: @27 = (@27/@14) */
  w27 /= w14;
  /* #222: @27 = tanh(@27) */
  w27 = tanh( w27 );
  /* #223: @27 = (@14*@27) */
  w27  = (w14*w27);
  /* #224: @16 = (@16-@27) */
  w16 -= w27;
  /* #225: @16 = (@16/@13) */
  w16 /= w13;
  /* #226: @27 = @2[9] */
  w27 = wr02[9];
  /* #227: @32 = (@12*@32) */
  w32  = (w12*w32);
  /* #228: @27 = (@27-@32) */
  w27 -= w32;
  /* #229: @34 = (@34/@14) */
  w34 /= w14;
  /* #230: @34 = tanh(@34) */
  w34 = tanh( w34 );
  /* #231: @34 = (@14*@34) */
  w34  = (w14*w34);
  /* #232: @27 = (@27-@34) */
  w27 -= w34;
  /* #233: @27 = (@27/@13) */
  w27 /= w13;
  /* #234: @34 = @2[10] */
  w34 = wr02[10];
  /* #235: @12 = (@12*@9) */
  w12 *= w09;
  /* #236: @34 = (@34-@12) */
  w34 -= w12;
  /* #237: @35 = (@35/@14) */
  w35 /= w14;
  /* #238: @35 = tanh(@35) */
  w35 = tanh( w35 );
  /* #239: @14 = (@14*@35) */
  w14 *= w35;
  /* #240: @34 = (@34-@14) */
  w34 -= w14;
  /* #241: @34 = (@34/@13) */
  w34 /= w13;
  /* #242: @37 = input[2][0] */
  casadi_copy(arg[2], 4, w37);
  /* #243: @13 = @37[0] */
  for (rr=(&w13), cs=w37+0; cs!=w37+1; cs+=1) *rr++ = *cs;
  /* #244: @14 = @37[1] */
  for (rr=(&w14), cs=w37+1; cs!=w37+2; cs+=1) *rr++ = *cs;
  /* #245: @35 = @37[2] */
  for (rr=(&w35), cs=w37+2; cs!=w37+3; cs+=1) *rr++ = *cs;
  /* #246: @12 = @37[3] */
  for (rr=(&w12), cs=w37+3; cs!=w37+4; cs+=1) *rr++ = *cs;
  /* #247: @2 = vertcat(@5, @1, @15, @19, @16, @27, @34, @13, @14, @35, @12) */
  rr=w02;
  *rr++ = w05;
  *rr++ = w01;
  *rr++ = w15;
  *rr++ = w19;
  *rr++ = w16;
  *rr++ = w27;
  *rr++ = w34;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w35;
  *rr++ = w12;
  /* #248: @0 = (@0-@2) */
  for (i=0, rr=w00, cr=wr00, cs=w02; i<11; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #249: output[0][0] = @0 */
  casadi_copy(w00, 11, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_impl_dae_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 68;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_impl_dae_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 68*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
