/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {8, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_expl_ode_fun:(i0[11],i1[4],i2[8])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w02, w03, w04, w05, w07, w08, w09, w10, w11, w12;
  casadi_real w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24;
  casadi_real w25, w26, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36;
  casadi_real *w37=w+54;
  const casadi_real *cs, *wr01, *wr06;
  /* #0: @0 = 0.00333333 */
  w00 = 3.3333333333333335e-03;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[1] */
  w02 = wr01[1];
  /* #3: @3 = @1[2] */
  w03 = wr01[2];
  /* #4: @4 = (@2*@3) */
  w04  = (w02*w03);
  /* #5: @5 = 1.5 */
  w05 = 1.5000000000000000e+00;
  /* #6: @6 = input[2][0] */
  wr06 = arg[2] ? arg[2] : casadi_zeros;
  /* #7: @7 = @6[3] */
  w07 = wr06[3];
  /* #8: @8 = 10 */
  w08 = 10.;
  /* #9: @7 = fmax(@7,@8) */
  w07  = casadi_fmax(w07,w08);
  /* #10: @7 = (@5*@7) */
  w07  = (w05*w07);
  /* #11: @9 = 1.3 */
  w09 = 1.3000000000000000e+00;
  /* #12: @10 = 9 */
  w10 = 9.;
  /* #13: @11 = 0.0001 */
  w11 = 1.0000000000000000e-04;
  /* #14: @12 = 0.193 */
  w12 = 1.9300000000000000e-01;
  /* #15: @13 = @1[3] */
  w13 = wr01[3];
  /* #16: @14 = (@12*@13) */
  w14  = (w12*w13);
  /* #17: @15 = 0.01 */
  w15 = 1.0000000000000002e-02;
  /* #18: @16 = @1[0] */
  w16 = wr01[0];
  /* #19: @17 = 0.621 */
  w17 = 6.2100000000000000e-01;
  /* #20: @18 = (@17*@3) */
  w18  = (w17*w03);
  /* #21: @19 = (@16-@18) */
  w19  = (w16-w18);
  /* #22: @20 = @6[1] */
  w20 = wr06[1];
  /* #23: @21 = cos(@20) */
  w21 = cos( w20 );
  /* #24: @22 = (@19*@21) */
  w22  = (w19*w21);
  /* #25: @23 = 0.765 */
  w23 = 7.6500000000000001e-01;
  /* #26: @24 = (@23*@3) */
  w24  = (w23*w03);
  /* #27: @25 = (@2+@24) */
  w25  = (w02+w24);
  /* #28: @20 = sin(@20) */
  w20 = sin( w20 );
  /* #29: @26 = (@25*@20) */
  w26  = (w25*w20);
  /* #30: @22 = (@22+@26) */
  w22 += w26;
  /* #31: @22 = sq(@22) */
  w22 = casadi_sq( w22 );
  /* #32: @22 = (@15+@22) */
  w22  = (w15+w22);
  /* #33: @22 = sqrt(@22) */
  w22 = sqrt( w22 );
  /* #34: @14 = (@14-@22) */
  w14 -= w22;
  /* #35: @14 = (@14/@22) */
  w14 /= w22;
  /* #36: @26 = sq(@14) */
  w26 = casadi_sq( w14 );
  /* #37: @27 = (@25*@21) */
  w27  = (w25*w21);
  /* #38: @28 = (@19*@20) */
  w28  = (w19*w20);
  /* #39: @27 = (@27-@28) */
  w27 -= w28;
  /* #40: @27 = atan2(@27,@22) */
  w27  = atan2(w27,w22);
  /* #41: @22 = sq(@27) */
  w22 = casadi_sq( w27 );
  /* #42: @26 = (@26+@22) */
  w26 += w22;
  /* #43: @26 = (@11+@26) */
  w26  = (w11+w26);
  /* #44: @26 = sqrt(@26) */
  w26 = sqrt( w26 );
  /* #45: @22 = (@10*@26) */
  w22  = (w10*w26);
  /* #46: @28 = 0.7 */
  w28 = 6.9999999999999996e-01;
  /* #47: @29 = atan(@22) */
  w29 = atan( w22 );
  /* #48: @29 = (@22-@29) */
  w29  = (w22-w29);
  /* #49: @29 = (@28*@29) */
  w29  = (w28*w29);
  /* #50: @22 = (@22-@29) */
  w22 -= w29;
  /* #51: @22 = atan(@22) */
  w22 = atan( w22 );
  /* #52: @22 = (@9*@22) */
  w22  = (w09*w22);
  /* #53: @22 = sin(@22) */
  w22 = sin( w22 );
  /* #54: @7 = (@7*@22) */
  w07 *= w22;
  /* #55: @14 = (@14/@26) */
  w14 /= w26;
  /* #56: @14 = (@7*@14) */
  w14  = (w07*w14);
  /* #57: @22 = (@14*@21) */
  w22  = (w14*w21);
  /* #58: @27 = (@27/@26) */
  w27 /= w26;
  /* #59: @7 = (@7*@27) */
  w07 *= w27;
  /* #60: @27 = (@7*@20) */
  w27  = (w07*w20);
  /* #61: @22 = (@22+@27) */
  w22 += w27;
  /* #62: @4 = (@4+@22) */
  w04 += w22;
  /* #63: @27 = @6[4] */
  w27 = wr06[4];
  /* #64: @27 = fmax(@27,@8) */
  w27  = casadi_fmax(w27,w08);
  /* #65: @27 = (@5*@27) */
  w27  = (w05*w27);
  /* #66: @26 = @1[4] */
  w26 = wr01[4];
  /* #67: @29 = (@12*@26) */
  w29  = (w12*w26);
  /* #68: @18 = (@16+@18) */
  w18  = (w16+w18);
  /* #69: @30 = @6[2] */
  w30 = wr06[2];
  /* #70: @31 = cos(@30) */
  w31 = cos( w30 );
  /* #71: @32 = (@18*@31) */
  w32  = (w18*w31);
  /* #72: @30 = sin(@30) */
  w30 = sin( w30 );
  /* #73: @33 = (@25*@30) */
  w33  = (w25*w30);
  /* #74: @32 = (@32+@33) */
  w32 += w33;
  /* #75: @32 = sq(@32) */
  w32 = casadi_sq( w32 );
  /* #76: @32 = (@15+@32) */
  w32  = (w15+w32);
  /* #77: @32 = sqrt(@32) */
  w32 = sqrt( w32 );
  /* #78: @29 = (@29-@32) */
  w29 -= w32;
  /* #79: @29 = (@29/@32) */
  w29 /= w32;
  /* #80: @33 = sq(@29) */
  w33 = casadi_sq( w29 );
  /* #81: @25 = (@25*@31) */
  w25 *= w31;
  /* #82: @34 = (@18*@30) */
  w34  = (w18*w30);
  /* #83: @25 = (@25-@34) */
  w25 -= w34;
  /* #84: @25 = atan2(@25,@32) */
  w25  = atan2(w25,w32);
  /* #85: @32 = sq(@25) */
  w32 = casadi_sq( w25 );
  /* #86: @33 = (@33+@32) */
  w33 += w32;
  /* #87: @33 = (@11+@33) */
  w33  = (w11+w33);
  /* #88: @33 = sqrt(@33) */
  w33 = sqrt( w33 );
  /* #89: @32 = (@10*@33) */
  w32  = (w10*w33);
  /* #90: @34 = atan(@32) */
  w34 = atan( w32 );
  /* #91: @34 = (@32-@34) */
  w34  = (w32-w34);
  /* #92: @34 = (@28*@34) */
  w34  = (w28*w34);
  /* #93: @32 = (@32-@34) */
  w32 -= w34;
  /* #94: @32 = atan(@32) */
  w32 = atan( w32 );
  /* #95: @32 = (@9*@32) */
  w32  = (w09*w32);
  /* #96: @32 = sin(@32) */
  w32 = sin( w32 );
  /* #97: @27 = (@27*@32) */
  w27 *= w32;
  /* #98: @29 = (@29/@33) */
  w29 /= w33;
  /* #99: @29 = (@27*@29) */
  w29  = (w27*w29);
  /* #100: @32 = (@29*@31) */
  w32  = (w29*w31);
  /* #101: @25 = (@25/@33) */
  w25 /= w33;
  /* #102: @27 = (@27*@25) */
  w27 *= w25;
  /* #103: @25 = (@27*@30) */
  w25  = (w27*w30);
  /* #104: @32 = (@32+@25) */
  w32 += w25;
  /* #105: @4 = (@4+@32) */
  w04 += w32;
  /* #106: @25 = @6[5] */
  w25 = wr06[5];
  /* #107: @25 = fmax(@25,@8) */
  w25  = casadi_fmax(w25,w08);
  /* #108: @25 = (@5*@25) */
  w25  = (w05*w25);
  /* #109: @33 = @1[5] */
  w33 = wr01[5];
  /* #110: @34 = (@12*@33) */
  w34  = (w12*w33);
  /* #111: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #112: @19 = (@15+@19) */
  w19  = (w15+w19);
  /* #113: @19 = sqrt(@19) */
  w19 = sqrt( w19 );
  /* #114: @34 = (@34-@19) */
  w34 -= w19;
  /* #115: @34 = (@34/@19) */
  w34 /= w19;
  /* #116: @35 = sq(@34) */
  w35 = casadi_sq( w34 );
  /* #117: @2 = (@2-@24) */
  w02 -= w24;
  /* #118: @19 = atan2(@2,@19) */
  w19  = atan2(w02,w19);
  /* #119: @24 = sq(@19) */
  w24 = casadi_sq( w19 );
  /* #120: @35 = (@35+@24) */
  w35 += w24;
  /* #121: @35 = (@11+@35) */
  w35  = (w11+w35);
  /* #122: @35 = sqrt(@35) */
  w35 = sqrt( w35 );
  /* #123: @24 = (@10*@35) */
  w24  = (w10*w35);
  /* #124: @36 = atan(@24) */
  w36 = atan( w24 );
  /* #125: @36 = (@24-@36) */
  w36  = (w24-w36);
  /* #126: @36 = (@28*@36) */
  w36  = (w28*w36);
  /* #127: @24 = (@24-@36) */
  w24 -= w36;
  /* #128: @24 = atan(@24) */
  w24 = atan( w24 );
  /* #129: @24 = (@9*@24) */
  w24  = (w09*w24);
  /* #130: @24 = sin(@24) */
  w24 = sin( w24 );
  /* #131: @25 = (@25*@24) */
  w25 *= w24;
  /* #132: @34 = (@34/@35) */
  w34 /= w35;
  /* #133: @34 = (@25*@34) */
  w34  = (w25*w34);
  /* #134: @4 = (@4+@34) */
  w04 += w34;
  /* #135: @24 = @6[6] */
  w24 = wr06[6];
  /* #136: @24 = fmax(@24,@8) */
  w24  = casadi_fmax(w24,w08);
  /* #137: @5 = (@5*@24) */
  w05 *= w24;
  /* #138: @24 = @1[6] */
  w24 = wr01[6];
  /* #139: @8 = (@12*@24) */
  w08  = (w12*w24);
  /* #140: @18 = sq(@18) */
  w18 = casadi_sq( w18 );
  /* #141: @15 = (@15+@18) */
  w15 += w18;
  /* #142: @15 = sqrt(@15) */
  w15 = sqrt( w15 );
  /* #143: @8 = (@8-@15) */
  w08 -= w15;
  /* #144: @8 = (@8/@15) */
  w08 /= w15;
  /* #145: @18 = sq(@8) */
  w18 = casadi_sq( w08 );
  /* #146: @2 = atan2(@2,@15) */
  w02  = atan2(w02,w15);
  /* #147: @15 = sq(@2) */
  w15 = casadi_sq( w02 );
  /* #148: @18 = (@18+@15) */
  w18 += w15;
  /* #149: @11 = (@11+@18) */
  w11 += w18;
  /* #150: @11 = sqrt(@11) */
  w11 = sqrt( w11 );
  /* #151: @10 = (@10*@11) */
  w10 *= w11;
  /* #152: @18 = atan(@10) */
  w18 = atan( w10 );
  /* #153: @18 = (@10-@18) */
  w18  = (w10-w18);
  /* #154: @28 = (@28*@18) */
  w28 *= w18;
  /* #155: @10 = (@10-@28) */
  w10 -= w28;
  /* #156: @10 = atan(@10) */
  w10 = atan( w10 );
  /* #157: @9 = (@9*@10) */
  w09 *= w10;
  /* #158: @9 = sin(@9) */
  w09 = sin( w09 );
  /* #159: @5 = (@5*@9) */
  w05 *= w09;
  /* #160: @8 = (@8/@11) */
  w08 /= w11;
  /* #161: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #162: @4 = (@4+@8) */
  w04 += w08;
  /* #163: @9 = 0.957 */
  w09 = 9.5700000000000007e-01;
  /* #164: @10 = sq(@16) */
  w10 = casadi_sq( w16 );
  /* #165: @9 = (@9*@10) */
  w09 *= w10;
  /* #166: @4 = (@4-@9) */
  w04 -= w09;
  /* #167: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #168: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #169: @20 = (@14*@20) */
  w20  = (w14*w20);
  /* #170: @7 = (@7*@21) */
  w07 *= w21;
  /* #171: @20 = (@20-@7) */
  w20 -= w07;
  /* #172: @16 = (@16*@3) */
  w16 *= w03;
  /* #173: @16 = (@20-@16) */
  w16  = (w20-w16);
  /* #174: @30 = (@29*@30) */
  w30  = (w29*w30);
  /* #175: @27 = (@27*@31) */
  w27 *= w31;
  /* #176: @30 = (@30-@27) */
  w30 -= w27;
  /* #177: @16 = (@16+@30) */
  w16 += w30;
  /* #178: @19 = (@19/@35) */
  w19 /= w35;
  /* #179: @25 = (@25*@19) */
  w25 *= w19;
  /* #180: @16 = (@16-@25) */
  w16 -= w25;
  /* #181: @2 = (@2/@11) */
  w02 /= w11;
  /* #182: @5 = (@5*@2) */
  w05 *= w02;
  /* #183: @16 = (@16-@5) */
  w16 -= w05;
  /* #184: @0 = (@0*@16) */
  w00 *= w16;
  /* #185: output[0][1] = @0 */
  if (res[0]) res[0][1] = w00;
  /* #186: @0 = 0.00787092 */
  w00 = 7.8709169618260532e-03;
  /* #187: @20 = (@20+@30) */
  w20 += w30;
  /* #188: @20 = (@23*@20) */
  w20  = (w23*w20);
  /* #189: @5 = (-@5) */
  w05 = (- w05 );
  /* #190: @5 = (@5-@25) */
  w05 -= w25;
  /* #191: @23 = (@23*@5) */
  w23 *= w05;
  /* #192: @20 = (@20-@23) */
  w20 -= w23;
  /* #193: @32 = (@32-@22) */
  w32 -= w22;
  /* #194: @32 = (@32+@8) */
  w32 += w08;
  /* #195: @32 = (@32-@34) */
  w32 -= w34;
  /* #196: @17 = (@17*@32) */
  w17 *= w32;
  /* #197: @20 = (@20+@17) */
  w20 += w17;
  /* #198: @0 = (@0*@20) */
  w00 *= w20;
  /* #199: output[0][2] = @0 */
  if (res[0]) res[0][2] = w00;
  /* #200: @0 = @1[7] */
  w00 = wr01[7];
  /* #201: @14 = (@12*@14) */
  w14  = (w12*w14);
  /* #202: @0 = (@0-@14) */
  w00 -= w14;
  /* #203: @14 = 0.1 */
  w14 = 1.0000000000000001e-01;
  /* #204: @13 = (@13/@14) */
  w13 /= w14;
  /* #205: @13 = tanh(@13) */
  w13 = tanh( w13 );
  /* #206: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #207: @0 = (@0-@13) */
  w00 -= w13;
  /* #208: @13 = 0.15 */
  w13 = 1.4999999999999999e-01;
  /* #209: @0 = (@0/@13) */
  w00 /= w13;
  /* #210: output[0][3] = @0 */
  if (res[0]) res[0][3] = w00;
  /* #211: @0 = @1[8] */
  w00 = wr01[8];
  /* #212: @29 = (@12*@29) */
  w29  = (w12*w29);
  /* #213: @0 = (@0-@29) */
  w00 -= w29;
  /* #214: @26 = (@26/@14) */
  w26 /= w14;
  /* #215: @26 = tanh(@26) */
  w26 = tanh( w26 );
  /* #216: @26 = (@14*@26) */
  w26  = (w14*w26);
  /* #217: @0 = (@0-@26) */
  w00 -= w26;
  /* #218: @0 = (@0/@13) */
  w00 /= w13;
  /* #219: output[0][4] = @0 */
  if (res[0]) res[0][4] = w00;
  /* #220: @0 = @1[9] */
  w00 = wr01[9];
  /* #221: @34 = (@12*@34) */
  w34  = (w12*w34);
  /* #222: @0 = (@0-@34) */
  w00 -= w34;
  /* #223: @33 = (@33/@14) */
  w33 /= w14;
  /* #224: @33 = tanh(@33) */
  w33 = tanh( w33 );
  /* #225: @33 = (@14*@33) */
  w33  = (w14*w33);
  /* #226: @0 = (@0-@33) */
  w00 -= w33;
  /* #227: @0 = (@0/@13) */
  w00 /= w13;
  /* #228: output[0][5] = @0 */
  if (res[0]) res[0][5] = w00;
  /* #229: @0 = @1[10] */
  w00 = wr01[10];
  /* #230: @12 = (@12*@8) */
  w12 *= w08;
  /* #231: @0 = (@0-@12) */
  w00 -= w12;
  /* #232: @24 = (@24/@14) */
  w24 /= w14;
  /* #233: @24 = tanh(@24) */
  w24 = tanh( w24 );
  /* #234: @14 = (@14*@24) */
  w14 *= w24;
  /* #235: @0 = (@0-@14) */
  w00 -= w14;
  /* #236: @0 = (@0/@13) */
  w00 /= w13;
  /* #237: output[0][6] = @0 */
  if (res[0]) res[0][6] = w00;
  /* #238: @37 = input[1][0] */
  casadi_copy(arg[1], 4, w37);
  /* #239: @0 = @37[0] */
  for (rr=(&w00), cs=w37+0; cs!=w37+1; cs+=1) *rr++ = *cs;
  /* #240: output[0][7] = @0 */
  if (res[0]) res[0][7] = w00;
  /* #241: @0 = @37[1] */
  for (rr=(&w00), cs=w37+1; cs!=w37+2; cs+=1) *rr++ = *cs;
  /* #242: output[0][8] = @0 */
  if (res[0]) res[0][8] = w00;
  /* #243: @0 = @37[2] */
  for (rr=(&w00), cs=w37+2; cs!=w37+3; cs+=1) *rr++ = *cs;
  /* #244: output[0][9] = @0 */
  if (res[0]) res[0][9] = w00;
  /* #245: @0 = @37[3] */
  for (rr=(&w00), cs=w37+3; cs!=w37+4; cs+=1) *rr++ = *cs;
  /* #246: output[0][10] = @0 */
  if (res[0]) res[0][10] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 58;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 58*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
