/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {12, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_constr_h_fun:(i0[11],i1[4],i2[],i3[8])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w00, w02, w03, w04, w05, w06, w07, w09, w10, w11, w12, w13;
  casadi_real w14, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  const casadi_real *wr01, *wr08;
  /* #0: @0 = 1.5 */
  w00 = 1.5000000000000000e+00;
  /* #1: @1 = input[3][0] */
  wr01 = arg[3] ? arg[3] : casadi_zeros;
  /* #2: @2 = @1[3] */
  w02 = wr01[3];
  /* #3: @3 = 10 */
  w03 = 10.;
  /* #4: @2 = fmax(@2,@3) */
  w02  = casadi_fmax(w02,w03);
  /* #5: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #6: @4 = 1.3 */
  w04 = 1.3000000000000000e+00;
  /* #7: @5 = 9 */
  w05 = 9.;
  /* #8: @6 = 0.0001 */
  w06 = 1.0000000000000000e-04;
  /* #9: @7 = 0.193 */
  w07 = 1.9300000000000000e-01;
  /* #10: @8 = input[0][0] */
  wr08 = arg[0] ? arg[0] : casadi_zeros;
  /* #11: @9 = @8[3] */
  w09 = wr08[3];
  /* #12: @9 = (@7*@9) */
  w09  = (w07*w09);
  /* #13: @10 = 0.01 */
  w10 = 1.0000000000000002e-02;
  /* #14: @11 = @8[0] */
  w11 = wr08[0];
  /* #15: @12 = 0.621 */
  w12 = 6.2100000000000000e-01;
  /* #16: @13 = @8[2] */
  w13 = wr08[2];
  /* #17: @12 = (@12*@13) */
  w12 *= w13;
  /* #18: @14 = (@11-@12) */
  w14  = (w11-w12);
  /* #19: @15 = @1[1] */
  w15 = wr01[1];
  /* #20: @16 = cos(@15) */
  w16 = cos( w15 );
  /* #21: @17 = (@14*@16) */
  w17  = (w14*w16);
  /* #22: @18 = @8[1] */
  w18 = wr08[1];
  /* #23: @19 = 0.765 */
  w19 = 7.6500000000000001e-01;
  /* #24: @19 = (@19*@13) */
  w19 *= w13;
  /* #25: @13 = (@18+@19) */
  w13  = (w18+w19);
  /* #26: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #27: @20 = (@13*@15) */
  w20  = (w13*w15);
  /* #28: @17 = (@17+@20) */
  w17 += w20;
  /* #29: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #30: @17 = (@10+@17) */
  w17  = (w10+w17);
  /* #31: @17 = sqrt(@17) */
  w17 = sqrt( w17 );
  /* #32: @9 = (@9-@17) */
  w09 -= w17;
  /* #33: @9 = (@9/@17) */
  w09 /= w17;
  /* #34: @20 = sq(@9) */
  w20 = casadi_sq( w09 );
  /* #35: @21 = (@13*@16) */
  w21  = (w13*w16);
  /* #36: @22 = (@14*@15) */
  w22  = (w14*w15);
  /* #37: @21 = (@21-@22) */
  w21 -= w22;
  /* #38: @21 = atan2(@21,@17) */
  w21  = atan2(w21,w17);
  /* #39: @17 = sq(@21) */
  w17 = casadi_sq( w21 );
  /* #40: @20 = (@20+@17) */
  w20 += w17;
  /* #41: @20 = (@6+@20) */
  w20  = (w06+w20);
  /* #42: @20 = sqrt(@20) */
  w20 = sqrt( w20 );
  /* #43: @17 = (@5*@20) */
  w17  = (w05*w20);
  /* #44: @22 = 0.7 */
  w22 = 6.9999999999999996e-01;
  /* #45: @23 = atan(@17) */
  w23 = atan( w17 );
  /* #46: @23 = (@17-@23) */
  w23  = (w17-w23);
  /* #47: @23 = (@22*@23) */
  w23  = (w22*w23);
  /* #48: @17 = (@17-@23) */
  w17 -= w23;
  /* #49: @17 = atan(@17) */
  w17 = atan( w17 );
  /* #50: @17 = (@4*@17) */
  w17  = (w04*w17);
  /* #51: @17 = sin(@17) */
  w17 = sin( w17 );
  /* #52: @17 = (@2*@17) */
  w17  = (w02*w17);
  /* #53: @9 = (@9/@20) */
  w09 /= w20;
  /* #54: @9 = (@17*@9) */
  w09  = (w17*w09);
  /* #55: @23 = (@9*@16) */
  w23  = (w09*w16);
  /* #56: @21 = (@21/@20) */
  w21 /= w20;
  /* #57: @17 = (@17*@21) */
  w17 *= w21;
  /* #58: @21 = (@17*@15) */
  w21  = (w17*w15);
  /* #59: @23 = (@23+@21) */
  w23 += w21;
  /* #60: @23 = (@23/@2) */
  w23 /= w02;
  /* #61: @23 = sq(@23) */
  w23 = casadi_sq( w23 );
  /* #62: @9 = (@9*@15) */
  w09 *= w15;
  /* #63: @17 = (@17*@16) */
  w17 *= w16;
  /* #64: @9 = (@9-@17) */
  w09 -= w17;
  /* #65: @9 = (@9/@2) */
  w09 /= w02;
  /* #66: @9 = sq(@9) */
  w09 = casadi_sq( w09 );
  /* #67: @23 = (@23+@9) */
  w23 += w09;
  /* #68: @9 = 1 */
  w09 = 1.;
  /* #69: @23 = (@23-@9) */
  w23 -= w09;
  /* #70: output[0][0] = @23 */
  if (res[0]) res[0][0] = w23;
  /* #71: @23 = @1[4] */
  w23 = wr01[4];
  /* #72: @23 = fmax(@23,@3) */
  w23  = casadi_fmax(w23,w03);
  /* #73: @23 = (@0*@23) */
  w23  = (w00*w23);
  /* #74: @2 = @8[4] */
  w02 = wr08[4];
  /* #75: @2 = (@7*@2) */
  w02  = (w07*w02);
  /* #76: @11 = (@11+@12) */
  w11 += w12;
  /* #77: @12 = @1[2] */
  w12 = wr01[2];
  /* #78: @17 = cos(@12) */
  w17 = cos( w12 );
  /* #79: @16 = (@11*@17) */
  w16  = (w11*w17);
  /* #80: @12 = sin(@12) */
  w12 = sin( w12 );
  /* #81: @15 = (@13*@12) */
  w15  = (w13*w12);
  /* #82: @16 = (@16+@15) */
  w16 += w15;
  /* #83: @16 = sq(@16) */
  w16 = casadi_sq( w16 );
  /* #84: @16 = (@10+@16) */
  w16  = (w10+w16);
  /* #85: @16 = sqrt(@16) */
  w16 = sqrt( w16 );
  /* #86: @2 = (@2-@16) */
  w02 -= w16;
  /* #87: @2 = (@2/@16) */
  w02 /= w16;
  /* #88: @15 = sq(@2) */
  w15 = casadi_sq( w02 );
  /* #89: @13 = (@13*@17) */
  w13 *= w17;
  /* #90: @21 = (@11*@12) */
  w21  = (w11*w12);
  /* #91: @13 = (@13-@21) */
  w13 -= w21;
  /* #92: @13 = atan2(@13,@16) */
  w13  = atan2(w13,w16);
  /* #93: @16 = sq(@13) */
  w16 = casadi_sq( w13 );
  /* #94: @15 = (@15+@16) */
  w15 += w16;
  /* #95: @15 = (@6+@15) */
  w15  = (w06+w15);
  /* #96: @15 = sqrt(@15) */
  w15 = sqrt( w15 );
  /* #97: @16 = (@5*@15) */
  w16  = (w05*w15);
  /* #98: @21 = atan(@16) */
  w21 = atan( w16 );
  /* #99: @21 = (@16-@21) */
  w21  = (w16-w21);
  /* #100: @21 = (@22*@21) */
  w21  = (w22*w21);
  /* #101: @16 = (@16-@21) */
  w16 -= w21;
  /* #102: @16 = atan(@16) */
  w16 = atan( w16 );
  /* #103: @16 = (@4*@16) */
  w16  = (w04*w16);
  /* #104: @16 = sin(@16) */
  w16 = sin( w16 );
  /* #105: @16 = (@23*@16) */
  w16  = (w23*w16);
  /* #106: @2 = (@2/@15) */
  w02 /= w15;
  /* #107: @2 = (@16*@2) */
  w02  = (w16*w02);
  /* #108: @21 = (@2*@17) */
  w21  = (w02*w17);
  /* #109: @13 = (@13/@15) */
  w13 /= w15;
  /* #110: @16 = (@16*@13) */
  w16 *= w13;
  /* #111: @13 = (@16*@12) */
  w13  = (w16*w12);
  /* #112: @21 = (@21+@13) */
  w21 += w13;
  /* #113: @21 = (@21/@23) */
  w21 /= w23;
  /* #114: @21 = sq(@21) */
  w21 = casadi_sq( w21 );
  /* #115: @2 = (@2*@12) */
  w02 *= w12;
  /* #116: @16 = (@16*@17) */
  w16 *= w17;
  /* #117: @2 = (@2-@16) */
  w02 -= w16;
  /* #118: @2 = (@2/@23) */
  w02 /= w23;
  /* #119: @2 = sq(@2) */
  w02 = casadi_sq( w02 );
  /* #120: @21 = (@21+@2) */
  w21 += w02;
  /* #121: @21 = (@21-@9) */
  w21 -= w09;
  /* #122: output[0][1] = @21 */
  if (res[0]) res[0][1] = w21;
  /* #123: @21 = @1[5] */
  w21 = wr01[5];
  /* #124: @21 = fmax(@21,@3) */
  w21  = casadi_fmax(w21,w03);
  /* #125: @21 = (@0*@21) */
  w21  = (w00*w21);
  /* #126: @2 = @8[5] */
  w02 = wr08[5];
  /* #127: @2 = (@7*@2) */
  w02  = (w07*w02);
  /* #128: @14 = sq(@14) */
  w14 = casadi_sq( w14 );
  /* #129: @14 = (@10+@14) */
  w14  = (w10+w14);
  /* #130: @14 = sqrt(@14) */
  w14 = sqrt( w14 );
  /* #131: @2 = (@2-@14) */
  w02 -= w14;
  /* #132: @2 = (@2/@14) */
  w02 /= w14;
  /* #133: @23 = sq(@2) */
  w23 = casadi_sq( w02 );
  /* #134: @18 = (@18-@19) */
  w18 -= w19;
  /* #135: @14 = atan2(@18,@14) */
  w14  = atan2(w18,w14);
  /* #136: @19 = sq(@14) */
  w19 = casadi_sq( w14 );
  /* #137: @23 = (@23+@19) */
  w23 += w19;
  /* #138: @23 = (@6+@23) */
  w23  = (w06+w23);
  /* #139: @23 = sqrt(@23) */
  w23 = sqrt( w23 );
  /* #140: @19 = (@5*@23) */
  w19  = (w05*w23);
  /* #141: @16 = atan(@19) */
  w16 = atan( w19 );
  /* #142: @16 = (@19-@16) */
  w16  = (w19-w16);
  /* #143: @16 = (@22*@16) */
  w16  = (w22*w16);
  /* #144: @19 = (@19-@16) */
  w19 -= w16;
  /* #145: @19 = atan(@19) */
  w19 = atan( w19 );
  /* #146: @19 = (@4*@19) */
  w19  = (w04*w19);
  /* #147: @19 = sin(@19) */
  w19 = sin( w19 );
  /* #148: @19 = (@21*@19) */
  w19  = (w21*w19);
  /* #149: @2 = (@2/@23) */
  w02 /= w23;
  /* #150: @2 = (@19*@2) */
  w02  = (w19*w02);
  /* #151: @2 = (@2/@21) */
  w02 /= w21;
  /* #152: @2 = sq(@2) */
  w02 = casadi_sq( w02 );
  /* #153: @14 = (@14/@23) */
  w14 /= w23;
  /* #154: @19 = (@19*@14) */
  w19 *= w14;
  /* #155: @19 = (@19/@21) */
  w19 /= w21;
  /* #156: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #157: @2 = (@2+@19) */
  w02 += w19;
  /* #158: @2 = (@2-@9) */
  w02 -= w09;
  /* #159: output[0][2] = @2 */
  if (res[0]) res[0][2] = w02;
  /* #160: @2 = @1[6] */
  w02 = wr01[6];
  /* #161: @2 = fmax(@2,@3) */
  w02  = casadi_fmax(w02,w03);
  /* #162: @0 = (@0*@2) */
  w00 *= w02;
  /* #163: @2 = @8[6] */
  w02 = wr08[6];
  /* #164: @7 = (@7*@2) */
  w07 *= w02;
  /* #165: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #166: @10 = (@10+@11) */
  w10 += w11;
  /* #167: @10 = sqrt(@10) */
  w10 = sqrt( w10 );
  /* #168: @7 = (@7-@10) */
  w07 -= w10;
  /* #169: @7 = (@7/@10) */
  w07 /= w10;
  /* #170: @11 = sq(@7) */
  w11 = casadi_sq( w07 );
  /* #171: @18 = atan2(@18,@10) */
  w18  = atan2(w18,w10);
  /* #172: @10 = sq(@18) */
  w10 = casadi_sq( w18 );
  /* #173: @11 = (@11+@10) */
  w11 += w10;
  /* #174: @6 = (@6+@11) */
  w06 += w11;
  /* #175: @6 = sqrt(@6) */
  w06 = sqrt( w06 );
  /* #176: @5 = (@5*@6) */
  w05 *= w06;
  /* #177: @11 = atan(@5) */
  w11 = atan( w05 );
  /* #178: @11 = (@5-@11) */
  w11  = (w05-w11);
  /* #179: @22 = (@22*@11) */
  w22 *= w11;
  /* #180: @5 = (@5-@22) */
  w05 -= w22;
  /* #181: @5 = atan(@5) */
  w05 = atan( w05 );
  /* #182: @4 = (@4*@5) */
  w04 *= w05;
  /* #183: @4 = sin(@4) */
  w04 = sin( w04 );
  /* #184: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #185: @7 = (@7/@6) */
  w07 /= w06;
  /* #186: @7 = (@4*@7) */
  w07  = (w04*w07);
  /* #187: @7 = (@7/@0) */
  w07 /= w00;
  /* #188: @7 = sq(@7) */
  w07 = casadi_sq( w07 );
  /* #189: @18 = (@18/@6) */
  w18 /= w06;
  /* #190: @4 = (@4*@18) */
  w04 *= w18;
  /* #191: @4 = (@4/@0) */
  w04 /= w00;
  /* #192: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #193: @7 = (@7+@4) */
  w07 += w04;
  /* #194: @7 = (@7-@9) */
  w07 -= w09;
  /* #195: output[0][3] = @7 */
  if (res[0]) res[0][3] = w07;
  /* #196: @7 = -10 */
  w07 = -10.;
  /* #197: @9 = @8[7] */
  w09 = wr08[7];
  /* #198: @4 = (@7-@9) */
  w04  = (w07-w09);
  /* #199: output[0][4] = @4 */
  if (res[0]) res[0][4] = w04;
  /* #200: @4 = @8[8] */
  w04 = wr08[8];
  /* #201: @0 = (@7-@4) */
  w00  = (w07-w04);
  /* #202: output[0][5] = @0 */
  if (res[0]) res[0][5] = w00;
  /* #203: @0 = @8[9] */
  w00 = wr08[9];
  /* #204: @18 = (@7-@0) */
  w18  = (w07-w00);
  /* #205: output[0][6] = @18 */
  if (res[0]) res[0][6] = w18;
  /* #206: @18 = @8[10] */
  w18 = wr08[10];
  /* #207: @7 = (@7-@18) */
  w07 -= w18;
  /* #208: output[0][7] = @7 */
  if (res[0]) res[0][7] = w07;
  /* #209: @7 = 143 */
  w07 = 143.;
  /* #210: @9 = (@9-@7) */
  w09 -= w07;
  /* #211: output[0][8] = @9 */
  if (res[0]) res[0][8] = w09;
  /* #212: @4 = (@4-@7) */
  w04 -= w07;
  /* #213: output[0][9] = @4 */
  if (res[0]) res[0][9] = w04;
  /* #214: @0 = (@0-@7) */
  w00 -= w07;
  /* #215: output[0][10] = @0 */
  if (res[0]) res[0][10] = w00;
  /* #216: @18 = (@18-@7) */
  w18 -= w07;
  /* #217: output[0][11] = @18 */
  if (res[0]) res[0][11] = w18;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 41;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 41*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
