/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};

static const casadi_real casadi_zeros[8] = {0., 0., 0., 0., 0., 0., 0., 0.};

/* tv_nmpc_constr_h_fun:(i0[7],i1[4],i2[],i3[8])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w02, w03, w04, w05, w06, *w07=w+14, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22;
  const casadi_real *cs, *wr01;
  /* #0: @0 = 1.5 */
  w00 = 1.5000000000000000e+00;
  /* #1: @1 = input[3][0] */
  wr01 = arg[3] ? arg[3] : casadi_zeros;
  /* #2: @2 = @1[3] */
  w02 = wr01[3];
  /* #3: @3 = 10 */
  w03 = 10.;
  /* #4: @2 = fmax(@2,@3) */
  w02  = casadi_fmax(w02,w03);
  /* #5: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #6: @4 = 1.3 */
  w04 = 1.3000000000000000e+00;
  /* #7: @5 = 25 */
  w05 = 25.;
  /* #8: @6 = 0.193 */
  w06 = 1.9300000000000000e-01;
  /* #9: @7 = input[0][0] */
  casadi_copy(arg[0], 7, w07);
  /* #10: @8 = @7[3] */
  for (rr=(&w08), cs=w07+3; cs!=w07+4; cs+=1) *rr++ = *cs;
  /* #11: @8 = (@6*@8) */
  w08  = (w06*w08);
  /* #12: @9 = @7[0] */
  for (rr=(&w09), cs=w07+0; cs!=w07+1; cs+=1) *rr++ = *cs;
  /* #13: @10 = 0.621 */
  w10 = 6.2100000000000000e-01;
  /* #14: @11 = @7[2] */
  for (rr=(&w11), cs=w07+2; cs!=w07+3; cs+=1) *rr++ = *cs;
  /* #15: @10 = (@10*@11) */
  w10 *= w11;
  /* #16: @12 = (@9-@10) */
  w12  = (w09-w10);
  /* #17: @13 = @1[1] */
  w13 = wr01[1];
  /* #18: @14 = cos(@13) */
  w14 = cos( w13 );
  /* #19: @15 = (@12*@14) */
  w15  = (w12*w14);
  /* #20: @16 = @7[1] */
  for (rr=(&w16), cs=w07+1; cs!=w07+2; cs+=1) *rr++ = *cs;
  /* #21: @17 = 0.765 */
  w17 = 7.6500000000000001e-01;
  /* #22: @17 = (@17*@11) */
  w17 *= w11;
  /* #23: @11 = (@16+@17) */
  w11  = (w16+w17);
  /* #24: @13 = sin(@13) */
  w13 = sin( w13 );
  /* #25: @18 = (@11*@13) */
  w18  = (w11*w13);
  /* #26: @15 = (@15+@18) */
  w15 += w18;
  /* #27: @18 = fabs(@15) */
  w18 = casadi_fabs( w15 );
  /* #28: @19 = 0.001 */
  w19 = 1.0000000000000000e-03;
  /* #29: @18 = (@18<@19) */
  w18  = (w18<w19);
  /* #30: @20 = (@18?@19:0) */
  w20  = (w18?w19:0);
  /* #31: @18 = (!@18) */
  w18 = (! w18 );
  /* #32: @18 = (@18?@15:0) */
  w18  = (w18?w15:0);
  /* #33: @20 = (@20+@18) */
  w20 += w18;
  /* #34: @8 = (@8-@20) */
  w08 -= w20;
  /* #35: @8 = (@8/@20) */
  w08 /= w20;
  /* #36: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #37: @18 = 0.7 */
  w18 = 6.9999999999999996e-01;
  /* #38: @15 = atan(@8) */
  w15 = atan( w08 );
  /* #39: @15 = (@8-@15) */
  w15  = (w08-w15);
  /* #40: @15 = (@18*@15) */
  w15  = (w18*w15);
  /* #41: @8 = (@8-@15) */
  w08 -= w15;
  /* #42: @8 = atan(@8) */
  w08 = atan( w08 );
  /* #43: @8 = (@4*@8) */
  w08  = (w04*w08);
  /* #44: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #45: @8 = (@2*@8) */
  w08  = (w02*w08);
  /* #46: @15 = (@8*@14) */
  w15  = (w08*w14);
  /* #47: @21 = (@11*@14) */
  w21  = (w11*w14);
  /* #48: @22 = (@12*@13) */
  w22  = (w12*w13);
  /* #49: @21 = (@21-@22) */
  w21 -= w22;
  /* #50: @21 = atan2(@21,@20) */
  w21  = atan2(w21,w20);
  /* #51: @21 = (@5*@21) */
  w21  = (w05*w21);
  /* #52: @20 = atan(@21) */
  w20 = atan( w21 );
  /* #53: @20 = (@21-@20) */
  w20  = (w21-w20);
  /* #54: @20 = (@18*@20) */
  w20  = (w18*w20);
  /* #55: @21 = (@21-@20) */
  w21 -= w20;
  /* #56: @21 = atan(@21) */
  w21 = atan( w21 );
  /* #57: @21 = (@4*@21) */
  w21  = (w04*w21);
  /* #58: @21 = sin(@21) */
  w21 = sin( w21 );
  /* #59: @21 = (@2*@21) */
  w21  = (w02*w21);
  /* #60: @20 = (@21*@13) */
  w20  = (w21*w13);
  /* #61: @15 = (@15-@20) */
  w15 -= w20;
  /* #62: @15 = (@15/@2) */
  w15 /= w02;
  /* #63: @15 = sq(@15) */
  w15 = casadi_sq( w15 );
  /* #64: @8 = (@8*@13) */
  w08 *= w13;
  /* #65: @21 = (@21*@14) */
  w21 *= w14;
  /* #66: @8 = (@8+@21) */
  w08 += w21;
  /* #67: @8 = (@8/@2) */
  w08 /= w02;
  /* #68: @8 = sq(@8) */
  w08 = casadi_sq( w08 );
  /* #69: @15 = (@15+@8) */
  w15 += w08;
  /* #70: @8 = 1 */
  w08 = 1.;
  /* #71: @15 = (@15-@8) */
  w15 -= w08;
  /* #72: output[0][0] = @15 */
  if (res[0]) res[0][0] = w15;
  /* #73: @15 = @1[4] */
  w15 = wr01[4];
  /* #74: @15 = fmax(@15,@3) */
  w15  = casadi_fmax(w15,w03);
  /* #75: @15 = (@0*@15) */
  w15  = (w00*w15);
  /* #76: @2 = @7[4] */
  for (rr=(&w02), cs=w07+4; cs!=w07+5; cs+=1) *rr++ = *cs;
  /* #77: @2 = (@6*@2) */
  w02  = (w06*w02);
  /* #78: @9 = (@9+@10) */
  w09 += w10;
  /* #79: @10 = @1[2] */
  w10 = wr01[2];
  /* #80: @21 = cos(@10) */
  w21 = cos( w10 );
  /* #81: @14 = (@9*@21) */
  w14  = (w09*w21);
  /* #82: @10 = sin(@10) */
  w10 = sin( w10 );
  /* #83: @13 = (@11*@10) */
  w13  = (w11*w10);
  /* #84: @14 = (@14+@13) */
  w14 += w13;
  /* #85: @13 = fabs(@14) */
  w13 = casadi_fabs( w14 );
  /* #86: @13 = (@13<@19) */
  w13  = (w13<w19);
  /* #87: @20 = (@13?@19:0) */
  w20  = (w13?w19:0);
  /* #88: @13 = (!@13) */
  w13 = (! w13 );
  /* #89: @13 = (@13?@14:0) */
  w13  = (w13?w14:0);
  /* #90: @20 = (@20+@13) */
  w20 += w13;
  /* #91: @2 = (@2-@20) */
  w02 -= w20;
  /* #92: @2 = (@2/@20) */
  w02 /= w20;
  /* #93: @2 = (@5*@2) */
  w02  = (w05*w02);
  /* #94: @13 = atan(@2) */
  w13 = atan( w02 );
  /* #95: @13 = (@2-@13) */
  w13  = (w02-w13);
  /* #96: @13 = (@18*@13) */
  w13  = (w18*w13);
  /* #97: @2 = (@2-@13) */
  w02 -= w13;
  /* #98: @2 = atan(@2) */
  w02 = atan( w02 );
  /* #99: @2 = (@4*@2) */
  w02  = (w04*w02);
  /* #100: @2 = sin(@2) */
  w02 = sin( w02 );
  /* #101: @2 = (@15*@2) */
  w02  = (w15*w02);
  /* #102: @13 = (@2*@21) */
  w13  = (w02*w21);
  /* #103: @11 = (@11*@21) */
  w11 *= w21;
  /* #104: @14 = (@9*@10) */
  w14  = (w09*w10);
  /* #105: @11 = (@11-@14) */
  w11 -= w14;
  /* #106: @11 = atan2(@11,@20) */
  w11  = atan2(w11,w20);
  /* #107: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #108: @20 = atan(@11) */
  w20 = atan( w11 );
  /* #109: @20 = (@11-@20) */
  w20  = (w11-w20);
  /* #110: @20 = (@18*@20) */
  w20  = (w18*w20);
  /* #111: @11 = (@11-@20) */
  w11 -= w20;
  /* #112: @11 = atan(@11) */
  w11 = atan( w11 );
  /* #113: @11 = (@4*@11) */
  w11  = (w04*w11);
  /* #114: @11 = sin(@11) */
  w11 = sin( w11 );
  /* #115: @11 = (@15*@11) */
  w11  = (w15*w11);
  /* #116: @20 = (@11*@10) */
  w20  = (w11*w10);
  /* #117: @13 = (@13-@20) */
  w13 -= w20;
  /* #118: @13 = (@13/@15) */
  w13 /= w15;
  /* #119: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #120: @2 = (@2*@10) */
  w02 *= w10;
  /* #121: @11 = (@11*@21) */
  w11 *= w21;
  /* #122: @2 = (@2+@11) */
  w02 += w11;
  /* #123: @2 = (@2/@15) */
  w02 /= w15;
  /* #124: @2 = sq(@2) */
  w02 = casadi_sq( w02 );
  /* #125: @13 = (@13+@2) */
  w13 += w02;
  /* #126: @13 = (@13-@8) */
  w13 -= w08;
  /* #127: output[0][1] = @13 */
  if (res[0]) res[0][1] = w13;
  /* #128: @13 = @1[5] */
  w13 = wr01[5];
  /* #129: @13 = fmax(@13,@3) */
  w13  = casadi_fmax(w13,w03);
  /* #130: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #131: @2 = @7[5] */
  for (rr=(&w02), cs=w07+5; cs!=w07+6; cs+=1) *rr++ = *cs;
  /* #132: @2 = (@6*@2) */
  w02  = (w06*w02);
  /* #133: @15 = fabs(@12) */
  w15 = casadi_fabs( w12 );
  /* #134: @15 = (@15<@19) */
  w15  = (w15<w19);
  /* #135: @11 = (@15?@19:0) */
  w11  = (w15?w19:0);
  /* #136: @15 = (!@15) */
  w15 = (! w15 );
  /* #137: @15 = (@15?@12:0) */
  w15  = (w15?w12:0);
  /* #138: @11 = (@11+@15) */
  w11 += w15;
  /* #139: @2 = (@2-@11) */
  w02 -= w11;
  /* #140: @2 = (@2/@11) */
  w02 /= w11;
  /* #141: @2 = (@5*@2) */
  w02  = (w05*w02);
  /* #142: @15 = atan(@2) */
  w15 = atan( w02 );
  /* #143: @15 = (@2-@15) */
  w15  = (w02-w15);
  /* #144: @15 = (@18*@15) */
  w15  = (w18*w15);
  /* #145: @2 = (@2-@15) */
  w02 -= w15;
  /* #146: @2 = atan(@2) */
  w02 = atan( w02 );
  /* #147: @2 = (@4*@2) */
  w02  = (w04*w02);
  /* #148: @2 = sin(@2) */
  w02 = sin( w02 );
  /* #149: @2 = (@13*@2) */
  w02  = (w13*w02);
  /* #150: @2 = (@2/@13) */
  w02 /= w13;
  /* #151: @2 = sq(@2) */
  w02 = casadi_sq( w02 );
  /* #152: @16 = (@16-@17) */
  w16 -= w17;
  /* #153: @11 = atan2(@16,@11) */
  w11  = atan2(w16,w11);
  /* #154: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #155: @17 = atan(@11) */
  w17 = atan( w11 );
  /* #156: @17 = (@11-@17) */
  w17  = (w11-w17);
  /* #157: @17 = (@18*@17) */
  w17  = (w18*w17);
  /* #158: @11 = (@11-@17) */
  w11 -= w17;
  /* #159: @11 = atan(@11) */
  w11 = atan( w11 );
  /* #160: @11 = (@4*@11) */
  w11  = (w04*w11);
  /* #161: @11 = sin(@11) */
  w11 = sin( w11 );
  /* #162: @11 = (@13*@11) */
  w11  = (w13*w11);
  /* #163: @11 = (@11/@13) */
  w11 /= w13;
  /* #164: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #165: @2 = (@2+@11) */
  w02 += w11;
  /* #166: @2 = (@2-@8) */
  w02 -= w08;
  /* #167: output[0][2] = @2 */
  if (res[0]) res[0][2] = w02;
  /* #168: @2 = @1[6] */
  w02 = wr01[6];
  /* #169: @2 = fmax(@2,@3) */
  w02  = casadi_fmax(w02,w03);
  /* #170: @0 = (@0*@2) */
  w00 *= w02;
  /* #171: @2 = @7[6] */
  for (rr=(&w02), cs=w07+6; cs!=w07+7; cs+=1) *rr++ = *cs;
  /* #172: @6 = (@6*@2) */
  w06 *= w02;
  /* #173: @2 = fabs(@9) */
  w02 = casadi_fabs( w09 );
  /* #174: @2 = (@2<@19) */
  w02  = (w02<w19);
  /* #175: @19 = (@2?@19:0) */
  w19  = (w02?w19:0);
  /* #176: @2 = (!@2) */
  w02 = (! w02 );
  /* #177: @2 = (@2?@9:0) */
  w02  = (w02?w09:0);
  /* #178: @19 = (@19+@2) */
  w19 += w02;
  /* #179: @6 = (@6-@19) */
  w06 -= w19;
  /* #180: @6 = (@6/@19) */
  w06 /= w19;
  /* #181: @6 = (@5*@6) */
  w06  = (w05*w06);
  /* #182: @2 = atan(@6) */
  w02 = atan( w06 );
  /* #183: @2 = (@6-@2) */
  w02  = (w06-w02);
  /* #184: @2 = (@18*@2) */
  w02  = (w18*w02);
  /* #185: @6 = (@6-@2) */
  w06 -= w02;
  /* #186: @6 = atan(@6) */
  w06 = atan( w06 );
  /* #187: @6 = (@4*@6) */
  w06  = (w04*w06);
  /* #188: @6 = sin(@6) */
  w06 = sin( w06 );
  /* #189: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #190: @6 = (@6/@0) */
  w06 /= w00;
  /* #191: @6 = sq(@6) */
  w06 = casadi_sq( w06 );
  /* #192: @16 = atan2(@16,@19) */
  w16  = atan2(w16,w19);
  /* #193: @5 = (@5*@16) */
  w05 *= w16;
  /* #194: @16 = atan(@5) */
  w16 = atan( w05 );
  /* #195: @16 = (@5-@16) */
  w16  = (w05-w16);
  /* #196: @18 = (@18*@16) */
  w18 *= w16;
  /* #197: @5 = (@5-@18) */
  w05 -= w18;
  /* #198: @5 = atan(@5) */
  w05 = atan( w05 );
  /* #199: @4 = (@4*@5) */
  w04 *= w05;
  /* #200: @4 = sin(@4) */
  w04 = sin( w04 );
  /* #201: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #202: @4 = (@4/@0) */
  w04 /= w00;
  /* #203: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #204: @6 = (@6+@4) */
  w06 += w04;
  /* #205: @6 = (@6-@8) */
  w06 -= w08;
  /* #206: output[0][3] = @6 */
  if (res[0]) res[0][3] = w06;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 36;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 36*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
