/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {15, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_fun_jac:(i0[11],i1[4],i2[],i3[8])->(o0,o1[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, *w01=w+1, w02, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, *w13=w+30, w14, w15, w16, w17, w18, w19;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 10000 */
  w00 = 10000.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = @1[1] */
  w05 = wr01[1];
  /* #9: @6 = 0.25 */
  w06 = 2.5000000000000000e-01;
  /* #10: @7 = @1[0] */
  w07 = wr01[0];
  /* #11: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #12: @6 = (@6+@8) */
  w06 += w08;
  /* #13: @6 = sqrt(@6) */
  w06 = sqrt( w06 );
  /* #14: @5 = (@5/@6) */
  w05 /= w06;
  /* #15: @8 = sq(@5) */
  w08 = casadi_sq( w05 );
  /* #16: @4 = (@4+@8) */
  w04 += w08;
  /* #17: @8 = 400000 */
  w08 = 400000.;
  /* #18: @9 = 4 */
  w09 = 4.;
  /* #19: @10 = pow(@5,@9) */
  w10  = pow(w05,w09);
  /* #20: @10 = (@8*@10) */
  w10  = (w08*w10);
  /* #21: @4 = (@4+@10) */
  w04 += w10;
  /* #22: @10 = 10 */
  w10 = 10.;
  /* #23: @11 = @1[7] */
  w11 = wr01[7];
  /* #24: @12 = @1[8] */
  w12 = wr01[8];
  /* #25: @11 = (@11+@12) */
  w11 += w12;
  /* #26: @12 = @1[9] */
  w12 = wr01[9];
  /* #27: @11 = (@11+@12) */
  w11 += w12;
  /* #28: @12 = @1[10] */
  w12 = wr01[10];
  /* #29: @11 = (@11+@12) */
  w11 += w12;
  /* #30: @12 = @3[7] */
  w12 = wr03[7];
  /* #31: @11 = (@11-@12) */
  w11 -= w12;
  /* #32: @12 = sq(@11) */
  w12 = casadi_sq( w11 );
  /* #33: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #34: @4 = (@4+@12) */
  w04 += w12;
  /* #35: @12 = 0.03 */
  w12 = 2.9999999999999999e-02;
  /* #36: @13 = input[1][0] */
  casadi_copy(arg[1], 4, w13);
  /* #37: @14 = @13[0] */
  for (rr=(&w14), cs=w13+0; cs!=w13+1; cs+=1) *rr++ = *cs;
  /* #38: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #39: @16 = @13[1] */
  for (rr=(&w16), cs=w13+1; cs!=w13+2; cs+=1) *rr++ = *cs;
  /* #40: @17 = sq(@16) */
  w17 = casadi_sq( w16 );
  /* #41: @15 = (@15+@17) */
  w15 += w17;
  /* #42: @17 = @13[2] */
  for (rr=(&w17), cs=w13+2; cs!=w13+3; cs+=1) *rr++ = *cs;
  /* #43: @18 = sq(@17) */
  w18 = casadi_sq( w17 );
  /* #44: @15 = (@15+@18) */
  w15 += w18;
  /* #45: @18 = @13[3] */
  for (rr=(&w18), cs=w13+3; cs!=w13+4; cs+=1) *rr++ = *cs;
  /* #46: @19 = sq(@18) */
  w19 = casadi_sq( w18 );
  /* #47: @15 = (@15+@19) */
  w15 += w19;
  /* #48: @15 = (@12*@15) */
  w15  = (w12*w15);
  /* #49: @4 = (@4+@15) */
  w04 += w15;
  /* #50: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #51: @13 = zeros(4x1) */
  casadi_clear(w13, 4);
  /* #52: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #53: @18 = (@12*@18) */
  w18  = (w12*w18);
  /* #54: (@13[3] += @18) */
  for (rr=w13+3, cs=(&w18); rr!=w13+4; rr+=1) *rr += *cs++;
  /* #55: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #56: @17 = (@12*@17) */
  w17  = (w12*w17);
  /* #57: (@13[2] += @17) */
  for (rr=w13+2, cs=(&w17); rr!=w13+3; rr+=1) *rr += *cs++;
  /* #58: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #59: @16 = (@12*@16) */
  w16  = (w12*w16);
  /* #60: (@13[1] += @16) */
  for (rr=w13+1, cs=(&w16); rr!=w13+2; rr+=1) *rr += *cs++;
  /* #61: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #62: @12 = (@12*@14) */
  w12 *= w14;
  /* #63: (@13[0] += @12) */
  for (rr=w13+0, cs=(&w12); rr!=w13+1; rr+=1) *rr += *cs++;
  /* #64: output[1][0] = @13 */
  casadi_copy(w13, 4, res[1]);
  /* #65: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #66: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #67: @10 = (@10*@11) */
  w10 *= w11;
  /* #68: (@1[10] += @10) */
  for (rr=w01+10, cs=(&w10); rr!=w01+11; rr+=1) *rr += *cs++;
  /* #69: (@1[9] += @10) */
  for (rr=w01+9, cs=(&w10); rr!=w01+10; rr+=1) *rr += *cs++;
  /* #70: (@1[8] += @10) */
  for (rr=w01+8, cs=(&w10); rr!=w01+9; rr+=1) *rr += *cs++;
  /* #71: (@1[7] += @10) */
  for (rr=w01+7, cs=(&w10); rr!=w01+8; rr+=1) *rr += *cs++;
  /* #72: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #73: @10 = (@5/@6) */
  w10  = (w05/w06);
  /* #74: @11 = 3 */
  w11 = 3.;
  /* #75: @11 = pow(@5,@11) */
  w11  = pow(w05,w11);
  /* #76: @9 = (@9*@11) */
  w09 *= w11;
  /* #77: @8 = (@8*@9) */
  w08 *= w09;
  /* #78: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #79: @8 = (@8+@5) */
  w08 += w05;
  /* #80: @10 = (@10*@8) */
  w10 *= w08;
  /* #81: @5 = (2.*@6) */
  w05 = (2.* w06 );
  /* #82: @10 = (@10/@5) */
  w10 /= w05;
  /* #83: @7 = (@7*@10) */
  w07 *= w10;
  /* #84: @7 = (-@7) */
  w07 = (- w07 );
  /* #85: (@1[0] += @7) */
  for (rr=w01+0, cs=(&w07); rr!=w01+1; rr+=1) *rr += *cs++;
  /* #86: @8 = (@8/@6) */
  w08 /= w06;
  /* #87: (@1[1] += @8) */
  for (rr=w01+1, cs=(&w08); rr!=w01+2; rr+=1) *rr += *cs++;
  /* #88: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #89: @0 = (@0*@2) */
  w00 *= w02;
  /* #90: (@1[2] += @0) */
  for (rr=w01+2, cs=(&w00); rr!=w01+3; rr+=1) *rr += *cs++;
  /* #91: output[1][1] = @1 */
  if (res[1]) casadi_copy(w01, 11, res[1]+4);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 40;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 40*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
