/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[7] = {11, 1, 0, 3, 0, 1, 2};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_e_fun_jac:(i0[11],i1[8])->(o0,o1[11x1,3nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, *w01=w+1, w02, w04, w05, w06, w07, w08, w09, *w10=w+27;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 18 */
  w00 = 18.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[1][0] */
  wr03 = arg[1] ? arg[1] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = 50000 */
  w05 = 50000.;
  /* #9: @6 = @1[1] */
  w06 = wr01[1];
  /* #10: @7 = 0.001 */
  w07 = 1.0000000000000000e-03;
  /* #11: @8 = @1[0] */
  w08 = wr01[0];
  /* #12: @7 = (@7+@8) */
  w07 += w08;
  /* #13: @8 = atan2(@6,@7) */
  w08  = atan2(w06,w07);
  /* #14: @9 = sq(@8) */
  w09 = casadi_sq( w08 );
  /* #15: @9 = (@5*@9) */
  w09  = (w05*w09);
  /* #16: @4 = (@4+@9) */
  w04 += w09;
  /* #17: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #18: @10 = zeros(11x1,3nz) */
  casadi_clear(w10, 3);
  /* #19: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #20: @4 = sq(@6) */
  w04 = casadi_sq( w06 );
  /* #21: @9 = sq(@7) */
  w09 = casadi_sq( w07 );
  /* #22: @4 = (@4+@9) */
  w04 += w09;
  /* #23: @6 = (@6/@4) */
  w06 /= w04;
  /* #24: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #25: @5 = (@5*@8) */
  w05 *= w08;
  /* #26: @6 = (@6*@5) */
  w06 *= w05;
  /* #27: @6 = (-@6) */
  w06 = (- w06 );
  /* #28: (@1[0] += @6) */
  for (rr=w01+0, cs=(&w06); rr!=w01+1; rr+=1) *rr += *cs++;
  /* #29: @7 = (@7/@4) */
  w07 /= w04;
  /* #30: @7 = (@7*@5) */
  w07 *= w05;
  /* #31: (@1[1] += @7) */
  for (rr=w01+1, cs=(&w07); rr!=w01+2; rr+=1) *rr += *cs++;
  /* #32: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #33: @0 = (@0*@2) */
  w00 *= w02;
  /* #34: (@1[2] += @0) */
  for (rr=w01+2, cs=(&w00); rr!=w01+3; rr+=1) *rr += *cs++;
  /* #35: @0 = @1[0] */
  for (rr=(&w00), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #36: (@10[0] = @0) */
  for (rr=w10+0, cs=(&w00); rr!=w10+1; rr+=1) *rr = *cs++;
  /* #37: @0 = @1[1] */
  for (rr=(&w00), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #38: (@10[1] = @0) */
  for (rr=w10+1, cs=(&w00); rr!=w10+2; rr+=1) *rr = *cs++;
  /* #39: @0 = @1[2] */
  for (rr=(&w00), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #40: (@10[2] = @0) */
  for (rr=w10+2, cs=(&w00); rr!=w10+3; rr+=1) *rr = *cs++;
  /* #41: output[1][0] = @10 */
  casadi_copy(w10, 3, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_e_fun_jac_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 30;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 30*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
