/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = 
  {0, 1, 2, 3, 4, 5, 6, 11,
  12, 13, 14};
static const casadi_int casadi_s1[11] = 
  {0, 1, 2, 3, 4, 5, 8, 9,
  10, 11, 12};
static const casadi_int casadi_s2[11] = 
  {0, 1, 2, 3, 4, 6, 8, 9,
  13, 17, 21};
static const casadi_int casadi_s3[6] = {0, 1, 7, 8, 9, 10};
static const casadi_int casadi_s4[6] = {6, 7, 13, 14, 15, 16};
static const casadi_int casadi_s5[6] = {5, 7, 10, 14, 18, 22};
static const casadi_int casadi_s6[43] = 
  {15, 15, 0, 1, 2, 3, 4, 6,
  8, 9, 9, 9, 9, 9, 13, 17,
  21, 25, 0, 1, 2, 3, 4, 5,
  4, 5, 6, 11, 12, 13, 14, 11,
  12, 13, 14, 11, 12, 13, 14, 11,
  12, 13, 14};
static const casadi_int casadi_s7[3] = {11, 1, 1};
static const casadi_int casadi_s8[3] = {4, 1, 1};
static const casadi_int casadi_s9[3] = {0, 0, 1};
static const casadi_int casadi_s10[3] = {8, 1, 1};
static const casadi_int casadi_s11[3] = {1, 1, 1};
static const casadi_int casadi_s12[3] = {15, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_0_fun_jac_hess:(i0[11],i1[4],i2[],i3[8])->(o0,o1[15],o2[15x15,25nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, *w01=w+1, w02, w04, w05, w06, w07, w08, w09, w10, *w11=w+28;
  casadi_real w12, w13, w14, w15, w16, w17, *w18=w+38, *w19=w+42, *w20=w+53, *w21=w+78, *w22=w+85, *w23=w+100;
  casadi_real *w24=w+102, *w25=w+104, *w26=w+110;
  const casadi_int *cii;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 10000 */
  w00 = 10000.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = @1[1] */
  w05 = wr01[1];
  /* #9: @6 = 0.25 */
  w06 = 2.5000000000000000e-01;
  /* #10: @7 = @1[0] */
  w07 = wr01[0];
  /* #11: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #12: @6 = (@6+@8) */
  w06 += w08;
  /* #13: @6 = sqrt(@6) */
  w06 = sqrt( w06 );
  /* #14: @5 = (@5/@6) */
  w05 /= w06;
  /* #15: @8 = sq(@5) */
  w08 = casadi_sq( w05 );
  /* #16: @4 = (@4+@8) */
  w04 += w08;
  /* #17: @8 = 10 */
  w08 = 10.;
  /* #18: @9 = @1[7] */
  w09 = wr01[7];
  /* #19: @10 = @1[8] */
  w10 = wr01[8];
  /* #20: @9 = (@9+@10) */
  w09 += w10;
  /* #21: @10 = @1[9] */
  w10 = wr01[9];
  /* #22: @9 = (@9+@10) */
  w09 += w10;
  /* #23: @10 = @1[10] */
  w10 = wr01[10];
  /* #24: @9 = (@9+@10) */
  w09 += w10;
  /* #25: @10 = @3[7] */
  w10 = wr03[7];
  /* #26: @9 = (@9-@10) */
  w09 -= w10;
  /* #27: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #28: @10 = (@8*@10) */
  w10  = (w08*w10);
  /* #29: @4 = (@4+@10) */
  w04 += w10;
  /* #30: @10 = 0.03 */
  w10 = 2.9999999999999999e-02;
  /* #31: @11 = input[1][0] */
  casadi_copy(arg[1], 4, w11);
  /* #32: @12 = @11[0] */
  for (rr=(&w12), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #33: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #34: @14 = @11[1] */
  for (rr=(&w14), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #35: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #36: @13 = (@13+@15) */
  w13 += w15;
  /* #37: @15 = @11[2] */
  for (rr=(&w15), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #38: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #39: @13 = (@13+@16) */
  w13 += w16;
  /* #40: @16 = @11[3] */
  for (rr=(&w16), cs=w11+3; cs!=w11+4; cs+=1) *rr++ = *cs;
  /* #41: @17 = sq(@16) */
  w17 = casadi_sq( w16 );
  /* #42: @13 = (@13+@17) */
  w13 += w17;
  /* #43: @13 = (@10*@13) */
  w13  = (w10*w13);
  /* #44: @4 = (@4+@13) */
  w04 += w13;
  /* #45: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #46: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #47: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #48: @16 = (@10*@16) */
  w16  = (w10*w16);
  /* #49: @18 = @11; (@18[3] += @16) */
  casadi_copy(w11, 4, w18);
  for (rr=w18+3, cs=(&w16); rr!=w18+4; rr+=1) *rr += *cs++;
  /* #50: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #51: @15 = (@10*@15) */
  w15  = (w10*w15);
  /* #52: (@18[2] += @15) */
  for (rr=w18+2, cs=(&w15); rr!=w18+3; rr+=1) *rr += *cs++;
  /* #53: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #54: @14 = (@10*@14) */
  w14  = (w10*w14);
  /* #55: (@18[1] += @14) */
  for (rr=w18+1, cs=(&w14); rr!=w18+2; rr+=1) *rr += *cs++;
  /* #56: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #57: @12 = (@10*@12) */
  w12  = (w10*w12);
  /* #58: (@18[0] += @12) */
  for (rr=w18+0, cs=(&w12); rr!=w18+1; rr+=1) *rr += *cs++;
  /* #59: output[1][0] = @18 */
  casadi_copy(w18, 4, res[1]);
  /* #60: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #61: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #62: @9 = (@8*@9) */
  w09  = (w08*w09);
  /* #63: @19 = @1; (@19[10] += @9) */
  casadi_copy(w01, 11, w19);
  for (rr=w19+10, cs=(&w09); rr!=w19+11; rr+=1) *rr += *cs++;
  /* #64: (@19[9] += @9) */
  for (rr=w19+9, cs=(&w09); rr!=w19+10; rr+=1) *rr += *cs++;
  /* #65: (@19[8] += @9) */
  for (rr=w19+8, cs=(&w09); rr!=w19+9; rr+=1) *rr += *cs++;
  /* #66: (@19[7] += @9) */
  for (rr=w19+7, cs=(&w09); rr!=w19+8; rr+=1) *rr += *cs++;
  /* #67: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #68: @9 = (@5/@6) */
  w09  = (w05/w06);
  /* #69: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #70: @12 = (@9*@5) */
  w12  = (w09*w05);
  /* #71: @14 = (2.*@6) */
  w14 = (2.* w06 );
  /* #72: @12 = (@12/@14) */
  w12 /= w14;
  /* #73: @15 = (@7*@12) */
  w15  = (w07*w12);
  /* #74: @15 = (-@15) */
  w15 = (- w15 );
  /* #75: (@19[0] += @15) */
  for (rr=w19+0, cs=(&w15); rr!=w19+1; rr+=1) *rr += *cs++;
  /* #76: @15 = (@5/@6) */
  w15  = (w05/w06);
  /* #77: (@19[1] += @15) */
  for (rr=w19+1, cs=(&w15); rr!=w19+2; rr+=1) *rr += *cs++;
  /* #78: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #79: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #80: (@19[2] += @2) */
  for (rr=w19+2, cs=(&w02); rr!=w19+3; rr+=1) *rr += *cs++;
  /* #81: output[1][1] = @19 */
  if (res[1]) casadi_copy(w19, 11, res[1]+4);
  /* #82: @20 = zeros(15x15,25nz) */
  casadi_clear(w20, 25);
  /* #83: @19 = ones(15x1,11nz) */
  casadi_fill(w19, 11, 1.);
  /* #84: {@18, @21} = vertsplit(@19) */
  casadi_copy(w19, 4, w18);
  casadi_copy(w19+4, 7, w21);
  /* #85: @2 = @18[3] */
  for (rr=(&w02), cs=w18+3; cs!=w18+4; cs+=1) *rr++ = *cs;
  /* #86: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #87: @2 = (@10*@2) */
  w02  = (w10*w02);
  /* #88: (@11[3] += @2) */
  for (rr=w11+3, cs=(&w02); rr!=w11+4; rr+=1) *rr += *cs++;
  /* #89: @2 = @18[2] */
  for (rr=(&w02), cs=w18+2; cs!=w18+3; cs+=1) *rr++ = *cs;
  /* #90: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #91: @2 = (@10*@2) */
  w02  = (w10*w02);
  /* #92: (@11[2] += @2) */
  for (rr=w11+2, cs=(&w02); rr!=w11+3; rr+=1) *rr += *cs++;
  /* #93: @2 = @18[1] */
  for (rr=(&w02), cs=w18+1; cs!=w18+2; cs+=1) *rr++ = *cs;
  /* #94: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #95: @2 = (@10*@2) */
  w02  = (w10*w02);
  /* #96: (@11[1] += @2) */
  for (rr=w11+1, cs=(&w02); rr!=w11+2; rr+=1) *rr += *cs++;
  /* #97: @2 = @18[0] */
  for (rr=(&w02), cs=w18+0; cs!=w18+1; cs+=1) *rr++ = *cs;
  /* #98: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #99: @10 = (@10*@2) */
  w10 *= w02;
  /* #100: (@11[0] += @10) */
  for (rr=w11+0, cs=(&w10); rr!=w11+1; rr+=1) *rr += *cs++;
  /* #101: @10 = @21[6] */
  for (rr=(&w10), cs=w21+6; cs!=w21+7; cs+=1) *rr++ = *cs;
  /* #102: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #103: @10 = (@8*@10) */
  w10  = (w08*w10);
  /* #104: @19 = @1; (@19[10] += @10) */
  casadi_copy(w01, 11, w19);
  for (rr=w19+10, cs=(&w10); rr!=w19+11; rr+=1) *rr += *cs++;
  /* #105: (@19[9] += @10) */
  for (rr=w19+9, cs=(&w10); rr!=w19+10; rr+=1) *rr += *cs++;
  /* #106: (@19[8] += @10) */
  for (rr=w19+8, cs=(&w10); rr!=w19+9; rr+=1) *rr += *cs++;
  /* #107: (@19[7] += @10) */
  for (rr=w19+7, cs=(&w10); rr!=w19+8; rr+=1) *rr += *cs++;
  /* #108: @10 = @21[0] */
  for (rr=(&w10), cs=w21+0; cs!=w21+1; cs+=1) *rr++ = *cs;
  /* #109: @2 = (2.*@10) */
  w02 = (2.* w10 );
  /* #110: @2 = (@12*@2) */
  w02  = (w12*w02);
  /* #111: @16 = (@9/@6) */
  w16  = (w09/w06);
  /* #112: @10 = (@7*@10) */
  w10  = (w07*w10);
  /* #113: @10 = (@10/@14) */
  w10 /= w14;
  /* #114: @16 = (@16*@10) */
  w16 *= w10;
  /* #115: @16 = (-@16) */
  w16 = (- w16 );
  /* #116: @4 = (@9*@10) */
  w04  = (w09*w10);
  /* #117: @13 = (@4/@6) */
  w13  = (w04/w06);
  /* #118: @16 = (@16-@13) */
  w16 -= w13;
  /* #119: @16 = (@5*@16) */
  w16  = (w05*w16);
  /* #120: @4 = (-@4) */
  w04 = (- w04 );
  /* #121: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #122: @13 = (@9*@4) */
  w13  = (w09*w04);
  /* #123: @16 = (@16+@13) */
  w16 += w13;
  /* #124: @16 = (@16/@14) */
  w16 /= w14;
  /* #125: @12 = (@12/@14) */
  w12 /= w14;
  /* #126: @13 = (2.*@10) */
  w13 = (2.* w10 );
  /* #127: @12 = (@12*@13) */
  w12 *= w13;
  /* #128: @16 = (@16-@12) */
  w16 -= w12;
  /* #129: @16 = (@7*@16) */
  w16  = (w07*w16);
  /* #130: @2 = (@2+@16) */
  w02 += w16;
  /* #131: @2 = (-@2) */
  w02 = (- w02 );
  /* #132: (@19[0] += @2) */
  for (rr=w19+0, cs=(&w02); rr!=w19+1; rr+=1) *rr += *cs++;
  /* #133: @4 = (@4/@6) */
  w04 /= w06;
  /* #134: @15 = (@15/@6) */
  w15 /= w06;
  /* #135: @15 = (@15*@10) */
  w15 *= w10;
  /* #136: @4 = (@4-@15) */
  w04 -= w15;
  /* #137: (@19[1] += @4) */
  for (rr=w19+1, cs=(&w04); rr!=w19+2; rr+=1) *rr += *cs++;
  /* #138: @4 = @21[1] */
  for (rr=(&w04), cs=w21+1; cs!=w21+2; cs+=1) *rr++ = *cs;
  /* #139: @4 = (2.*@4) */
  w04 = (2.* w04 );
  /* #140: @0 = (@0*@4) */
  w00 *= w04;
  /* #141: (@19[2] += @0) */
  for (rr=w19+2, cs=(&w00); rr!=w19+3; rr+=1) *rr += *cs++;
  /* #142: @22 = vertcat(@11, @19) */
  rr=w22;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<11; ++i) *rr++ = *cs++;
  /* #143: @19 = @22[0, 1, 2, 3, 4, 5, 6, 11, 12, 13, 14] */
  for (cii=casadi_s0, rr=w19, cs=w22; cii!=casadi_s0+11; ++cii) *rr++ = cs[*cii];
  /* #144: (@20[0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12] = @19) */
  for (cii=casadi_s1, rr=w20, cs=w19; cii!=casadi_s1+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #145: (@20[0, 1, 2, 3, 4, 6, 8, 9, 13, 17, 21] = @19) */
  for (cii=casadi_s2, rr=w20, cs=w19; cii!=casadi_s2+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #146: @23 = ones(15x1,2nz) */
  casadi_fill(w23, 2, 1.);
  /* #147: {NULL, @24} = vertsplit(@23) */
  casadi_copy(w23, 2, w24);
  /* #148: @0 = @24[1] */
  for (rr=(&w00), cs=w24+1; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #149: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #150: @0 = (@8*@0) */
  w00  = (w08*w00);
  /* #151: @19 = @1; (@19[10] += @0) */
  casadi_copy(w01, 11, w19);
  for (rr=w19+10, cs=(&w00); rr!=w19+11; rr+=1) *rr += *cs++;
  /* #152: (@19[9] += @0) */
  for (rr=w19+9, cs=(&w00); rr!=w19+10; rr+=1) *rr += *cs++;
  /* #153: (@19[8] += @0) */
  for (rr=w19+8, cs=(&w00); rr!=w19+9; rr+=1) *rr += *cs++;
  /* #154: (@19[7] += @0) */
  for (rr=w19+7, cs=(&w00); rr!=w19+8; rr+=1) *rr += *cs++;
  /* #155: @0 = @24[0] */
  for (rr=(&w00), cs=w24+0; cs!=w24+1; cs+=1) *rr++ = *cs;
  /* #156: @0 = (@0/@6) */
  w00 /= w06;
  /* #157: @4 = (@0/@6) */
  w04  = (w00/w06);
  /* #158: @5 = (@5*@4) */
  w05 *= w04;
  /* #159: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #160: @9 = (@9*@0) */
  w09 *= w00;
  /* #161: @5 = (@5+@9) */
  w05 += w09;
  /* #162: @5 = (@5/@14) */
  w05 /= w14;
  /* #163: @7 = (@7*@5) */
  w07 *= w05;
  /* #164: @7 = (-@7) */
  w07 = (- w07 );
  /* #165: (@19[0] += @7) */
  for (rr=w19+0, cs=(&w07); rr!=w19+1; rr+=1) *rr += *cs++;
  /* #166: @0 = (@0/@6) */
  w00 /= w06;
  /* #167: (@19[1] += @0) */
  for (rr=w19+1, cs=(&w00); rr!=w19+2; rr+=1) *rr += *cs++;
  /* #168: @25 = @19[0, 1, 7, 8, 9, 10] */
  for (cii=casadi_s3, rr=w25, cs=w19; cii!=casadi_s3+6; ++cii) *rr++ = cs[*cii];
  /* #169: (@20[6, 7, 13, 14, 15, 16] = @25) */
  for (cii=casadi_s4, rr=w20, cs=w25; cii!=casadi_s4+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #170: (@20[5, 7, 10, 14, 18, 22] = @25) */
  for (cii=casadi_s5, rr=w20, cs=w25; cii!=casadi_s5+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #171: @0 = ones(15x1,1nz) */
  w00 = 1.;
  /* #172: {NULL, @6} = vertsplit(@0) */
  w06 = w00;
  /* #173: @0 = @6[0] */
  for (rr=(&w00), cs=(&w06)+0; cs!=(&w06)+1; cs+=1) *rr++ = *cs;
  /* #174: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #175: @0 = (@8*@0) */
  w00  = (w08*w00);
  /* #176: @19 = @1; (@19[10] += @0) */
  casadi_copy(w01, 11, w19);
  for (rr=w19+10, cs=(&w00); rr!=w19+11; rr+=1) *rr += *cs++;
  /* #177: (@19[9] += @0) */
  for (rr=w19+9, cs=(&w00); rr!=w19+10; rr+=1) *rr += *cs++;
  /* #178: (@19[8] += @0) */
  for (rr=w19+8, cs=(&w00); rr!=w19+9; rr+=1) *rr += *cs++;
  /* #179: (@19[7] += @0) */
  for (rr=w19+7, cs=(&w00); rr!=w19+8; rr+=1) *rr += *cs++;
  /* #180: @11 = @19[7:11] */
  for (rr=w11, cs=w19+7; cs!=w19+11; cs+=1) *rr++ = *cs;
  /* #181: (@20[17:21] = @11) */
  for (rr=w20+17, cs=w11; rr!=w20+21; rr+=1) *rr = *cs++;
  /* #182: (@20[11:27:4] = @11) */
  for (rr=w20+11, cs=w11; rr!=w20+27; rr+=4) *rr = *cs++;
  /* #183: @0 = ones(15x1,1nz) */
  w00 = 1.;
  /* #184: {NULL, @6} = vertsplit(@0) */
  w06 = w00;
  /* #185: @0 = @6[0] */
  for (rr=(&w00), cs=(&w06)+0; cs!=(&w06)+1; cs+=1) *rr++ = *cs;
  /* #186: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #187: @8 = (@8*@0) */
  w08 *= w00;
  /* #188: (@1[10] += @8) */
  for (rr=w01+10, cs=(&w08); rr!=w01+11; rr+=1) *rr += *cs++;
  /* #189: (@1[9] += @8) */
  for (rr=w01+9, cs=(&w08); rr!=w01+10; rr+=1) *rr += *cs++;
  /* #190: (@1[8] += @8) */
  for (rr=w01+8, cs=(&w08); rr!=w01+9; rr+=1) *rr += *cs++;
  /* #191: (@1[7] += @8) */
  for (rr=w01+7, cs=(&w08); rr!=w01+8; rr+=1) *rr += *cs++;
  /* #192: @11 = @1[7:11] */
  for (rr=w11, cs=w01+7; cs!=w01+11; cs+=1) *rr++ = *cs;
  /* #193: (@20[21:25] = @11) */
  for (rr=w20+21, cs=w11; rr!=w20+25; rr+=1) *rr = *cs++;
  /* #194: (@20[12:28:4] = @11) */
  for (rr=w20+12, cs=w11; rr!=w20+28; rr+=4) *rr = *cs++;
  /* #195: @26 = @20' */
  casadi_trans(w20,casadi_s6, w26, casadi_s6, iw);
  /* #196: output[2][0] = @26 */
  casadi_copy(w26, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    case 3: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s12;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 16;
  if (sz_w) *sz_w = 135;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 16*sizeof(casadi_int);
  if (sz_w) *sz_w = 135*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
