/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = 
  {0, 1, 2, 3, 4, 5, 6, 11,
  12, 13, 14};
static const casadi_int casadi_s1[11] = 
  {0, 1, 2, 3, 4, 5, 8, 9,
  10, 11, 12};
static const casadi_int casadi_s2[11] = 
  {0, 1, 2, 3, 4, 6, 8, 9,
  13, 17, 21};
static const casadi_int casadi_s3[6] = {0, 1, 7, 8, 9, 10};
static const casadi_int casadi_s4[6] = {6, 7, 13, 14, 15, 16};
static const casadi_int casadi_s5[6] = {5, 7, 10, 14, 18, 22};
static const casadi_int casadi_s6[43] = 
  {15, 15, 0, 1, 2, 3, 4, 6,
  8, 9, 9, 9, 9, 9, 13, 17,
  21, 25, 0, 1, 2, 3, 4, 5,
  4, 5, 6, 11, 12, 13, 14, 11,
  12, 13, 14, 11, 12, 13, 14, 11,
  12, 13, 14};
static const casadi_int casadi_s7[3] = {11, 1, 1};
static const casadi_int casadi_s8[3] = {4, 1, 1};
static const casadi_int casadi_s9[3] = {0, 0, 1};
static const casadi_int casadi_s10[3] = {8, 1, 1};
static const casadi_int casadi_s11[3] = {1, 1, 1};
static const casadi_int casadi_s12[3] = {15, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_fun_jac_hess:(i0[11],i1[4],i2[],i3[8])->(o0,o1[15],o2[15x15,25nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, *w01=w+1, w02, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, *w16=w+33, w17, w18, w19, w20, w21, w22, *w23=w+43;
  casadi_real *w24=w+47, *w25=w+58, *w26=w+83, *w27=w+90, *w28=w+105, *w29=w+107, *w30=w+109, *w31=w+115;
  const casadi_int *cii;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 100 */
  w00 = 100.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = 0.1 */
  w05 = 1.0000000000000001e-01;
  /* #9: @6 = @1[1] */
  w06 = wr01[1];
  /* #10: @7 = 0.001 */
  w07 = 1.0000000000000000e-03;
  /* #11: @8 = @1[0] */
  w08 = wr01[0];
  /* #12: @7 = (@7+@8) */
  w07 += w08;
  /* #13: @8 = atan2(@6,@7) */
  w08  = atan2(w06,w07);
  /* #14: @9 = sq(@8) */
  w09 = casadi_sq( w08 );
  /* #15: @9 = (@5*@9) */
  w09  = (w05*w09);
  /* #16: @4 = (@4+@9) */
  w04 += w09;
  /* #17: @9 = @1[7] */
  w09 = wr01[7];
  /* #18: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #19: @11 = @1[8] */
  w11 = wr01[8];
  /* #20: @12 = sq(@11) */
  w12 = casadi_sq( w11 );
  /* #21: @10 = (@10+@12) */
  w10 += w12;
  /* #22: @12 = @1[9] */
  w12 = wr01[9];
  /* #23: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #24: @10 = (@10+@13) */
  w10 += w13;
  /* #25: @13 = @1[10] */
  w13 = wr01[10];
  /* #26: @14 = sq(@13) */
  w14 = casadi_sq( w13 );
  /* #27: @10 = (@10+@14) */
  w10 += w14;
  /* #28: @10 = (@5*@10) */
  w10  = (w05*w10);
  /* #29: @4 = (@4+@10) */
  w04 += w10;
  /* #30: @10 = 10 */
  w10 = 10.;
  /* #31: @14 = (@9+@11) */
  w14  = (w09+w11);
  /* #32: @14 = (@14+@12) */
  w14 += w12;
  /* #33: @14 = (@14+@13) */
  w14 += w13;
  /* #34: @15 = @3[7] */
  w15 = wr03[7];
  /* #35: @14 = (@14-@15) */
  w14 -= w15;
  /* #36: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #37: @15 = (@10*@15) */
  w15  = (w10*w15);
  /* #38: @4 = (@4+@15) */
  w04 += w15;
  /* #39: @15 = 0.002 */
  w15 = 2.0000000000000000e-03;
  /* #40: @16 = input[1][0] */
  casadi_copy(arg[1], 4, w16);
  /* #41: @17 = @16[0] */
  for (rr=(&w17), cs=w16+0; cs!=w16+1; cs+=1) *rr++ = *cs;
  /* #42: @18 = sq(@17) */
  w18 = casadi_sq( w17 );
  /* #43: @19 = @16[1] */
  for (rr=(&w19), cs=w16+1; cs!=w16+2; cs+=1) *rr++ = *cs;
  /* #44: @20 = sq(@19) */
  w20 = casadi_sq( w19 );
  /* #45: @18 = (@18+@20) */
  w18 += w20;
  /* #46: @20 = @16[2] */
  for (rr=(&w20), cs=w16+2; cs!=w16+3; cs+=1) *rr++ = *cs;
  /* #47: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #48: @18 = (@18+@21) */
  w18 += w21;
  /* #49: @21 = @16[3] */
  for (rr=(&w21), cs=w16+3; cs!=w16+4; cs+=1) *rr++ = *cs;
  /* #50: @22 = sq(@21) */
  w22 = casadi_sq( w21 );
  /* #51: @18 = (@18+@22) */
  w18 += w22;
  /* #52: @18 = (@15*@18) */
  w18  = (w15*w18);
  /* #53: @4 = (@4+@18) */
  w04 += w18;
  /* #54: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #55: @16 = zeros(4x1) */
  casadi_clear(w16, 4);
  /* #56: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #57: @21 = (@15*@21) */
  w21  = (w15*w21);
  /* #58: @23 = @16; (@23[3] += @21) */
  casadi_copy(w16, 4, w23);
  for (rr=w23+3, cs=(&w21); rr!=w23+4; rr+=1) *rr += *cs++;
  /* #59: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #60: @20 = (@15*@20) */
  w20  = (w15*w20);
  /* #61: (@23[2] += @20) */
  for (rr=w23+2, cs=(&w20); rr!=w23+3; rr+=1) *rr += *cs++;
  /* #62: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #63: @19 = (@15*@19) */
  w19  = (w15*w19);
  /* #64: (@23[1] += @19) */
  for (rr=w23+1, cs=(&w19); rr!=w23+2; rr+=1) *rr += *cs++;
  /* #65: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #66: @17 = (@15*@17) */
  w17  = (w15*w17);
  /* #67: (@23[0] += @17) */
  for (rr=w23+0, cs=(&w17); rr!=w23+1; rr+=1) *rr += *cs++;
  /* #68: output[1][0] = @23 */
  casadi_copy(w23, 4, res[1]);
  /* #69: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #70: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #71: @14 = (@10*@14) */
  w14  = (w10*w14);
  /* #72: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #73: @13 = (@5*@13) */
  w13  = (w05*w13);
  /* #74: @13 = (@14+@13) */
  w13  = (w14+w13);
  /* #75: @24 = @1; (@24[10] += @13) */
  casadi_copy(w01, 11, w24);
  for (rr=w24+10, cs=(&w13); rr!=w24+11; rr+=1) *rr += *cs++;
  /* #76: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #77: @12 = (@5*@12) */
  w12  = (w05*w12);
  /* #78: @12 = (@14+@12) */
  w12  = (w14+w12);
  /* #79: (@24[9] += @12) */
  for (rr=w24+9, cs=(&w12); rr!=w24+10; rr+=1) *rr += *cs++;
  /* #80: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #81: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #82: @11 = (@14+@11) */
  w11  = (w14+w11);
  /* #83: (@24[8] += @11) */
  for (rr=w24+8, cs=(&w11); rr!=w24+9; rr+=1) *rr += *cs++;
  /* #84: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #85: @9 = (@5*@9) */
  w09  = (w05*w09);
  /* #86: @14 = (@14+@9) */
  w14 += w09;
  /* #87: (@24[7] += @14) */
  for (rr=w24+7, cs=(&w14); rr!=w24+8; rr+=1) *rr += *cs++;
  /* #88: @14 = sq(@6) */
  w14 = casadi_sq( w06 );
  /* #89: @9 = sq(@7) */
  w09 = casadi_sq( w07 );
  /* #90: @14 = (@14+@9) */
  w14 += w09;
  /* #91: @9 = (@6/@14) */
  w09  = (w06/w14);
  /* #92: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #93: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #94: @11 = (@9*@8) */
  w11  = (w09*w08);
  /* #95: @11 = (-@11) */
  w11 = (- w11 );
  /* #96: (@24[0] += @11) */
  for (rr=w24+0, cs=(&w11); rr!=w24+1; rr+=1) *rr += *cs++;
  /* #97: @11 = (@7/@14) */
  w11  = (w07/w14);
  /* #98: @12 = (@11*@8) */
  w12  = (w11*w08);
  /* #99: (@24[1] += @12) */
  for (rr=w24+1, cs=(&w12); rr!=w24+2; rr+=1) *rr += *cs++;
  /* #100: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #101: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #102: (@24[2] += @2) */
  for (rr=w24+2, cs=(&w02); rr!=w24+3; rr+=1) *rr += *cs++;
  /* #103: output[1][1] = @24 */
  if (res[1]) casadi_copy(w24, 11, res[1]+4);
  /* #104: @25 = zeros(15x15,25nz) */
  casadi_clear(w25, 25);
  /* #105: @24 = ones(15x1,11nz) */
  casadi_fill(w24, 11, 1.);
  /* #106: {@23, @26} = vertsplit(@24) */
  casadi_copy(w24, 4, w23);
  casadi_copy(w24+4, 7, w26);
  /* #107: @2 = @23[3] */
  for (rr=(&w02), cs=w23+3; cs!=w23+4; cs+=1) *rr++ = *cs;
  /* #108: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #109: @2 = (@15*@2) */
  w02  = (w15*w02);
  /* #110: (@16[3] += @2) */
  for (rr=w16+3, cs=(&w02); rr!=w16+4; rr+=1) *rr += *cs++;
  /* #111: @2 = @23[2] */
  for (rr=(&w02), cs=w23+2; cs!=w23+3; cs+=1) *rr++ = *cs;
  /* #112: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #113: @2 = (@15*@2) */
  w02  = (w15*w02);
  /* #114: (@16[2] += @2) */
  for (rr=w16+2, cs=(&w02); rr!=w16+3; rr+=1) *rr += *cs++;
  /* #115: @2 = @23[1] */
  for (rr=(&w02), cs=w23+1; cs!=w23+2; cs+=1) *rr++ = *cs;
  /* #116: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #117: @2 = (@15*@2) */
  w02  = (w15*w02);
  /* #118: (@16[1] += @2) */
  for (rr=w16+1, cs=(&w02); rr!=w16+2; rr+=1) *rr += *cs++;
  /* #119: @2 = @23[0] */
  for (rr=(&w02), cs=w23+0; cs!=w23+1; cs+=1) *rr++ = *cs;
  /* #120: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #121: @15 = (@15*@2) */
  w15 *= w02;
  /* #122: (@16[0] += @15) */
  for (rr=w16+0, cs=(&w15); rr!=w16+1; rr+=1) *rr += *cs++;
  /* #123: @15 = @26[6] */
  for (rr=(&w15), cs=w26+6; cs!=w26+7; cs+=1) *rr++ = *cs;
  /* #124: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #125: @2 = (@10*@15) */
  w02  = (w10*w15);
  /* #126: @24 = @1; (@24[10] += @2) */
  casadi_copy(w01, 11, w24);
  for (rr=w24+10, cs=(&w02); rr!=w24+11; rr+=1) *rr += *cs++;
  /* #127: (@24[9] += @2) */
  for (rr=w24+9, cs=(&w02); rr!=w24+10; rr+=1) *rr += *cs++;
  /* #128: (@24[8] += @2) */
  for (rr=w24+8, cs=(&w02); rr!=w24+9; rr+=1) *rr += *cs++;
  /* #129: @15 = (@5*@15) */
  w15  = (w05*w15);
  /* #130: @2 = (@2+@15) */
  w02 += w15;
  /* #131: (@24[7] += @2) */
  for (rr=w24+7, cs=(&w02); rr!=w24+8; rr+=1) *rr += *cs++;
  /* #132: @2 = @26[0] */
  for (rr=(&w02), cs=w26+0; cs!=w26+1; cs+=1) *rr++ = *cs;
  /* #133: @15 = (@9*@2) */
  w15  = (w09*w02);
  /* #134: @15 = (-@15) */
  w15 = (- w15 );
  /* #135: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #136: @15 = (@5*@15) */
  w15  = (w05*w15);
  /* #137: @12 = (@9*@15) */
  w12  = (w09*w15);
  /* #138: @13 = (@9/@14) */
  w13  = (w09/w14);
  /* #139: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #140: @7 = (@7*@2) */
  w07 *= w02;
  /* #141: @17 = (@13*@7) */
  w17  = (w13*w07);
  /* #142: @17 = (@8*@17) */
  w17  = (w08*w17);
  /* #143: @12 = (@12-@17) */
  w12 -= w17;
  /* #144: @12 = (-@12) */
  w12 = (- w12 );
  /* #145: (@24[0] += @12) */
  for (rr=w24+0, cs=(&w12); rr!=w24+1; rr+=1) *rr += *cs++;
  /* #146: @2 = (@2/@14) */
  w02 /= w14;
  /* #147: @12 = (@11/@14) */
  w12  = (w11/w14);
  /* #148: @7 = (@12*@7) */
  w07  = (w12*w07);
  /* #149: @2 = (@2-@7) */
  w02 -= w07;
  /* #150: @2 = (@8*@2) */
  w02  = (w08*w02);
  /* #151: @15 = (@11*@15) */
  w15  = (w11*w15);
  /* #152: @2 = (@2+@15) */
  w02 += w15;
  /* #153: (@24[1] += @2) */
  for (rr=w24+1, cs=(&w02); rr!=w24+2; rr+=1) *rr += *cs++;
  /* #154: @2 = @26[1] */
  for (rr=(&w02), cs=w26+1; cs!=w26+2; cs+=1) *rr++ = *cs;
  /* #155: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #156: @0 = (@0*@2) */
  w00 *= w02;
  /* #157: (@24[2] += @0) */
  for (rr=w24+2, cs=(&w00); rr!=w24+3; rr+=1) *rr += *cs++;
  /* #158: @27 = vertcat(@16, @24) */
  rr=w27;
  for (i=0, cs=w16; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<11; ++i) *rr++ = *cs++;
  /* #159: @24 = @27[0, 1, 2, 3, 4, 5, 6, 11, 12, 13, 14] */
  for (cii=casadi_s0, rr=w24, cs=w27; cii!=casadi_s0+11; ++cii) *rr++ = cs[*cii];
  /* #160: (@25[0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12] = @24) */
  for (cii=casadi_s1, rr=w25, cs=w24; cii!=casadi_s1+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #161: (@25[0, 1, 2, 3, 4, 6, 8, 9, 13, 17, 21] = @24) */
  for (cii=casadi_s2, rr=w25, cs=w24; cii!=casadi_s2+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #162: @28 = ones(15x1,2nz) */
  casadi_fill(w28, 2, 1.);
  /* #163: {NULL, @29} = vertsplit(@28) */
  casadi_copy(w28, 2, w29);
  /* #164: @0 = @29[1] */
  for (rr=(&w00), cs=w29+1; cs!=w29+2; cs+=1) *rr++ = *cs;
  /* #165: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #166: @2 = (@10*@0) */
  w02  = (w10*w00);
  /* #167: @24 = @1; (@24[10] += @2) */
  casadi_copy(w01, 11, w24);
  for (rr=w24+10, cs=(&w02); rr!=w24+11; rr+=1) *rr += *cs++;
  /* #168: (@24[9] += @2) */
  for (rr=w24+9, cs=(&w02); rr!=w24+10; rr+=1) *rr += *cs++;
  /* #169: @0 = (@5*@0) */
  w00  = (w05*w00);
  /* #170: @0 = (@2+@0) */
  w00  = (w02+w00);
  /* #171: (@24[8] += @0) */
  for (rr=w24+8, cs=(&w00); rr!=w24+9; rr+=1) *rr += *cs++;
  /* #172: (@24[7] += @2) */
  for (rr=w24+7, cs=(&w02); rr!=w24+8; rr+=1) *rr += *cs++;
  /* #173: @2 = @29[0] */
  for (rr=(&w02), cs=w29+0; cs!=w29+1; cs+=1) *rr++ = *cs;
  /* #174: @14 = (@2/@14) */
  w14  = (w02/w14);
  /* #175: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #176: @6 = (@6*@2) */
  w06 *= w02;
  /* #177: @13 = (@13*@6) */
  w13 *= w06;
  /* #178: @14 = (@14-@13) */
  w14 -= w13;
  /* #179: @14 = (@8*@14) */
  w14  = (w08*w14);
  /* #180: @2 = (@11*@2) */
  w02  = (w11*w02);
  /* #181: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #182: @2 = (@5*@2) */
  w02  = (w05*w02);
  /* #183: @9 = (@9*@2) */
  w09 *= w02;
  /* #184: @14 = (@14+@9) */
  w14 += w09;
  /* #185: @14 = (-@14) */
  w14 = (- w14 );
  /* #186: (@24[0] += @14) */
  for (rr=w24+0, cs=(&w14); rr!=w24+1; rr+=1) *rr += *cs++;
  /* #187: @11 = (@11*@2) */
  w11 *= w02;
  /* #188: @12 = (@12*@6) */
  w12 *= w06;
  /* #189: @8 = (@8*@12) */
  w08 *= w12;
  /* #190: @11 = (@11-@8) */
  w11 -= w08;
  /* #191: (@24[1] += @11) */
  for (rr=w24+1, cs=(&w11); rr!=w24+2; rr+=1) *rr += *cs++;
  /* #192: @30 = @24[0, 1, 7, 8, 9, 10] */
  for (cii=casadi_s3, rr=w30, cs=w24; cii!=casadi_s3+6; ++cii) *rr++ = cs[*cii];
  /* #193: (@25[6, 7, 13, 14, 15, 16] = @30) */
  for (cii=casadi_s4, rr=w25, cs=w30; cii!=casadi_s4+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #194: (@25[5, 7, 10, 14, 18, 22] = @30) */
  for (cii=casadi_s5, rr=w25, cs=w30; cii!=casadi_s5+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #195: @11 = ones(15x1,1nz) */
  w11 = 1.;
  /* #196: {NULL, @8} = vertsplit(@11) */
  w08 = w11;
  /* #197: @11 = @8[0] */
  for (rr=(&w11), cs=(&w08)+0; cs!=(&w08)+1; cs+=1) *rr++ = *cs;
  /* #198: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #199: @8 = (@10*@11) */
  w08  = (w10*w11);
  /* #200: @24 = @1; (@24[10] += @8) */
  casadi_copy(w01, 11, w24);
  for (rr=w24+10, cs=(&w08); rr!=w24+11; rr+=1) *rr += *cs++;
  /* #201: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #202: @11 = (@8+@11) */
  w11  = (w08+w11);
  /* #203: (@24[9] += @11) */
  for (rr=w24+9, cs=(&w11); rr!=w24+10; rr+=1) *rr += *cs++;
  /* #204: (@24[8] += @8) */
  for (rr=w24+8, cs=(&w08); rr!=w24+9; rr+=1) *rr += *cs++;
  /* #205: (@24[7] += @8) */
  for (rr=w24+7, cs=(&w08); rr!=w24+8; rr+=1) *rr += *cs++;
  /* #206: @16 = @24[7:11] */
  for (rr=w16, cs=w24+7; cs!=w24+11; cs+=1) *rr++ = *cs;
  /* #207: (@25[17:21] = @16) */
  for (rr=w25+17, cs=w16; rr!=w25+21; rr+=1) *rr = *cs++;
  /* #208: (@25[11:27:4] = @16) */
  for (rr=w25+11, cs=w16; rr!=w25+27; rr+=4) *rr = *cs++;
  /* #209: @8 = ones(15x1,1nz) */
  w08 = 1.;
  /* #210: {NULL, @11} = vertsplit(@8) */
  w11 = w08;
  /* #211: @8 = @11[0] */
  for (rr=(&w08), cs=(&w11)+0; cs!=(&w11)+1; cs+=1) *rr++ = *cs;
  /* #212: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #213: @10 = (@10*@8) */
  w10 *= w08;
  /* #214: @5 = (@5*@8) */
  w05 *= w08;
  /* #215: @5 = (@10+@5) */
  w05  = (w10+w05);
  /* #216: (@1[10] += @5) */
  for (rr=w01+10, cs=(&w05); rr!=w01+11; rr+=1) *rr += *cs++;
  /* #217: (@1[9] += @10) */
  for (rr=w01+9, cs=(&w10); rr!=w01+10; rr+=1) *rr += *cs++;
  /* #218: (@1[8] += @10) */
  for (rr=w01+8, cs=(&w10); rr!=w01+9; rr+=1) *rr += *cs++;
  /* #219: (@1[7] += @10) */
  for (rr=w01+7, cs=(&w10); rr!=w01+8; rr+=1) *rr += *cs++;
  /* #220: @16 = @1[7:11] */
  for (rr=w16, cs=w01+7; cs!=w01+11; cs+=1) *rr++ = *cs;
  /* #221: (@25[21:25] = @16) */
  for (rr=w25+21, cs=w16; rr!=w25+25; rr+=1) *rr = *cs++;
  /* #222: (@25[12:28:4] = @16) */
  for (rr=w25+12, cs=w16; rr!=w25+28; rr+=4) *rr = *cs++;
  /* #223: @31 = @25' */
  casadi_trans(w25,casadi_s6, w31, casadi_s6, iw);
  /* #224: output[2][0] = @31 */
  casadi_copy(w31, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    case 3: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s12;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 16;
  if (sz_w) *sz_w = 140;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 16*sizeof(casadi_int);
  if (sz_w) *sz_w = 140*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
