/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[15] = 
  {11, 11, 0, 0, 0, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 2};
static const casadi_int casadi_s1[3] = {11, 1, 1};
static const casadi_int casadi_s2[3] = {8, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};
static const casadi_int casadi_s4[5] = {11, 1, 0, 1, 2};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_e_fun_jac_hess:(i0[11],i1[8])->(o0,o1[11x1,1nz],o2[11x11,1nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, w2, w4;
  const casadi_real *cs, *wr1, *wr3;
  /* #0: @0 = 10000 */
  w0 = 10000.;
  /* #1: @1 = input[0][0] */
  wr1 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w2 = wr1[2];
  /* #3: @3 = input[1][0] */
  wr3 = arg[1] ? arg[1] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w4 = wr3[0];
  /* #5: @2 = (@2-@4) */
  w2 -= w4;
  /* #6: @4 = sq(@2) */
  w4 = casadi_sq( w2 );
  /* #7: @4 = (@0*@4) */
  w4  = (w0*w4);
  /* #8: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #9: @4 = zeros(11x1,1nz) */
  w4 = 0.;
  /* #10: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #11: @0 = (@0*@2) */
  w0 *= w2;
  /* #12: @2 = @4; (@2[0] = @0) */
  casadi_copy((&w4), 1, (&w2));
  for (rr=(&w2)+0, cs=(&w0); rr!=(&w2)+1; rr+=1) *rr = *cs++;
  /* #13: output[1][0] = @2 */
  if (res[1]) res[1][0] = w2;
  /* #14: @2 = zeros(11x11,1nz) */
  w2 = 0.;
  /* #15: @0 = 20000 */
  w0 = 20000.;
  /* #16: (@4[0] += @0) */
  for (rr=(&w4)+0, cs=(&w0); rr!=(&w4)+1; rr+=1) *rr += *cs++;
  /* #17: @0 = @4[0] */
  for (rr=(&w0), cs=(&w4)+0; cs!=(&w4)+1; cs+=1) *rr++ = *cs;
  /* #18: (@2[0] = @0) */
  for (rr=(&w2)+0, cs=(&w0); rr!=(&w2)+1; rr+=1) *rr = *cs++;
  /* #19: @0 = @2' */
  casadi_trans((&w2),casadi_s0, (&w0), casadi_s0, iw);
  /* #20: output[2][0] = @0 */
  if (res[2]) res[2][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 12;
  if (sz_w) *sz_w = 22;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 12*sizeof(casadi_int);
  if (sz_w) *sz_w = 22*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
