/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_e_fun:(i0[11],i1[8])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w2, w4, w5, w6;
  const casadi_real *wr1, *wr3;
  /* #0: @0 = 1000 */
  w0 = 1000.;
  /* #1: @1 = input[0][0] */
  wr1 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w2 = wr1[2];
  /* #3: @3 = input[1][0] */
  wr3 = arg[1] ? arg[1] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w4 = wr3[0];
  /* #5: @2 = (@2-@4) */
  w2 -= w4;
  /* #6: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #7: @0 = (@0*@2) */
  w0 *= w2;
  /* #8: @2 = 50 */
  w2 = 50.;
  /* #9: @4 = @1[1] */
  w4 = wr1[1];
  /* #10: @5 = @1[0] */
  w5 = wr1[0];
  /* #11: @6 = 0.5 */
  w6 = 5.0000000000000000e-01;
  /* #12: @5 = fmax(@5,@6) */
  w5  = casadi_fmax(w5,w6);
  /* #13: @4 = (@4/@5) */
  w4 /= w5;
  /* #14: @4 = sq(@4) */
  w4 = casadi_sq( w4 );
  /* #15: @2 = (@2*@4) */
  w2 *= w4;
  /* #16: @0 = (@0+@2) */
  w0 += w2;
  /* #17: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_e_fun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 24;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 24*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
