/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_0_fun:(i0[11],i1[4],i2[],i3[8])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w02, w04, w05, w06, w07, w08, w09, w10, w11, w12;
  casadi_real w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24;
  casadi_real w25, *w26=w+43;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 1000 */
  w00 = 1000.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @4 = (@2-@4) */
  w04  = (w02-w04);
  /* #6: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #7: @0 = (@0*@4) */
  w00 *= w04;
  /* #8: @4 = 30 */
  w04 = 30.;
  /* #9: @5 = @1[7] */
  w05 = wr01[7];
  /* #10: @6 = @1[8] */
  w06 = wr01[8];
  /* #11: @5 = (@5+@6) */
  w05 += w06;
  /* #12: @6 = @1[9] */
  w06 = wr01[9];
  /* #13: @5 = (@5+@6) */
  w05 += w06;
  /* #14: @6 = @1[10] */
  w06 = wr01[10];
  /* #15: @5 = (@5+@6) */
  w05 += w06;
  /* #16: @6 = @3[7] */
  w06 = wr03[7];
  /* #17: @5 = (@5-@6) */
  w05 -= w06;
  /* #18: @5 = sq(@5) */
  w05 = casadi_sq( w05 );
  /* #19: @4 = (@4*@5) */
  w04 *= w05;
  /* #20: @0 = (@0+@4) */
  w00 += w04;
  /* #21: @4 = 5 */
  w04 = 5.;
  /* #22: @5 = 1.5 */
  w05 = 1.5000000000000000e+00;
  /* #23: @6 = @3[3] */
  w06 = wr03[3];
  /* #24: @7 = 10 */
  w07 = 10.;
  /* #25: @6 = fmax(@6,@7) */
  w06  = casadi_fmax(w06,w07);
  /* #26: @6 = (@5*@6) */
  w06  = (w05*w06);
  /* #27: @8 = 1.3 */
  w08 = 1.3000000000000000e+00;
  /* #28: @9 = 9 */
  w09 = 9.;
  /* #29: @10 = 0.0001 */
  w10 = 1.0000000000000000e-04;
  /* #30: @11 = 0.193 */
  w11 = 1.9300000000000000e-01;
  /* #31: @12 = @1[3] */
  w12 = wr01[3];
  /* #32: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #33: @13 = 0.01 */
  w13 = 1.0000000000000002e-02;
  /* #34: @14 = @1[0] */
  w14 = wr01[0];
  /* #35: @15 = 0.621 */
  w15 = 6.2100000000000000e-01;
  /* #36: @15 = (@15*@2) */
  w15 *= w02;
  /* #37: @16 = (@14-@15) */
  w16  = (w14-w15);
  /* #38: @17 = @3[1] */
  w17 = wr03[1];
  /* #39: @18 = cos(@17) */
  w18 = cos( w17 );
  /* #40: @19 = (@16*@18) */
  w19  = (w16*w18);
  /* #41: @20 = @1[1] */
  w20 = wr01[1];
  /* #42: @21 = 0.765 */
  w21 = 7.6500000000000001e-01;
  /* #43: @21 = (@21*@2) */
  w21 *= w02;
  /* #44: @2 = (@20+@21) */
  w02  = (w20+w21);
  /* #45: @17 = sin(@17) */
  w17 = sin( w17 );
  /* #46: @22 = (@2*@17) */
  w22  = (w02*w17);
  /* #47: @19 = (@19+@22) */
  w19 += w22;
  /* #48: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #49: @19 = (@13+@19) */
  w19  = (w13+w19);
  /* #50: @19 = sqrt(@19) */
  w19 = sqrt( w19 );
  /* #51: @12 = (@12-@19) */
  w12 -= w19;
  /* #52: @12 = (@12/@19) */
  w12 /= w19;
  /* #53: @22 = sq(@12) */
  w22 = casadi_sq( w12 );
  /* #54: @23 = (@2*@18) */
  w23  = (w02*w18);
  /* #55: @24 = (@16*@17) */
  w24  = (w16*w17);
  /* #56: @23 = (@23-@24) */
  w23 -= w24;
  /* #57: @23 = atan2(@23,@19) */
  w23  = atan2(w23,w19);
  /* #58: @19 = sq(@23) */
  w19 = casadi_sq( w23 );
  /* #59: @22 = (@22+@19) */
  w22 += w19;
  /* #60: @22 = (@10+@22) */
  w22  = (w10+w22);
  /* #61: @22 = sqrt(@22) */
  w22 = sqrt( w22 );
  /* #62: @19 = (@9*@22) */
  w19  = (w09*w22);
  /* #63: @24 = 0.7 */
  w24 = 6.9999999999999996e-01;
  /* #64: @25 = atan(@19) */
  w25 = atan( w19 );
  /* #65: @25 = (@19-@25) */
  w25  = (w19-w25);
  /* #66: @25 = (@24*@25) */
  w25  = (w24*w25);
  /* #67: @19 = (@19-@25) */
  w19 -= w25;
  /* #68: @19 = atan(@19) */
  w19 = atan( w19 );
  /* #69: @19 = (@8*@19) */
  w19  = (w08*w19);
  /* #70: @19 = sin(@19) */
  w19 = sin( w19 );
  /* #71: @19 = (@6*@19) */
  w19  = (w06*w19);
  /* #72: @12 = (@12/@22) */
  w12 /= w22;
  /* #73: @12 = (@19*@12) */
  w12  = (w19*w12);
  /* #74: @12 = (@12*@18) */
  w12 *= w18;
  /* #75: @12 = (-@12) */
  w12 = (- w12 );
  /* #76: @23 = (@23/@22) */
  w23 /= w22;
  /* #77: @19 = (@19*@23) */
  w19 *= w23;
  /* #78: @19 = (@19*@17) */
  w19 *= w17;
  /* #79: @12 = (@12-@19) */
  w12 -= w19;
  /* #80: @12 = (@12/@6) */
  w12 /= w06;
  /* #81: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #82: @6 = @3[4] */
  w06 = wr03[4];
  /* #83: @6 = fmax(@6,@7) */
  w06  = casadi_fmax(w06,w07);
  /* #84: @6 = (@5*@6) */
  w06  = (w05*w06);
  /* #85: @19 = @1[4] */
  w19 = wr01[4];
  /* #86: @19 = (@11*@19) */
  w19  = (w11*w19);
  /* #87: @14 = (@14+@15) */
  w14 += w15;
  /* #88: @15 = @3[2] */
  w15 = wr03[2];
  /* #89: @17 = cos(@15) */
  w17 = cos( w15 );
  /* #90: @23 = (@14*@17) */
  w23  = (w14*w17);
  /* #91: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #92: @22 = (@2*@15) */
  w22  = (w02*w15);
  /* #93: @23 = (@23+@22) */
  w23 += w22;
  /* #94: @23 = sq(@23) */
  w23 = casadi_sq( w23 );
  /* #95: @23 = (@13+@23) */
  w23  = (w13+w23);
  /* #96: @23 = sqrt(@23) */
  w23 = sqrt( w23 );
  /* #97: @19 = (@19-@23) */
  w19 -= w23;
  /* #98: @19 = (@19/@23) */
  w19 /= w23;
  /* #99: @22 = sq(@19) */
  w22 = casadi_sq( w19 );
  /* #100: @2 = (@2*@17) */
  w02 *= w17;
  /* #101: @18 = (@14*@15) */
  w18  = (w14*w15);
  /* #102: @2 = (@2-@18) */
  w02 -= w18;
  /* #103: @2 = atan2(@2,@23) */
  w02  = atan2(w02,w23);
  /* #104: @23 = sq(@2) */
  w23 = casadi_sq( w02 );
  /* #105: @22 = (@22+@23) */
  w22 += w23;
  /* #106: @22 = (@10+@22) */
  w22  = (w10+w22);
  /* #107: @22 = sqrt(@22) */
  w22 = sqrt( w22 );
  /* #108: @23 = (@9*@22) */
  w23  = (w09*w22);
  /* #109: @18 = atan(@23) */
  w18 = atan( w23 );
  /* #110: @18 = (@23-@18) */
  w18  = (w23-w18);
  /* #111: @18 = (@24*@18) */
  w18  = (w24*w18);
  /* #112: @23 = (@23-@18) */
  w23 -= w18;
  /* #113: @23 = atan(@23) */
  w23 = atan( w23 );
  /* #114: @23 = (@8*@23) */
  w23  = (w08*w23);
  /* #115: @23 = sin(@23) */
  w23 = sin( w23 );
  /* #116: @23 = (@6*@23) */
  w23  = (w06*w23);
  /* #117: @19 = (@19/@22) */
  w19 /= w22;
  /* #118: @19 = (@23*@19) */
  w19  = (w23*w19);
  /* #119: @19 = (@19*@17) */
  w19 *= w17;
  /* #120: @19 = (-@19) */
  w19 = (- w19 );
  /* #121: @2 = (@2/@22) */
  w02 /= w22;
  /* #122: @23 = (@23*@2) */
  w23 *= w02;
  /* #123: @23 = (@23*@15) */
  w23 *= w15;
  /* #124: @19 = (@19-@23) */
  w19 -= w23;
  /* #125: @19 = (@19/@6) */
  w19 /= w06;
  /* #126: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #127: @12 = (@12+@19) */
  w12 += w19;
  /* #128: @19 = @3[5] */
  w19 = wr03[5];
  /* #129: @19 = fmax(@19,@7) */
  w19  = casadi_fmax(w19,w07);
  /* #130: @19 = (@5*@19) */
  w19  = (w05*w19);
  /* #131: @6 = @1[5] */
  w06 = wr01[5];
  /* #132: @6 = (@11*@6) */
  w06  = (w11*w06);
  /* #133: @16 = sq(@16) */
  w16 = casadi_sq( w16 );
  /* #134: @16 = (@13+@16) */
  w16  = (w13+w16);
  /* #135: @16 = sqrt(@16) */
  w16 = sqrt( w16 );
  /* #136: @6 = (@6-@16) */
  w06 -= w16;
  /* #137: @6 = (@6/@16) */
  w06 /= w16;
  /* #138: @23 = sq(@6) */
  w23 = casadi_sq( w06 );
  /* #139: @20 = (@20-@21) */
  w20 -= w21;
  /* #140: @16 = atan2(@20,@16) */
  w16  = atan2(w20,w16);
  /* #141: @16 = sq(@16) */
  w16 = casadi_sq( w16 );
  /* #142: @23 = (@23+@16) */
  w23 += w16;
  /* #143: @23 = (@10+@23) */
  w23  = (w10+w23);
  /* #144: @23 = sqrt(@23) */
  w23 = sqrt( w23 );
  /* #145: @16 = (@9*@23) */
  w16  = (w09*w23);
  /* #146: @21 = atan(@16) */
  w21 = atan( w16 );
  /* #147: @21 = (@16-@21) */
  w21  = (w16-w21);
  /* #148: @21 = (@24*@21) */
  w21  = (w24*w21);
  /* #149: @16 = (@16-@21) */
  w16 -= w21;
  /* #150: @16 = atan(@16) */
  w16 = atan( w16 );
  /* #151: @16 = (@8*@16) */
  w16  = (w08*w16);
  /* #152: @16 = sin(@16) */
  w16 = sin( w16 );
  /* #153: @16 = (@19*@16) */
  w16  = (w19*w16);
  /* #154: @6 = (@6/@23) */
  w06 /= w23;
  /* #155: @16 = (@16*@6) */
  w16 *= w06;
  /* #156: @16 = (@16/@19) */
  w16 /= w19;
  /* #157: @16 = sq(@16) */
  w16 = casadi_sq( w16 );
  /* #158: @12 = (@12+@16) */
  w12 += w16;
  /* #159: @16 = @3[6] */
  w16 = wr03[6];
  /* #160: @16 = fmax(@16,@7) */
  w16  = casadi_fmax(w16,w07);
  /* #161: @5 = (@5*@16) */
  w05 *= w16;
  /* #162: @16 = @1[6] */
  w16 = wr01[6];
  /* #163: @11 = (@11*@16) */
  w11 *= w16;
  /* #164: @14 = sq(@14) */
  w14 = casadi_sq( w14 );
  /* #165: @13 = (@13+@14) */
  w13 += w14;
  /* #166: @13 = sqrt(@13) */
  w13 = sqrt( w13 );
  /* #167: @11 = (@11-@13) */
  w11 -= w13;
  /* #168: @11 = (@11/@13) */
  w11 /= w13;
  /* #169: @14 = sq(@11) */
  w14 = casadi_sq( w11 );
  /* #170: @20 = atan2(@20,@13) */
  w20  = atan2(w20,w13);
  /* #171: @20 = sq(@20) */
  w20 = casadi_sq( w20 );
  /* #172: @14 = (@14+@20) */
  w14 += w20;
  /* #173: @10 = (@10+@14) */
  w10 += w14;
  /* #174: @10 = sqrt(@10) */
  w10 = sqrt( w10 );
  /* #175: @9 = (@9*@10) */
  w09 *= w10;
  /* #176: @14 = atan(@9) */
  w14 = atan( w09 );
  /* #177: @14 = (@9-@14) */
  w14  = (w09-w14);
  /* #178: @24 = (@24*@14) */
  w24 *= w14;
  /* #179: @9 = (@9-@24) */
  w09 -= w24;
  /* #180: @9 = atan(@9) */
  w09 = atan( w09 );
  /* #181: @8 = (@8*@9) */
  w08 *= w09;
  /* #182: @8 = sin(@8) */
  w08 = sin( w08 );
  /* #183: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #184: @11 = (@11/@10) */
  w11 /= w10;
  /* #185: @8 = (@8*@11) */
  w08 *= w11;
  /* #186: @8 = (@8/@5) */
  w08 /= w05;
  /* #187: @8 = sq(@8) */
  w08 = casadi_sq( w08 );
  /* #188: @12 = (@12+@8) */
  w12 += w08;
  /* #189: @4 = (@4*@12) */
  w04 *= w12;
  /* #190: @0 = (@0+@4) */
  w00 += w04;
  /* #191: @4 = 0.04 */
  w04 = 4.0000000000000001e-02;
  /* #192: @26 = input[1][0] */
  casadi_copy(arg[1], 4, w26);
  /* #193: @12 = @26[0] */
  for (rr=(&w12), cs=w26+0; cs!=w26+1; cs+=1) *rr++ = *cs;
  /* #194: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #195: @8 = @26[1] */
  for (rr=(&w08), cs=w26+1; cs!=w26+2; cs+=1) *rr++ = *cs;
  /* #196: @8 = sq(@8) */
  w08 = casadi_sq( w08 );
  /* #197: @12 = (@12+@8) */
  w12 += w08;
  /* #198: @8 = @26[2] */
  for (rr=(&w08), cs=w26+2; cs!=w26+3; cs+=1) *rr++ = *cs;
  /* #199: @8 = sq(@8) */
  w08 = casadi_sq( w08 );
  /* #200: @12 = (@12+@8) */
  w12 += w08;
  /* #201: @8 = @26[3] */
  for (rr=(&w08), cs=w26+3; cs!=w26+4; cs+=1) *rr++ = *cs;
  /* #202: @8 = sq(@8) */
  w08 = casadi_sq( w08 );
  /* #203: @12 = (@12+@8) */
  w12 += w08;
  /* #204: @4 = (@4*@12) */
  w04 *= w12;
  /* #205: @0 = (@0+@4) */
  w00 += w04;
  /* #206: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 47;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 47*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
