/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {15, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_0_fun_jac:(i0[11],i1[4],i2[],i3[8])->(o0,o1[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, *w01=w+1, w02, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real *w12=w+29, w13, w14, w15, w16, w17;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 10000 */
  w00 = 10000.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = 10 */
  w05 = 10.;
  /* #9: @6 = @1[7] */
  w06 = wr01[7];
  /* #10: @7 = @1[8] */
  w07 = wr01[8];
  /* #11: @8 = (@6+@7) */
  w08  = (w06+w07);
  /* #12: @9 = @1[9] */
  w09 = wr01[9];
  /* #13: @8 = (@8+@9) */
  w08 += w09;
  /* #14: @10 = @1[10] */
  w10 = wr01[10];
  /* #15: @8 = (@8+@10) */
  w08 += w10;
  /* #16: @11 = @3[7] */
  w11 = wr03[7];
  /* #17: @8 = (@8-@11) */
  w08 -= w11;
  /* #18: @11 = sq(@8) */
  w11 = casadi_sq( w08 );
  /* #19: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #20: @4 = (@4+@11) */
  w04 += w11;
  /* #21: @11 = 0.08 */
  w11 = 8.0000000000000002e-02;
  /* #22: @6 = (@6-@9) */
  w06 -= w09;
  /* #23: @9 = sq(@6) */
  w09 = casadi_sq( w06 );
  /* #24: @7 = (@7-@10) */
  w07 -= w10;
  /* #25: @10 = sq(@7) */
  w10 = casadi_sq( w07 );
  /* #26: @9 = (@9+@10) */
  w09 += w10;
  /* #27: @9 = (@11*@9) */
  w09  = (w11*w09);
  /* #28: @4 = (@4+@9) */
  w04 += w09;
  /* #29: @9 = 0.05 */
  w09 = 5.0000000000000003e-02;
  /* #30: @12 = input[1][0] */
  casadi_copy(arg[1], 4, w12);
  /* #31: @10 = @12[0] */
  for (rr=(&w10), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #32: @13 = sq(@10) */
  w13 = casadi_sq( w10 );
  /* #33: @14 = @12[1] */
  for (rr=(&w14), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #34: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #35: @13 = (@13+@15) */
  w13 += w15;
  /* #36: @15 = @12[2] */
  for (rr=(&w15), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #37: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #38: @13 = (@13+@16) */
  w13 += w16;
  /* #39: @16 = @12[3] */
  for (rr=(&w16), cs=w12+3; cs!=w12+4; cs+=1) *rr++ = *cs;
  /* #40: @17 = sq(@16) */
  w17 = casadi_sq( w16 );
  /* #41: @13 = (@13+@17) */
  w13 += w17;
  /* #42: @13 = (@9*@13) */
  w13  = (w09*w13);
  /* #43: @4 = (@4+@13) */
  w04 += w13;
  /* #44: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #45: @12 = zeros(4x1) */
  casadi_clear(w12, 4);
  /* #46: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #47: @16 = (@9*@16) */
  w16  = (w09*w16);
  /* #48: (@12[3] += @16) */
  for (rr=w12+3, cs=(&w16); rr!=w12+4; rr+=1) *rr += *cs++;
  /* #49: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #50: @15 = (@9*@15) */
  w15  = (w09*w15);
  /* #51: (@12[2] += @15) */
  for (rr=w12+2, cs=(&w15); rr!=w12+3; rr+=1) *rr += *cs++;
  /* #52: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #53: @14 = (@9*@14) */
  w14  = (w09*w14);
  /* #54: (@12[1] += @14) */
  for (rr=w12+1, cs=(&w14); rr!=w12+2; rr+=1) *rr += *cs++;
  /* #55: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #56: @9 = (@9*@10) */
  w09 *= w10;
  /* #57: (@12[0] += @9) */
  for (rr=w12+0, cs=(&w09); rr!=w12+1; rr+=1) *rr += *cs++;
  /* #58: output[1][0] = @12 */
  casadi_copy(w12, 4, res[1]);
  /* #59: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #60: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #61: @5 = (@5*@8) */
  w05 *= w08;
  /* #62: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #63: @7 = (@11*@7) */
  w07  = (w11*w07);
  /* #64: @8 = (@5-@7) */
  w08  = (w05-w07);
  /* #65: (@1[10] += @8) */
  for (rr=w01+10, cs=(&w08); rr!=w01+11; rr+=1) *rr += *cs++;
  /* #66: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #67: @11 = (@11*@6) */
  w11 *= w06;
  /* #68: @6 = (@5-@11) */
  w06  = (w05-w11);
  /* #69: (@1[9] += @6) */
  for (rr=w01+9, cs=(&w06); rr!=w01+10; rr+=1) *rr += *cs++;
  /* #70: @7 = (@7+@5) */
  w07 += w05;
  /* #71: (@1[8] += @7) */
  for (rr=w01+8, cs=(&w07); rr!=w01+9; rr+=1) *rr += *cs++;
  /* #72: @11 = (@11+@5) */
  w11 += w05;
  /* #73: (@1[7] += @11) */
  for (rr=w01+7, cs=(&w11); rr!=w01+8; rr+=1) *rr += *cs++;
  /* #74: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #75: @0 = (@0*@2) */
  w00 *= w02;
  /* #76: (@1[2] += @0) */
  for (rr=w01+2, cs=(&w00); rr!=w01+3; rr+=1) *rr += *cs++;
  /* #77: output[1][1] = @1 */
  if (res[1]) casadi_copy(w01, 11, res[1]+4);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 38;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 38*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
