/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[19] = 
  {11, 11, 0, 2, 4, 5, 5, 5,
  5, 5, 5, 5, 5, 5, 0, 1,
  0, 1, 2};
static const casadi_int casadi_s1[3] = {11, 1, 1};
static const casadi_int casadi_s2[3] = {8, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};
static const casadi_int casadi_s4[7] = {11, 1, 0, 3, 0, 1, 2};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_e_fun_jac_hess:(i0[11],i1[8])->(o0,o1[11x1,3nz],o2[11x11,5nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, *w01=w+1, w02, w04, w05, w06, w07, w08, w09, *w10=w+27, w11;
  casadi_real *w12=w+31, w13, *w14=w+43, *w15=w+46, w16, *w17=w+52, *w18=w+55, *w19=w+57;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 18 */
  w00 = 18.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[1][0] */
  wr03 = arg[1] ? arg[1] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = 5 */
  w05 = 5.;
  /* #9: @6 = @1[1] */
  w06 = wr01[1];
  /* #10: @7 = 1 */
  w07 = 1.;
  /* #11: @8 = @1[0] */
  w08 = wr01[0];
  /* #12: @7 = (@7+@8) */
  w07 += w08;
  /* #13: @8 = atan2(@6,@7) */
  w08  = atan2(w06,w07);
  /* #14: @9 = sq(@8) */
  w09 = casadi_sq( w08 );
  /* #15: @9 = (@5*@9) */
  w09  = (w05*w09);
  /* #16: @4 = (@4+@9) */
  w04 += w09;
  /* #17: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #18: @10 = zeros(11x1,3nz) */
  casadi_clear(w10, 3);
  /* #19: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #20: @4 = sq(@6) */
  w04 = casadi_sq( w06 );
  /* #21: @9 = sq(@7) */
  w09 = casadi_sq( w07 );
  /* #22: @4 = (@4+@9) */
  w04 += w09;
  /* #23: @9 = (@6/@4) */
  w09  = (w06/w04);
  /* #24: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #25: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #26: @11 = (@9*@8) */
  w11  = (w09*w08);
  /* #27: @11 = (-@11) */
  w11 = (- w11 );
  /* #28: @12 = @1; (@12[0] += @11) */
  casadi_copy(w01, 11, w12);
  for (rr=w12+0, cs=(&w11); rr!=w12+1; rr+=1) *rr += *cs++;
  /* #29: @11 = (@7/@4) */
  w11  = (w07/w04);
  /* #30: @13 = (@11*@8) */
  w13  = (w11*w08);
  /* #31: (@12[1] += @13) */
  for (rr=w12+1, cs=(&w13); rr!=w12+2; rr+=1) *rr += *cs++;
  /* #32: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #33: @0 = (@0*@2) */
  w00 *= w02;
  /* #34: (@12[2] += @0) */
  for (rr=w12+2, cs=(&w00); rr!=w12+3; rr+=1) *rr += *cs++;
  /* #35: @0 = @12[0] */
  for (rr=(&w00), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #36: @14 = @10; (@14[0] = @0) */
  casadi_copy(w10, 3, w14);
  for (rr=w14+0, cs=(&w00); rr!=w14+1; rr+=1) *rr = *cs++;
  /* #37: @0 = @12[1] */
  for (rr=(&w00), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #38: (@14[1] = @0) */
  for (rr=w14+1, cs=(&w00); rr!=w14+2; rr+=1) *rr = *cs++;
  /* #39: @0 = @12[2] */
  for (rr=(&w00), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #40: (@14[2] = @0) */
  for (rr=w14+2, cs=(&w00); rr!=w14+3; rr+=1) *rr = *cs++;
  /* #41: output[1][0] = @14 */
  casadi_copy(w14, 3, res[1]);
  /* #42: @15 = zeros(11x11,5nz) */
  casadi_clear(w15, 5);
  /* #43: @0 = (-@9) */
  w00 = (- w09 );
  /* #44: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #45: @0 = (@5*@0) */
  w00  = (w05*w00);
  /* #46: @2 = (@9*@0) */
  w02  = (w09*w00);
  /* #47: @13 = (@9/@4) */
  w13  = (w09/w04);
  /* #48: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #49: @16 = (@13*@7) */
  w16  = (w13*w07);
  /* #50: @16 = (@8*@16) */
  w16  = (w08*w16);
  /* #51: @2 = (@2-@16) */
  w02 -= w16;
  /* #52: @2 = (-@2) */
  w02 = (- w02 );
  /* #53: @12 = @1; (@12[0] += @2) */
  casadi_copy(w01, 11, w12);
  for (rr=w12+0, cs=(&w02); rr!=w12+1; rr+=1) *rr += *cs++;
  /* #54: @2 = (1./@4) */
  w02 = (1./ w04 );
  /* #55: @4 = (@11/@4) */
  w04  = (w11/w04);
  /* #56: @7 = (@4*@7) */
  w07  = (w04*w07);
  /* #57: @7 = (@2-@7) */
  w07  = (w02-w07);
  /* #58: @7 = (@8*@7) */
  w07  = (w08*w07);
  /* #59: @0 = (@11*@0) */
  w00  = (w11*w00);
  /* #60: @7 = (@7+@0) */
  w07 += w00;
  /* #61: (@12[1] += @7) */
  for (rr=w12+1, cs=(&w07); rr!=w12+2; rr+=1) *rr += *cs++;
  /* #62: @7 = 36 */
  w07 = 36.;
  /* #63: (@12[2] += @7) */
  for (rr=w12+2, cs=(&w07); rr!=w12+3; rr+=1) *rr += *cs++;
  /* #64: @7 = @12[0] */
  for (rr=(&w07), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #65: @14 = @10; (@14[0] += @7) */
  casadi_copy(w10, 3, w14);
  for (rr=w14+0, cs=(&w07); rr!=w14+1; rr+=1) *rr += *cs++;
  /* #66: @7 = 0 */
  w07 = 0.;
  /* #67: (@14[1] = @7) */
  for (rr=w14+1, cs=(&w07); rr!=w14+2; rr+=1) *rr = *cs++;
  /* #68: @0 = @12[1] */
  for (rr=(&w00), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #69: (@14[1] += @0) */
  for (rr=w14+1, cs=(&w00); rr!=w14+2; rr+=1) *rr += *cs++;
  /* #70: (@14[2] = @7) */
  for (rr=w14+2, cs=(&w07); rr!=w14+3; rr+=1) *rr = *cs++;
  /* #71: @0 = @12[2] */
  for (rr=(&w00), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #72: (@14[2] += @0) */
  for (rr=w14+2, cs=(&w00); rr!=w14+3; rr+=1) *rr += *cs++;
  /* #73: @17 = @14[:3] */
  for (rr=w17, cs=w14+0; cs!=w14+3; cs+=1) *rr++ = *cs;
  /* #74: (@15[:6:2] = @17) */
  for (rr=w15+0, cs=w17; rr!=w15+6; rr+=2) *rr = *cs++;
  /* #75: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #76: @13 = (@13*@6) */
  w13 *= w06;
  /* #77: @2 = (@2-@13) */
  w02 -= w13;
  /* #78: @2 = (@8*@2) */
  w02  = (w08*w02);
  /* #79: @13 = (2.*@11) */
  w13 = (2.* w11 );
  /* #80: @5 = (@5*@13) */
  w05 *= w13;
  /* #81: @9 = (@9*@5) */
  w09 *= w05;
  /* #82: @2 = (@2+@9) */
  w02 += w09;
  /* #83: @2 = (-@2) */
  w02 = (- w02 );
  /* #84: (@1[0] += @2) */
  for (rr=w01+0, cs=(&w02); rr!=w01+1; rr+=1) *rr += *cs++;
  /* #85: @11 = (@11*@5) */
  w11 *= w05;
  /* #86: @4 = (@4*@6) */
  w04 *= w06;
  /* #87: @8 = (@8*@4) */
  w08 *= w04;
  /* #88: @11 = (@11-@8) */
  w11 -= w08;
  /* #89: (@1[1] += @11) */
  for (rr=w01+1, cs=(&w11); rr!=w01+2; rr+=1) *rr += *cs++;
  /* #90: @11 = @1[0] */
  for (rr=(&w11), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #91: (@10[0] += @11) */
  for (rr=w10+0, cs=(&w11); rr!=w10+1; rr+=1) *rr += *cs++;
  /* #92: (@10[1] = @7) */
  for (rr=w10+1, cs=(&w07); rr!=w10+2; rr+=1) *rr = *cs++;
  /* #93: @11 = @1[1] */
  for (rr=(&w11), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #94: (@10[1] += @11) */
  for (rr=w10+1, cs=(&w11); rr!=w10+2; rr+=1) *rr += *cs++;
  /* #95: (@10[2] = @7) */
  for (rr=w10+2, cs=(&w07); rr!=w10+3; rr+=1) *rr = *cs++;
  /* #96: @7 = @1[2] */
  for (rr=(&w07), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #97: (@10[2] += @7) */
  for (rr=w10+2, cs=(&w07); rr!=w10+3; rr+=1) *rr += *cs++;
  /* #98: @18 = @10[:2] */
  for (rr=w18, cs=w10+0; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #99: (@15[1:5:2] = @18) */
  for (rr=w15+1, cs=w18; rr!=w15+5; rr+=2) *rr = *cs++;
  /* #100: @19 = @15' */
  casadi_trans(w15,casadi_s0, w19, casadi_s0, iw);
  /* #101: output[2][0] = @19 */
  casadi_copy(w19, 5, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 12;
  if (sz_w) *sz_w = 62;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 12*sizeof(casadi_int);
  if (sz_w) *sz_w = 62*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
