/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[19] = 
  {11, 11, 0, 2, 4, 5, 5, 5,
  5, 5, 5, 5, 5, 5, 0, 1,
  0, 1, 2};
static const casadi_int casadi_s1[3] = {11, 1, 1};
static const casadi_int casadi_s2[3] = {8, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};
static const casadi_int casadi_s4[7] = {11, 1, 0, 3, 0, 1, 2};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_e_fun_jac_hess:(i0[11],i1[8])->(o0,o1[11x1,3nz],o2[11x11,5nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, *w01=w+1, w02, w04, w05, w06, w07, w08, w09, w10, *w11=w+28;
  casadi_real *w12=w+31, *w13=w+42, *w14=w+45, *w15=w+50, *w16=w+53, *w17=w+55;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 1000 */
  w00 = 1000.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[1][0] */
  wr03 = arg[1] ? arg[1] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = 50 */
  w05 = 50.;
  /* #9: @6 = @1[1] */
  w06 = wr01[1];
  /* #10: @7 = @1[0] */
  w07 = wr01[0];
  /* #11: @8 = 0.5 */
  w08 = 5.0000000000000000e-01;
  /* #12: @9 = fmax(@7,@8) */
  w09  = casadi_fmax(w07,w08);
  /* #13: @6 = (@6/@9) */
  w06 /= w09;
  /* #14: @10 = sq(@6) */
  w10 = casadi_sq( w06 );
  /* #15: @10 = (@5*@10) */
  w10  = (w05*w10);
  /* #16: @4 = (@4+@10) */
  w04 += w10;
  /* #17: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #18: @11 = zeros(11x1,3nz) */
  casadi_clear(w11, 3);
  /* #19: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #20: @4 = (@8<=@7) */
  w04  = (w08<=w07);
  /* #21: @7 = (@7<=@8) */
  w07  = (w07<=w08);
  /* #22: @7 = (@4+@7) */
  w07  = (w04+w07);
  /* #23: @4 = (@4/@7) */
  w04 /= w07;
  /* #24: @7 = (@6/@9) */
  w07  = (w06/w09);
  /* #25: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #26: @6 = (@5*@6) */
  w06  = (w05*w06);
  /* #27: @8 = (@7*@6) */
  w08  = (w07*w06);
  /* #28: @8 = (@4*@8) */
  w08  = (w04*w08);
  /* #29: @8 = (-@8) */
  w08 = (- w08 );
  /* #30: @12 = @1; (@12[0] += @8) */
  casadi_copy(w01, 11, w12);
  for (rr=w12+0, cs=(&w08); rr!=w12+1; rr+=1) *rr += *cs++;
  /* #31: @8 = (@6/@9) */
  w08  = (w06/w09);
  /* #32: (@12[1] += @8) */
  for (rr=w12+1, cs=(&w08); rr!=w12+2; rr+=1) *rr += *cs++;
  /* #33: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #34: @0 = (@0*@2) */
  w00 *= w02;
  /* #35: (@12[2] += @0) */
  for (rr=w12+2, cs=(&w00); rr!=w12+3; rr+=1) *rr += *cs++;
  /* #36: @0 = @12[0] */
  for (rr=(&w00), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #37: @13 = @11; (@13[0] = @0) */
  casadi_copy(w11, 3, w13);
  for (rr=w13+0, cs=(&w00); rr!=w13+1; rr+=1) *rr = *cs++;
  /* #38: @0 = @12[1] */
  for (rr=(&w00), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #39: (@13[1] = @0) */
  for (rr=w13+1, cs=(&w00); rr!=w13+2; rr+=1) *rr = *cs++;
  /* #40: @0 = @12[2] */
  for (rr=(&w00), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #41: (@13[2] = @0) */
  for (rr=w13+2, cs=(&w00); rr!=w13+3; rr+=1) *rr = *cs++;
  /* #42: output[1][0] = @13 */
  casadi_copy(w13, 3, res[1]);
  /* #43: @14 = zeros(11x11,5nz) */
  casadi_clear(w14, 5);
  /* #44: @0 = (@7/@9) */
  w00  = (w07/w09);
  /* #45: @0 = (@0*@4) */
  w00 *= w04;
  /* #46: @0 = (-@0) */
  w00 = (- w00 );
  /* #47: @2 = (@7*@4) */
  w02  = (w07*w04);
  /* #48: @10 = (@2/@9) */
  w10  = (w02/w09);
  /* #49: @0 = (@0-@10) */
  w00 -= w10;
  /* #50: @0 = (@6*@0) */
  w00  = (w06*w00);
  /* #51: @2 = (-@2) */
  w02 = (- w02 );
  /* #52: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #53: @2 = (@5*@2) */
  w02  = (w05*w02);
  /* #54: @10 = (@7*@2) */
  w10  = (w07*w02);
  /* #55: @0 = (@0+@10) */
  w00 += w10;
  /* #56: @0 = (@4*@0) */
  w00  = (w04*w00);
  /* #57: @0 = (-@0) */
  w00 = (- w00 );
  /* #58: @12 = @1; (@12[0] += @0) */
  casadi_copy(w01, 11, w12);
  for (rr=w12+0, cs=(&w00); rr!=w12+1; rr+=1) *rr += *cs++;
  /* #59: @2 = (@2/@9) */
  w02 /= w09;
  /* #60: @8 = (@8/@9) */
  w08 /= w09;
  /* #61: @8 = (@8*@4) */
  w08 *= w04;
  /* #62: @2 = (@2-@8) */
  w02 -= w08;
  /* #63: (@12[1] += @2) */
  for (rr=w12+1, cs=(&w02); rr!=w12+2; rr+=1) *rr += *cs++;
  /* #64: @2 = 2000 */
  w02 = 2000.;
  /* #65: (@12[2] += @2) */
  for (rr=w12+2, cs=(&w02); rr!=w12+3; rr+=1) *rr += *cs++;
  /* #66: @2 = @12[0] */
  for (rr=(&w02), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #67: @13 = @11; (@13[0] += @2) */
  casadi_copy(w11, 3, w13);
  for (rr=w13+0, cs=(&w02); rr!=w13+1; rr+=1) *rr += *cs++;
  /* #68: @2 = 0 */
  w02 = 0.;
  /* #69: (@13[1] = @2) */
  for (rr=w13+1, cs=(&w02); rr!=w13+2; rr+=1) *rr = *cs++;
  /* #70: @8 = @12[1] */
  for (rr=(&w08), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #71: (@13[1] += @8) */
  for (rr=w13+1, cs=(&w08); rr!=w13+2; rr+=1) *rr += *cs++;
  /* #72: (@13[2] = @2) */
  for (rr=w13+2, cs=(&w02); rr!=w13+3; rr+=1) *rr = *cs++;
  /* #73: @8 = @12[2] */
  for (rr=(&w08), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #74: (@13[2] += @8) */
  for (rr=w13+2, cs=(&w08); rr!=w13+3; rr+=1) *rr += *cs++;
  /* #75: @15 = @13[:3] */
  for (rr=w15, cs=w13+0; cs!=w13+3; cs+=1) *rr++ = *cs;
  /* #76: (@14[:6:2] = @15) */
  for (rr=w14+0, cs=w15; rr!=w14+6; rr+=2) *rr = *cs++;
  /* #77: @8 = (1./@9) */
  w08 = (1./ w09 );
  /* #78: @0 = (@8/@9) */
  w00  = (w08/w09);
  /* #79: @6 = (@6*@0) */
  w06 *= w00;
  /* #80: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #81: @5 = (@5*@8) */
  w05 *= w08;
  /* #82: @7 = (@7*@5) */
  w07 *= w05;
  /* #83: @6 = (@6+@7) */
  w06 += w07;
  /* #84: @4 = (@4*@6) */
  w04 *= w06;
  /* #85: @4 = (-@4) */
  w04 = (- w04 );
  /* #86: (@1[0] += @4) */
  for (rr=w01+0, cs=(&w04); rr!=w01+1; rr+=1) *rr += *cs++;
  /* #87: @5 = (@5/@9) */
  w05 /= w09;
  /* #88: (@1[1] += @5) */
  for (rr=w01+1, cs=(&w05); rr!=w01+2; rr+=1) *rr += *cs++;
  /* #89: @5 = @1[0] */
  for (rr=(&w05), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #90: (@11[0] += @5) */
  for (rr=w11+0, cs=(&w05); rr!=w11+1; rr+=1) *rr += *cs++;
  /* #91: (@11[1] = @2) */
  for (rr=w11+1, cs=(&w02); rr!=w11+2; rr+=1) *rr = *cs++;
  /* #92: @5 = @1[1] */
  for (rr=(&w05), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #93: (@11[1] += @5) */
  for (rr=w11+1, cs=(&w05); rr!=w11+2; rr+=1) *rr += *cs++;
  /* #94: (@11[2] = @2) */
  for (rr=w11+2, cs=(&w02); rr!=w11+3; rr+=1) *rr = *cs++;
  /* #95: @2 = @1[2] */
  for (rr=(&w02), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #96: (@11[2] += @2) */
  for (rr=w11+2, cs=(&w02); rr!=w11+3; rr+=1) *rr += *cs++;
  /* #97: @16 = @11[:2] */
  for (rr=w16, cs=w11+0; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #98: (@14[1:5:2] = @16) */
  for (rr=w14+1, cs=w16; rr!=w14+5; rr+=2) *rr = *cs++;
  /* #99: @17 = @14' */
  casadi_trans(w14,casadi_s0, w17, casadi_s0, iw);
  /* #100: output[2][0] = @17 */
  casadi_copy(w17, 5, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 12;
  if (sz_w) *sz_w = 60;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 12*sizeof(casadi_int);
  if (sz_w) *sz_w = 60*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
