/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {15, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_0_fun_jac:(i0[11],i1[4],i2[],i3[8])->(o0,o1[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, *w01=w+1, w02, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, *w18=w+35, w19, w20, w21, w22, w23;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 500 */
  w00 = 500.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = 30 */
  w05 = 30.;
  /* #9: @6 = @1[7] */
  w06 = wr01[7];
  /* #10: @7 = @1[8] */
  w07 = wr01[8];
  /* #11: @8 = (@6+@7) */
  w08  = (w06+w07);
  /* #12: @9 = @1[9] */
  w09 = wr01[9];
  /* #13: @8 = (@8+@9) */
  w08 += w09;
  /* #14: @10 = @1[10] */
  w10 = wr01[10];
  /* #15: @8 = (@8+@10) */
  w08 += w10;
  /* #16: @11 = @3[7] */
  w11 = wr03[7];
  /* #17: @8 = (@8-@11) */
  w08 -= w11;
  /* #18: @11 = sq(@8) */
  w11 = casadi_sq( w08 );
  /* #19: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #20: @4 = (@4+@11) */
  w04 += w11;
  /* #21: @11 = 0.193 */
  w11 = 1.9300000000000000e-01;
  /* #22: @12 = @3[3] */
  w12 = wr03[3];
  /* #23: @13 = 10 */
  w13 = 10.;
  /* #24: @12 = fmax(@12,@13) */
  w12  = casadi_fmax(w12,w13);
  /* #25: @12 = (@11*@12) */
  w12  = (w11*w12);
  /* #26: @6 = (@6/@12) */
  w06 /= w12;
  /* #27: @14 = sq(@6) */
  w14 = casadi_sq( w06 );
  /* #28: @14 = (@0*@14) */
  w14  = (w00*w14);
  /* #29: @4 = (@4+@14) */
  w04 += w14;
  /* #30: @14 = @3[4] */
  w14 = wr03[4];
  /* #31: @14 = fmax(@14,@13) */
  w14  = casadi_fmax(w14,w13);
  /* #32: @14 = (@11*@14) */
  w14  = (w11*w14);
  /* #33: @7 = (@7/@14) */
  w07 /= w14;
  /* #34: @15 = sq(@7) */
  w15 = casadi_sq( w07 );
  /* #35: @15 = (@0*@15) */
  w15  = (w00*w15);
  /* #36: @4 = (@4+@15) */
  w04 += w15;
  /* #37: @15 = 100 */
  w15 = 100.;
  /* #38: @16 = @3[5] */
  w16 = wr03[5];
  /* #39: @16 = fmax(@16,@13) */
  w16  = casadi_fmax(w16,w13);
  /* #40: @16 = (@11*@16) */
  w16  = (w11*w16);
  /* #41: @9 = (@9/@16) */
  w09 /= w16;
  /* #42: @17 = sq(@9) */
  w17 = casadi_sq( w09 );
  /* #43: @17 = (@15*@17) */
  w17  = (w15*w17);
  /* #44: @4 = (@4+@17) */
  w04 += w17;
  /* #45: @17 = @3[6] */
  w17 = wr03[6];
  /* #46: @17 = fmax(@17,@13) */
  w17  = casadi_fmax(w17,w13);
  /* #47: @11 = (@11*@17) */
  w11 *= w17;
  /* #48: @10 = (@10/@11) */
  w10 /= w11;
  /* #49: @17 = sq(@10) */
  w17 = casadi_sq( w10 );
  /* #50: @17 = (@15*@17) */
  w17  = (w15*w17);
  /* #51: @4 = (@4+@17) */
  w04 += w17;
  /* #52: @17 = 0.02 */
  w17 = 2.0000000000000000e-02;
  /* #53: @18 = input[1][0] */
  casadi_copy(arg[1], 4, w18);
  /* #54: @13 = @18[0] */
  for (rr=(&w13), cs=w18+0; cs!=w18+1; cs+=1) *rr++ = *cs;
  /* #55: @19 = sq(@13) */
  w19 = casadi_sq( w13 );
  /* #56: @20 = @18[1] */
  for (rr=(&w20), cs=w18+1; cs!=w18+2; cs+=1) *rr++ = *cs;
  /* #57: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #58: @19 = (@19+@21) */
  w19 += w21;
  /* #59: @21 = @18[2] */
  for (rr=(&w21), cs=w18+2; cs!=w18+3; cs+=1) *rr++ = *cs;
  /* #60: @22 = sq(@21) */
  w22 = casadi_sq( w21 );
  /* #61: @19 = (@19+@22) */
  w19 += w22;
  /* #62: @22 = @18[3] */
  for (rr=(&w22), cs=w18+3; cs!=w18+4; cs+=1) *rr++ = *cs;
  /* #63: @23 = sq(@22) */
  w23 = casadi_sq( w22 );
  /* #64: @19 = (@19+@23) */
  w19 += w23;
  /* #65: @19 = (@17*@19) */
  w19  = (w17*w19);
  /* #66: @4 = (@4+@19) */
  w04 += w19;
  /* #67: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #68: @18 = zeros(4x1) */
  casadi_clear(w18, 4);
  /* #69: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #70: @22 = (@17*@22) */
  w22  = (w17*w22);
  /* #71: (@18[3] += @22) */
  for (rr=w18+3, cs=(&w22); rr!=w18+4; rr+=1) *rr += *cs++;
  /* #72: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #73: @21 = (@17*@21) */
  w21  = (w17*w21);
  /* #74: (@18[2] += @21) */
  for (rr=w18+2, cs=(&w21); rr!=w18+3; rr+=1) *rr += *cs++;
  /* #75: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #76: @20 = (@17*@20) */
  w20  = (w17*w20);
  /* #77: (@18[1] += @20) */
  for (rr=w18+1, cs=(&w20); rr!=w18+2; rr+=1) *rr += *cs++;
  /* #78: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #79: @17 = (@17*@13) */
  w17 *= w13;
  /* #80: (@18[0] += @17) */
  for (rr=w18+0, cs=(&w17); rr!=w18+1; rr+=1) *rr += *cs++;
  /* #81: output[1][0] = @18 */
  casadi_copy(w18, 4, res[1]);
  /* #82: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #83: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #84: @10 = (@15*@10) */
  w10  = (w15*w10);
  /* #85: @10 = (@10/@11) */
  w10 /= w11;
  /* #86: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #87: @5 = (@5*@8) */
  w05 *= w08;
  /* #88: @10 = (@10+@5) */
  w10 += w05;
  /* #89: (@1[10] += @10) */
  for (rr=w01+10, cs=(&w10); rr!=w01+11; rr+=1) *rr += *cs++;
  /* #90: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #91: @15 = (@15*@9) */
  w15 *= w09;
  /* #92: @15 = (@15/@16) */
  w15 /= w16;
  /* #93: @15 = (@15+@5) */
  w15 += w05;
  /* #94: (@1[9] += @15) */
  for (rr=w01+9, cs=(&w15); rr!=w01+10; rr+=1) *rr += *cs++;
  /* #95: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #96: @7 = (@0*@7) */
  w07  = (w00*w07);
  /* #97: @7 = (@7/@14) */
  w07 /= w14;
  /* #98: @7 = (@7+@5) */
  w07 += w05;
  /* #99: (@1[8] += @7) */
  for (rr=w01+8, cs=(&w07); rr!=w01+9; rr+=1) *rr += *cs++;
  /* #100: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #101: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #102: @6 = (@6/@12) */
  w06 /= w12;
  /* #103: @6 = (@6+@5) */
  w06 += w05;
  /* #104: (@1[7] += @6) */
  for (rr=w01+7, cs=(&w06); rr!=w01+8; rr+=1) *rr += *cs++;
  /* #105: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #106: @0 = (@0*@2) */
  w00 *= w02;
  /* #107: (@1[2] += @0) */
  for (rr=w01+2, cs=(&w00); rr!=w01+3; rr+=1) *rr += *cs++;
  /* #108: output[1][1] = @1 */
  if (res[1]) casadi_copy(w01, 11, res[1]+4);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 44;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 44*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
