/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {15, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_fun_jac:(i0[11],i1[4],i2[],i3[8])->(o0,o1[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, *w01=w+1, w02, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+39, w23;
  casadi_real w24, w25, w26;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 1000 */
  w00 = 1000.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = 50 */
  w05 = 50.;
  /* #9: @6 = @1[1] */
  w06 = wr01[1];
  /* #10: @7 = @1[0] */
  w07 = wr01[0];
  /* #11: @8 = 0.5 */
  w08 = 5.0000000000000000e-01;
  /* #12: @9 = fmax(@7,@8) */
  w09  = casadi_fmax(w07,w08);
  /* #13: @6 = (@6/@9) */
  w06 /= w09;
  /* #14: @10 = sq(@6) */
  w10 = casadi_sq( w06 );
  /* #15: @10 = (@5*@10) */
  w10  = (w05*w10);
  /* #16: @4 = (@4+@10) */
  w04 += w10;
  /* #17: @10 = @1[7] */
  w10 = wr01[7];
  /* #18: @11 = @1[8] */
  w11 = wr01[8];
  /* #19: @12 = (@10+@11) */
  w12  = (w10+w11);
  /* #20: @13 = @1[9] */
  w13 = wr01[9];
  /* #21: @12 = (@12+@13) */
  w12 += w13;
  /* #22: @14 = @1[10] */
  w14 = wr01[10];
  /* #23: @12 = (@12+@14) */
  w12 += w14;
  /* #24: @15 = @3[7] */
  w15 = wr03[7];
  /* #25: @12 = (@12-@15) */
  w12 -= w15;
  /* #26: @15 = sq(@12) */
  w15 = casadi_sq( w12 );
  /* #27: @15 = (@5*@15) */
  w15  = (w05*w15);
  /* #28: @4 = (@4+@15) */
  w04 += w15;
  /* #29: @15 = sq(@10) */
  w15 = casadi_sq( w10 );
  /* #30: @16 = @3[3] */
  w16 = wr03[3];
  /* #31: @17 = 10 */
  w17 = 10.;
  /* #32: @16 = fmax(@16,@17) */
  w16  = casadi_fmax(w16,w17);
  /* #33: @15 = (@15/@16) */
  w15 /= w16;
  /* #34: @18 = sq(@11) */
  w18 = casadi_sq( w11 );
  /* #35: @19 = @3[4] */
  w19 = wr03[4];
  /* #36: @19 = fmax(@19,@17) */
  w19  = casadi_fmax(w19,w17);
  /* #37: @18 = (@18/@19) */
  w18 /= w19;
  /* #38: @15 = (@15+@18) */
  w15 += w18;
  /* #39: @18 = sq(@13) */
  w18 = casadi_sq( w13 );
  /* #40: @20 = @3[5] */
  w20 = wr03[5];
  /* #41: @20 = fmax(@20,@17) */
  w20  = casadi_fmax(w20,w17);
  /* #42: @18 = (@18/@20) */
  w18 /= w20;
  /* #43: @15 = (@15+@18) */
  w15 += w18;
  /* #44: @18 = sq(@14) */
  w18 = casadi_sq( w14 );
  /* #45: @21 = @3[6] */
  w21 = wr03[6];
  /* #46: @21 = fmax(@21,@17) */
  w21  = casadi_fmax(w21,w17);
  /* #47: @18 = (@18/@21) */
  w18 /= w21;
  /* #48: @15 = (@15+@18) */
  w15 += w18;
  /* #49: @4 = (@4+@15) */
  w04 += w15;
  /* #50: @15 = 0.01 */
  w15 = 1.0000000000000000e-02;
  /* #51: @22 = input[1][0] */
  casadi_copy(arg[1], 4, w22);
  /* #52: @18 = @22[0] */
  for (rr=(&w18), cs=w22+0; cs!=w22+1; cs+=1) *rr++ = *cs;
  /* #53: @17 = sq(@18) */
  w17 = casadi_sq( w18 );
  /* #54: @23 = @22[1] */
  for (rr=(&w23), cs=w22+1; cs!=w22+2; cs+=1) *rr++ = *cs;
  /* #55: @24 = sq(@23) */
  w24 = casadi_sq( w23 );
  /* #56: @17 = (@17+@24) */
  w17 += w24;
  /* #57: @24 = @22[2] */
  for (rr=(&w24), cs=w22+2; cs!=w22+3; cs+=1) *rr++ = *cs;
  /* #58: @25 = sq(@24) */
  w25 = casadi_sq( w24 );
  /* #59: @17 = (@17+@25) */
  w17 += w25;
  /* #60: @25 = @22[3] */
  for (rr=(&w25), cs=w22+3; cs!=w22+4; cs+=1) *rr++ = *cs;
  /* #61: @26 = sq(@25) */
  w26 = casadi_sq( w25 );
  /* #62: @17 = (@17+@26) */
  w17 += w26;
  /* #63: @17 = (@15*@17) */
  w17  = (w15*w17);
  /* #64: @4 = (@4+@17) */
  w04 += w17;
  /* #65: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #66: @22 = zeros(4x1) */
  casadi_clear(w22, 4);
  /* #67: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #68: @25 = (@15*@25) */
  w25  = (w15*w25);
  /* #69: (@22[3] += @25) */
  for (rr=w22+3, cs=(&w25); rr!=w22+4; rr+=1) *rr += *cs++;
  /* #70: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #71: @24 = (@15*@24) */
  w24  = (w15*w24);
  /* #72: (@22[2] += @24) */
  for (rr=w22+2, cs=(&w24); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #73: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #74: @23 = (@15*@23) */
  w23  = (w15*w23);
  /* #75: (@22[1] += @23) */
  for (rr=w22+1, cs=(&w23); rr!=w22+2; rr+=1) *rr += *cs++;
  /* #76: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #77: @15 = (@15*@18) */
  w15 *= w18;
  /* #78: (@22[0] += @15) */
  for (rr=w22+0, cs=(&w15); rr!=w22+1; rr+=1) *rr += *cs++;
  /* #79: output[1][0] = @22 */
  casadi_copy(w22, 4, res[1]);
  /* #80: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #81: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #82: @14 = (@14/@21) */
  w14 /= w21;
  /* #83: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #84: @12 = (@5*@12) */
  w12  = (w05*w12);
  /* #85: @14 = (@14+@12) */
  w14 += w12;
  /* #86: (@1[10] += @14) */
  for (rr=w01+10, cs=(&w14); rr!=w01+11; rr+=1) *rr += *cs++;
  /* #87: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #88: @13 = (@13/@20) */
  w13 /= w20;
  /* #89: @13 = (@13+@12) */
  w13 += w12;
  /* #90: (@1[9] += @13) */
  for (rr=w01+9, cs=(&w13); rr!=w01+10; rr+=1) *rr += *cs++;
  /* #91: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #92: @11 = (@11/@19) */
  w11 /= w19;
  /* #93: @11 = (@11+@12) */
  w11 += w12;
  /* #94: (@1[8] += @11) */
  for (rr=w01+8, cs=(&w11); rr!=w01+9; rr+=1) *rr += *cs++;
  /* #95: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #96: @10 = (@10/@16) */
  w10 /= w16;
  /* #97: @10 = (@10+@12) */
  w10 += w12;
  /* #98: (@1[7] += @10) */
  for (rr=w01+7, cs=(&w10); rr!=w01+8; rr+=1) *rr += *cs++;
  /* #99: @10 = (@8<=@7) */
  w10  = (w08<=w07);
  /* #100: @7 = (@7<=@8) */
  w07  = (w07<=w08);
  /* #101: @7 = (@10+@7) */
  w07  = (w10+w07);
  /* #102: @10 = (@10/@7) */
  w10 /= w07;
  /* #103: @7 = (@6/@9) */
  w07  = (w06/w09);
  /* #104: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #105: @5 = (@5*@6) */
  w05 *= w06;
  /* #106: @7 = (@7*@5) */
  w07 *= w05;
  /* #107: @10 = (@10*@7) */
  w10 *= w07;
  /* #108: @10 = (-@10) */
  w10 = (- w10 );
  /* #109: (@1[0] += @10) */
  for (rr=w01+0, cs=(&w10); rr!=w01+1; rr+=1) *rr += *cs++;
  /* #110: @5 = (@5/@9) */
  w05 /= w09;
  /* #111: (@1[1] += @5) */
  for (rr=w01+1, cs=(&w05); rr!=w01+2; rr+=1) *rr += *cs++;
  /* #112: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #113: @0 = (@0*@2) */
  w00 *= w02;
  /* #114: (@1[2] += @0) */
  for (rr=w01+2, cs=(&w00); rr!=w01+3; rr+=1) *rr += *cs++;
  /* #115: output[1][1] = @1 */
  if (res[1]) casadi_copy(w01, 11, res[1]+4);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 47;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 47*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
