/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = 
  {0, 1, 2, 3, 6, 11, 12, 13,
  14};
static const casadi_int casadi_s1[9] = 
  {0, 1, 2, 3, 4, 5, 9, 13,
  17};
static const casadi_int casadi_s2[39] = 
  {15, 15, 0, 1, 2, 3, 4, 4,
  4, 5, 5, 5, 5, 5, 9, 13,
  17, 21, 0, 1, 2, 3, 6, 11,
  12, 13, 14, 11, 12, 13, 14, 11,
  12, 13, 14, 11, 12, 13, 14};
static const casadi_int casadi_s3[3] = {11, 1, 1};
static const casadi_int casadi_s4[3] = {4, 1, 1};
static const casadi_int casadi_s5[3] = {0, 0, 1};
static const casadi_int casadi_s6[3] = {8, 1, 1};
static const casadi_int casadi_s7[3] = {1, 1, 1};
static const casadi_int casadi_s8[3] = {15, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_0_fun_jac_hess:(i0[11],i1[4],i2[],i3[8])->(o0,o1[15],o2[15x15,21nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, *w01=w+1, w02, *w03=w+13, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, *w12=w+29, w13, w14, w15, w16, w17, *w18=w+38, *w19=w+42, *w20=w+53, *w21=w+74, *w22=w+86;
  casadi_real *w23=w+101, *w24=w+110;
  const casadi_int *cii;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 10000 */
  w00 = 10000.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = 10 */
  w05 = 10.;
  /* #9: @6 = @1[7] */
  w06 = wr01[7];
  /* #10: @7 = @1[8] */
  w07 = wr01[8];
  /* #11: @8 = (@6+@7) */
  w08  = (w06+w07);
  /* #12: @9 = @1[9] */
  w09 = wr01[9];
  /* #13: @8 = (@8+@9) */
  w08 += w09;
  /* #14: @10 = @1[10] */
  w10 = wr01[10];
  /* #15: @8 = (@8+@10) */
  w08 += w10;
  /* #16: @11 = @3[7] */
  w11 = wr03[7];
  /* #17: @8 = (@8-@11) */
  w08 -= w11;
  /* #18: @11 = sq(@8) */
  w11 = casadi_sq( w08 );
  /* #19: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #20: @4 = (@4+@11) */
  w04 += w11;
  /* #21: @11 = 0.08 */
  w11 = 8.0000000000000002e-02;
  /* #22: @6 = (@6-@9) */
  w06 -= w09;
  /* #23: @9 = sq(@6) */
  w09 = casadi_sq( w06 );
  /* #24: @7 = (@7-@10) */
  w07 -= w10;
  /* #25: @10 = sq(@7) */
  w10 = casadi_sq( w07 );
  /* #26: @9 = (@9+@10) */
  w09 += w10;
  /* #27: @9 = (@11*@9) */
  w09  = (w11*w09);
  /* #28: @4 = (@4+@9) */
  w04 += w09;
  /* #29: @9 = 0.05 */
  w09 = 5.0000000000000003e-02;
  /* #30: @12 = input[1][0] */
  casadi_copy(arg[1], 4, w12);
  /* #31: @10 = @12[0] */
  for (rr=(&w10), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #32: @13 = sq(@10) */
  w13 = casadi_sq( w10 );
  /* #33: @14 = @12[1] */
  for (rr=(&w14), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #34: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #35: @13 = (@13+@15) */
  w13 += w15;
  /* #36: @15 = @12[2] */
  for (rr=(&w15), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #37: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #38: @13 = (@13+@16) */
  w13 += w16;
  /* #39: @16 = @12[3] */
  for (rr=(&w16), cs=w12+3; cs!=w12+4; cs+=1) *rr++ = *cs;
  /* #40: @17 = sq(@16) */
  w17 = casadi_sq( w16 );
  /* #41: @13 = (@13+@17) */
  w13 += w17;
  /* #42: @13 = (@9*@13) */
  w13  = (w09*w13);
  /* #43: @4 = (@4+@13) */
  w04 += w13;
  /* #44: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #45: @12 = zeros(4x1) */
  casadi_clear(w12, 4);
  /* #46: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #47: @16 = (@9*@16) */
  w16  = (w09*w16);
  /* #48: @18 = @12; (@18[3] += @16) */
  casadi_copy(w12, 4, w18);
  for (rr=w18+3, cs=(&w16); rr!=w18+4; rr+=1) *rr += *cs++;
  /* #49: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #50: @15 = (@9*@15) */
  w15  = (w09*w15);
  /* #51: (@18[2] += @15) */
  for (rr=w18+2, cs=(&w15); rr!=w18+3; rr+=1) *rr += *cs++;
  /* #52: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #53: @14 = (@9*@14) */
  w14  = (w09*w14);
  /* #54: (@18[1] += @14) */
  for (rr=w18+1, cs=(&w14); rr!=w18+2; rr+=1) *rr += *cs++;
  /* #55: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #56: @10 = (@9*@10) */
  w10  = (w09*w10);
  /* #57: (@18[0] += @10) */
  for (rr=w18+0, cs=(&w10); rr!=w18+1; rr+=1) *rr += *cs++;
  /* #58: output[1][0] = @18 */
  casadi_copy(w18, 4, res[1]);
  /* #59: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #60: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #61: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #62: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #63: @7 = (@11*@7) */
  w07  = (w11*w07);
  /* #64: @10 = (@8-@7) */
  w10  = (w08-w07);
  /* #65: @19 = @1; (@19[10] += @10) */
  casadi_copy(w01, 11, w19);
  for (rr=w19+10, cs=(&w10); rr!=w19+11; rr+=1) *rr += *cs++;
  /* #66: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #67: @6 = (@11*@6) */
  w06  = (w11*w06);
  /* #68: @10 = (@8-@6) */
  w10  = (w08-w06);
  /* #69: (@19[9] += @10) */
  for (rr=w19+9, cs=(&w10); rr!=w19+10; rr+=1) *rr += *cs++;
  /* #70: @7 = (@7+@8) */
  w07 += w08;
  /* #71: (@19[8] += @7) */
  for (rr=w19+8, cs=(&w07); rr!=w19+9; rr+=1) *rr += *cs++;
  /* #72: @6 = (@6+@8) */
  w06 += w08;
  /* #73: (@19[7] += @6) */
  for (rr=w19+7, cs=(&w06); rr!=w19+8; rr+=1) *rr += *cs++;
  /* #74: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #75: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #76: (@19[2] += @2) */
  for (rr=w19+2, cs=(&w02); rr!=w19+3; rr+=1) *rr += *cs++;
  /* #77: output[1][1] = @19 */
  if (res[1]) casadi_copy(w19, 11, res[1]+4);
  /* #78: @20 = zeros(15x15,21nz) */
  casadi_clear(w20, 21);
  /* #79: @21 = ones(15x1,12nz) */
  casadi_fill(w21, 12, 1.);
  /* #80: {@18, @3} = vertsplit(@21) */
  casadi_copy(w21, 4, w18);
  casadi_copy(w21+4, 8, w03);
  /* #81: @2 = @18[3] */
  for (rr=(&w02), cs=w18+3; cs!=w18+4; cs+=1) *rr++ = *cs;
  /* #82: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #83: @2 = (@9*@2) */
  w02  = (w09*w02);
  /* #84: (@12[3] += @2) */
  for (rr=w12+3, cs=(&w02); rr!=w12+4; rr+=1) *rr += *cs++;
  /* #85: @2 = @18[2] */
  for (rr=(&w02), cs=w18+2; cs!=w18+3; cs+=1) *rr++ = *cs;
  /* #86: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #87: @2 = (@9*@2) */
  w02  = (w09*w02);
  /* #88: (@12[2] += @2) */
  for (rr=w12+2, cs=(&w02); rr!=w12+3; rr+=1) *rr += *cs++;
  /* #89: @2 = @18[1] */
  for (rr=(&w02), cs=w18+1; cs!=w18+2; cs+=1) *rr++ = *cs;
  /* #90: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #91: @2 = (@9*@2) */
  w02  = (w09*w02);
  /* #92: (@12[1] += @2) */
  for (rr=w12+1, cs=(&w02); rr!=w12+2; rr+=1) *rr += *cs++;
  /* #93: @2 = @18[0] */
  for (rr=(&w02), cs=w18+0; cs!=w18+1; cs+=1) *rr++ = *cs;
  /* #94: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #95: @9 = (@9*@2) */
  w09 *= w02;
  /* #96: (@12[0] += @9) */
  for (rr=w12+0, cs=(&w09); rr!=w12+1; rr+=1) *rr += *cs++;
  /* #97: @9 = @3[7] */
  for (rr=(&w09), cs=w03+7; cs!=w03+8; cs+=1) *rr++ = *cs;
  /* #98: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #99: @2 = (@5*@9) */
  w02  = (w05*w09);
  /* #100: @19 = @1; (@19[10] += @2) */
  casadi_copy(w01, 11, w19);
  for (rr=w19+10, cs=(&w02); rr!=w19+11; rr+=1) *rr += *cs++;
  /* #101: @9 = (@11*@9) */
  w09  = (w11*w09);
  /* #102: @6 = (@2-@9) */
  w06  = (w02-w09);
  /* #103: (@19[9] += @6) */
  for (rr=w19+9, cs=(&w06); rr!=w19+10; rr+=1) *rr += *cs++;
  /* #104: (@19[8] += @2) */
  for (rr=w19+8, cs=(&w02); rr!=w19+9; rr+=1) *rr += *cs++;
  /* #105: @9 = (@9+@2) */
  w09 += w02;
  /* #106: (@19[7] += @9) */
  for (rr=w19+7, cs=(&w09); rr!=w19+8; rr+=1) *rr += *cs++;
  /* #107: @9 = @3[2] */
  for (rr=(&w09), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #108: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #109: @0 = (@0*@9) */
  w00 *= w09;
  /* #110: (@19[2] += @0) */
  for (rr=w19+2, cs=(&w00); rr!=w19+3; rr+=1) *rr += *cs++;
  /* #111: @22 = vertcat(@12, @19) */
  rr=w22;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<11; ++i) *rr++ = *cs++;
  /* #112: @23 = @22[0, 1, 2, 3, 6, 11, 12, 13, 14] */
  for (cii=casadi_s0, rr=w23, cs=w22; cii!=casadi_s0+9; ++cii) *rr++ = cs[*cii];
  /* #113: (@20[:9] = @23) */
  for (rr=w20+0, cs=w23; rr!=w20+9; rr+=1) *rr = *cs++;
  /* #114: (@20[0, 1, 2, 3, 4, 5, 9, 13, 17] = @23) */
  for (cii=casadi_s1, rr=w20, cs=w23; cii!=casadi_s1+9; ++cii, ++cs) rr[*cii] = *cs;
  /* #115: @0 = ones(15x1,1nz) */
  w00 = 1.;
  /* #116: {NULL, @9} = vertsplit(@0) */
  w09 = w00;
  /* #117: @0 = @9[0] */
  for (rr=(&w00), cs=(&w09)+0; cs!=(&w09)+1; cs+=1) *rr++ = *cs;
  /* #118: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #119: @9 = (@5*@0) */
  w09  = (w05*w00);
  /* #120: @0 = (@11*@0) */
  w00  = (w11*w00);
  /* #121: @2 = (@9-@0) */
  w02  = (w09-w00);
  /* #122: @19 = @1; (@19[10] += @2) */
  casadi_copy(w01, 11, w19);
  for (rr=w19+10, cs=(&w02); rr!=w19+11; rr+=1) *rr += *cs++;
  /* #123: (@19[9] += @9) */
  for (rr=w19+9, cs=(&w09); rr!=w19+10; rr+=1) *rr += *cs++;
  /* #124: @0 = (@0+@9) */
  w00 += w09;
  /* #125: (@19[8] += @0) */
  for (rr=w19+8, cs=(&w00); rr!=w19+9; rr+=1) *rr += *cs++;
  /* #126: (@19[7] += @9) */
  for (rr=w19+7, cs=(&w09); rr!=w19+8; rr+=1) *rr += *cs++;
  /* #127: @12 = @19[7:11] */
  for (rr=w12, cs=w19+7; cs!=w19+11; cs+=1) *rr++ = *cs;
  /* #128: (@20[9:13] = @12) */
  for (rr=w20+9, cs=w12; rr!=w20+13; rr+=1) *rr = *cs++;
  /* #129: (@20[6:22:4] = @12) */
  for (rr=w20+6, cs=w12; rr!=w20+22; rr+=4) *rr = *cs++;
  /* #130: @9 = ones(15x1,1nz) */
  w09 = 1.;
  /* #131: {NULL, @0} = vertsplit(@9) */
  w00 = w09;
  /* #132: @9 = @0[0] */
  for (rr=(&w09), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #133: @0 = (2.*@9) */
  w00 = (2.* w09 );
  /* #134: @0 = (@5*@0) */
  w00  = (w05*w00);
  /* #135: @19 = @1; (@19[10] += @0) */
  casadi_copy(w01, 11, w19);
  for (rr=w19+10, cs=(&w00); rr!=w19+11; rr+=1) *rr += *cs++;
  /* #136: @9 = (-@9) */
  w09 = (- w09 );
  /* #137: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #138: @9 = (@11*@9) */
  w09  = (w11*w09);
  /* #139: @2 = (@0-@9) */
  w02  = (w00-w09);
  /* #140: (@19[9] += @2) */
  for (rr=w19+9, cs=(&w02); rr!=w19+10; rr+=1) *rr += *cs++;
  /* #141: (@19[8] += @0) */
  for (rr=w19+8, cs=(&w00); rr!=w19+9; rr+=1) *rr += *cs++;
  /* #142: @9 = (@9+@0) */
  w09 += w00;
  /* #143: (@19[7] += @9) */
  for (rr=w19+7, cs=(&w09); rr!=w19+8; rr+=1) *rr += *cs++;
  /* #144: @12 = @19[7:11] */
  for (rr=w12, cs=w19+7; cs!=w19+11; cs+=1) *rr++ = *cs;
  /* #145: (@20[13:17] = @12) */
  for (rr=w20+13, cs=w12; rr!=w20+17; rr+=1) *rr = *cs++;
  /* #146: (@20[7:23:4] = @12) */
  for (rr=w20+7, cs=w12; rr!=w20+23; rr+=4) *rr = *cs++;
  /* #147: @9 = ones(15x1,1nz) */
  w09 = 1.;
  /* #148: {NULL, @0} = vertsplit(@9) */
  w00 = w09;
  /* #149: @9 = @0[0] */
  for (rr=(&w09), cs=(&w00)+0; cs!=(&w00)+1; cs+=1) *rr++ = *cs;
  /* #150: @0 = (2.*@9) */
  w00 = (2.* w09 );
  /* #151: @5 = (@5*@0) */
  w05 *= w00;
  /* #152: @9 = (-@9) */
  w09 = (- w09 );
  /* #153: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #154: @11 = (@11*@9) */
  w11 *= w09;
  /* #155: @9 = (@5-@11) */
  w09  = (w05-w11);
  /* #156: (@1[10] += @9) */
  for (rr=w01+10, cs=(&w09); rr!=w01+11; rr+=1) *rr += *cs++;
  /* #157: (@1[9] += @5) */
  for (rr=w01+9, cs=(&w05); rr!=w01+10; rr+=1) *rr += *cs++;
  /* #158: @11 = (@11+@5) */
  w11 += w05;
  /* #159: (@1[8] += @11) */
  for (rr=w01+8, cs=(&w11); rr!=w01+9; rr+=1) *rr += *cs++;
  /* #160: (@1[7] += @5) */
  for (rr=w01+7, cs=(&w05); rr!=w01+8; rr+=1) *rr += *cs++;
  /* #161: @12 = @1[7:11] */
  for (rr=w12, cs=w01+7; cs!=w01+11; cs+=1) *rr++ = *cs;
  /* #162: (@20[17:21] = @12) */
  for (rr=w20+17, cs=w12; rr!=w20+21; rr+=1) *rr = *cs++;
  /* #163: (@20[8:24:4] = @12) */
  for (rr=w20+8, cs=w12; rr!=w20+24; rr+=4) *rr = *cs++;
  /* #164: @24 = @20' */
  casadi_trans(w20,casadi_s2, w24, casadi_s2, iw);
  /* #165: output[2][0] = @24 */
  casadi_copy(w24, 21, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 16;
  if (sz_w) *sz_w = 131;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 16*sizeof(casadi_int);
  if (sz_w) *sz_w = 131*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
