/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {15, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_fun_jac:(i0[11],i1[4],i2[],i3[8])->(o0,o1[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, *w01=w+1, w02, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+39, w23;
  casadi_real w24, w25, w26, w27, w28;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 10000 */
  w00 = 10000.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = 50 */
  w05 = 50.;
  /* #9: @6 = @1[1] */
  w06 = wr01[1];
  /* #10: @7 = @1[0] */
  w07 = wr01[0];
  /* #11: @8 = 0.5 */
  w08 = 5.0000000000000000e-01;
  /* #12: @9 = fmax(@7,@8) */
  w09  = casadi_fmax(w07,w08);
  /* #13: @6 = (@6/@9) */
  w06 /= w09;
  /* #14: @10 = sq(@6) */
  w10 = casadi_sq( w06 );
  /* #15: @10 = (@5*@10) */
  w10  = (w05*w10);
  /* #16: @4 = (@4+@10) */
  w04 += w10;
  /* #17: @10 = @1[7] */
  w10 = wr01[7];
  /* #18: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #19: @12 = @3[3] */
  w12 = wr03[3];
  /* #20: @13 = 10 */
  w13 = 10.;
  /* #21: @12 = fmax(@12,@13) */
  w12  = casadi_fmax(w12,w13);
  /* #22: @11 = (@11/@12) */
  w11 /= w12;
  /* #23: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #24: @4 = (@4+@11) */
  w04 += w11;
  /* #25: @11 = @1[8] */
  w11 = wr01[8];
  /* #26: @14 = sq(@11) */
  w14 = casadi_sq( w11 );
  /* #27: @15 = @3[4] */
  w15 = wr03[4];
  /* #28: @15 = fmax(@15,@13) */
  w15  = casadi_fmax(w15,w13);
  /* #29: @14 = (@14/@15) */
  w14 /= w15;
  /* #30: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #31: @4 = (@4+@14) */
  w04 += w14;
  /* #32: @14 = 0.8 */
  w14 = 8.0000000000000004e-01;
  /* #33: @16 = @1[9] */
  w16 = wr01[9];
  /* #34: @17 = sq(@16) */
  w17 = casadi_sq( w16 );
  /* #35: @18 = @3[5] */
  w18 = wr03[5];
  /* #36: @18 = fmax(@18,@13) */
  w18  = casadi_fmax(w18,w13);
  /* #37: @17 = (@17/@18) */
  w17 /= w18;
  /* #38: @17 = (@14*@17) */
  w17  = (w14*w17);
  /* #39: @4 = (@4+@17) */
  w04 += w17;
  /* #40: @17 = @1[10] */
  w17 = wr01[10];
  /* #41: @19 = sq(@17) */
  w19 = casadi_sq( w17 );
  /* #42: @20 = @3[6] */
  w20 = wr03[6];
  /* #43: @20 = fmax(@20,@13) */
  w20  = casadi_fmax(w20,w13);
  /* #44: @19 = (@19/@20) */
  w19 /= w20;
  /* #45: @19 = (@14*@19) */
  w19  = (w14*w19);
  /* #46: @4 = (@4+@19) */
  w04 += w19;
  /* #47: @19 = 40 */
  w19 = 40.;
  /* #48: @13 = (@10+@11) */
  w13  = (w10+w11);
  /* #49: @13 = (@13+@16) */
  w13 += w16;
  /* #50: @13 = (@13+@17) */
  w13 += w17;
  /* #51: @21 = @3[7] */
  w21 = wr03[7];
  /* #52: @13 = (@13-@21) */
  w13 -= w21;
  /* #53: @21 = sq(@13) */
  w21 = casadi_sq( w13 );
  /* #54: @21 = (@19*@21) */
  w21  = (w19*w21);
  /* #55: @4 = (@4+@21) */
  w04 += w21;
  /* #56: @21 = 0.01 */
  w21 = 1.0000000000000000e-02;
  /* #57: @22 = input[1][0] */
  casadi_copy(arg[1], 4, w22);
  /* #58: @23 = @22[0] */
  for (rr=(&w23), cs=w22+0; cs!=w22+1; cs+=1) *rr++ = *cs;
  /* #59: @24 = sq(@23) */
  w24 = casadi_sq( w23 );
  /* #60: @25 = @22[1] */
  for (rr=(&w25), cs=w22+1; cs!=w22+2; cs+=1) *rr++ = *cs;
  /* #61: @26 = sq(@25) */
  w26 = casadi_sq( w25 );
  /* #62: @24 = (@24+@26) */
  w24 += w26;
  /* #63: @26 = @22[2] */
  for (rr=(&w26), cs=w22+2; cs!=w22+3; cs+=1) *rr++ = *cs;
  /* #64: @27 = sq(@26) */
  w27 = casadi_sq( w26 );
  /* #65: @24 = (@24+@27) */
  w24 += w27;
  /* #66: @27 = @22[3] */
  for (rr=(&w27), cs=w22+3; cs!=w22+4; cs+=1) *rr++ = *cs;
  /* #67: @28 = sq(@27) */
  w28 = casadi_sq( w27 );
  /* #68: @24 = (@24+@28) */
  w24 += w28;
  /* #69: @24 = (@21*@24) */
  w24  = (w21*w24);
  /* #70: @4 = (@4+@24) */
  w04 += w24;
  /* #71: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #72: @22 = zeros(4x1) */
  casadi_clear(w22, 4);
  /* #73: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #74: @27 = (@21*@27) */
  w27  = (w21*w27);
  /* #75: (@22[3] += @27) */
  for (rr=w22+3, cs=(&w27); rr!=w22+4; rr+=1) *rr += *cs++;
  /* #76: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #77: @26 = (@21*@26) */
  w26  = (w21*w26);
  /* #78: (@22[2] += @26) */
  for (rr=w22+2, cs=(&w26); rr!=w22+3; rr+=1) *rr += *cs++;
  /* #79: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #80: @25 = (@21*@25) */
  w25  = (w21*w25);
  /* #81: (@22[1] += @25) */
  for (rr=w22+1, cs=(&w25); rr!=w22+2; rr+=1) *rr += *cs++;
  /* #82: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #83: @21 = (@21*@23) */
  w21 *= w23;
  /* #84: (@22[0] += @21) */
  for (rr=w22+0, cs=(&w21); rr!=w22+1; rr+=1) *rr += *cs++;
  /* #85: output[1][0] = @22 */
  casadi_copy(w22, 4, res[1]);
  /* #86: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #87: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #88: @19 = (@19*@13) */
  w19 *= w13;
  /* #89: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #90: @20 = (@14/@20) */
  w20  = (w14/w20);
  /* #91: @17 = (@17*@20) */
  w17 *= w20;
  /* #92: @17 = (@19+@17) */
  w17  = (w19+w17);
  /* #93: (@1[10] += @17) */
  for (rr=w01+10, cs=(&w17); rr!=w01+11; rr+=1) *rr += *cs++;
  /* #94: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #95: @14 = (@14/@18) */
  w14 /= w18;
  /* #96: @16 = (@16*@14) */
  w16 *= w14;
  /* #97: @16 = (@19+@16) */
  w16  = (w19+w16);
  /* #98: (@1[9] += @16) */
  for (rr=w01+9, cs=(&w16); rr!=w01+10; rr+=1) *rr += *cs++;
  /* #99: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #100: @16 = 2 */
  w16 = 2.;
  /* #101: @15 = (@16/@15) */
  w15  = (w16/w15);
  /* #102: @11 = (@11*@15) */
  w11 *= w15;
  /* #103: @11 = (@19+@11) */
  w11  = (w19+w11);
  /* #104: (@1[8] += @11) */
  for (rr=w01+8, cs=(&w11); rr!=w01+9; rr+=1) *rr += *cs++;
  /* #105: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #106: @16 = (@16/@12) */
  w16 /= w12;
  /* #107: @10 = (@10*@16) */
  w10 *= w16;
  /* #108: @19 = (@19+@10) */
  w19 += w10;
  /* #109: (@1[7] += @19) */
  for (rr=w01+7, cs=(&w19); rr!=w01+8; rr+=1) *rr += *cs++;
  /* #110: @19 = (@8<=@7) */
  w19  = (w08<=w07);
  /* #111: @7 = (@7<=@8) */
  w07  = (w07<=w08);
  /* #112: @7 = (@19+@7) */
  w07  = (w19+w07);
  /* #113: @19 = (@19/@7) */
  w19 /= w07;
  /* #114: @7 = (@6/@9) */
  w07  = (w06/w09);
  /* #115: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #116: @5 = (@5*@6) */
  w05 *= w06;
  /* #117: @7 = (@7*@5) */
  w07 *= w05;
  /* #118: @19 = (@19*@7) */
  w19 *= w07;
  /* #119: @19 = (-@19) */
  w19 = (- w19 );
  /* #120: (@1[0] += @19) */
  for (rr=w01+0, cs=(&w19); rr!=w01+1; rr+=1) *rr += *cs++;
  /* #121: @5 = (@5/@9) */
  w05 /= w09;
  /* #122: (@1[1] += @5) */
  for (rr=w01+1, cs=(&w05); rr!=w01+2; rr+=1) *rr += *cs++;
  /* #123: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #124: @0 = (@0*@2) */
  w00 *= w02;
  /* #125: (@1[2] += @0) */
  for (rr=w01+2, cs=(&w00); rr!=w01+3; rr+=1) *rr += *cs++;
  /* #126: output[1][1] = @1 */
  if (res[1]) casadi_copy(w01, 11, res[1]+4);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 49;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 49*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
