/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[9] = 
  {0, 1, 2, 3, 6, 11, 12, 13,
  14};
static const casadi_int casadi_s1[9] = 
  {0, 1, 2, 3, 4, 5, 9, 13,
  17};
static const casadi_int casadi_s2[39] = 
  {15, 15, 0, 1, 2, 3, 4, 4,
  4, 5, 5, 5, 5, 5, 9, 13,
  17, 21, 0, 1, 2, 3, 6, 11,
  12, 13, 14, 11, 12, 13, 14, 11,
  12, 13, 14, 11, 12, 13, 14};
static const casadi_int casadi_s3[3] = {11, 1, 1};
static const casadi_int casadi_s4[3] = {4, 1, 1};
static const casadi_int casadi_s5[3] = {0, 0, 1};
static const casadi_int casadi_s6[3] = {8, 1, 1};
static const casadi_int casadi_s7[3] = {1, 1, 1};
static const casadi_int casadi_s8[3] = {15, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_fun_jac_hess:(i0[11],i1[4],i2[],i3[8])->(o0,o1[15],o2[15x15,21nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, *w01=w+1, w02, *w03=w+13, w04, w05, w06, w07, *w08=w+25, w09, w10;
  casadi_real w11, w12, w13, w14, *w15=w+35, *w16=w+39, *w17=w+50, *w18=w+71, *w19=w+83, *w20=w+98, *w21=w+107;
  const casadi_int *cii;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 500 */
  w00 = 500.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = 30 */
  w05 = 30.;
  /* #9: @6 = @1[7] */
  w06 = wr01[7];
  /* #10: @7 = @1[8] */
  w07 = wr01[8];
  /* #11: @6 = (@6+@7) */
  w06 += w07;
  /* #12: @7 = @1[9] */
  w07 = wr01[9];
  /* #13: @6 = (@6+@7) */
  w06 += w07;
  /* #14: @7 = @1[10] */
  w07 = wr01[10];
  /* #15: @6 = (@6+@7) */
  w06 += w07;
  /* #16: @7 = @3[7] */
  w07 = wr03[7];
  /* #17: @6 = (@6-@7) */
  w06 -= w07;
  /* #18: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #19: @7 = (@5*@7) */
  w07  = (w05*w07);
  /* #20: @4 = (@4+@7) */
  w04 += w07;
  /* #21: @7 = 0.03 */
  w07 = 2.9999999999999999e-02;
  /* #22: @8 = input[1][0] */
  casadi_copy(arg[1], 4, w08);
  /* #23: @9 = @8[0] */
  for (rr=(&w09), cs=w08+0; cs!=w08+1; cs+=1) *rr++ = *cs;
  /* #24: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #25: @11 = @8[1] */
  for (rr=(&w11), cs=w08+1; cs!=w08+2; cs+=1) *rr++ = *cs;
  /* #26: @12 = sq(@11) */
  w12 = casadi_sq( w11 );
  /* #27: @10 = (@10+@12) */
  w10 += w12;
  /* #28: @12 = @8[2] */
  for (rr=(&w12), cs=w08+2; cs!=w08+3; cs+=1) *rr++ = *cs;
  /* #29: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #30: @10 = (@10+@13) */
  w10 += w13;
  /* #31: @13 = @8[3] */
  for (rr=(&w13), cs=w08+3; cs!=w08+4; cs+=1) *rr++ = *cs;
  /* #32: @14 = sq(@13) */
  w14 = casadi_sq( w13 );
  /* #33: @10 = (@10+@14) */
  w10 += w14;
  /* #34: @10 = (@7*@10) */
  w10  = (w07*w10);
  /* #35: @4 = (@4+@10) */
  w04 += w10;
  /* #36: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #37: @8 = zeros(4x1) */
  casadi_clear(w08, 4);
  /* #38: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #39: @13 = (@7*@13) */
  w13  = (w07*w13);
  /* #40: @15 = @8; (@15[3] += @13) */
  casadi_copy(w08, 4, w15);
  for (rr=w15+3, cs=(&w13); rr!=w15+4; rr+=1) *rr += *cs++;
  /* #41: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #42: @12 = (@7*@12) */
  w12  = (w07*w12);
  /* #43: (@15[2] += @12) */
  for (rr=w15+2, cs=(&w12); rr!=w15+3; rr+=1) *rr += *cs++;
  /* #44: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #45: @11 = (@7*@11) */
  w11  = (w07*w11);
  /* #46: (@15[1] += @11) */
  for (rr=w15+1, cs=(&w11); rr!=w15+2; rr+=1) *rr += *cs++;
  /* #47: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #48: @9 = (@7*@9) */
  w09  = (w07*w09);
  /* #49: (@15[0] += @9) */
  for (rr=w15+0, cs=(&w09); rr!=w15+1; rr+=1) *rr += *cs++;
  /* #50: output[1][0] = @15 */
  casadi_copy(w15, 4, res[1]);
  /* #51: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #52: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #53: @6 = (@5*@6) */
  w06  = (w05*w06);
  /* #54: @16 = @1; (@16[10] += @6) */
  casadi_copy(w01, 11, w16);
  for (rr=w16+10, cs=(&w06); rr!=w16+11; rr+=1) *rr += *cs++;
  /* #55: (@16[9] += @6) */
  for (rr=w16+9, cs=(&w06); rr!=w16+10; rr+=1) *rr += *cs++;
  /* #56: (@16[8] += @6) */
  for (rr=w16+8, cs=(&w06); rr!=w16+9; rr+=1) *rr += *cs++;
  /* #57: (@16[7] += @6) */
  for (rr=w16+7, cs=(&w06); rr!=w16+8; rr+=1) *rr += *cs++;
  /* #58: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #59: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #60: (@16[2] += @2) */
  for (rr=w16+2, cs=(&w02); rr!=w16+3; rr+=1) *rr += *cs++;
  /* #61: output[1][1] = @16 */
  if (res[1]) casadi_copy(w16, 11, res[1]+4);
  /* #62: @17 = zeros(15x15,21nz) */
  casadi_clear(w17, 21);
  /* #63: @18 = ones(15x1,12nz) */
  casadi_fill(w18, 12, 1.);
  /* #64: {@15, @3} = vertsplit(@18) */
  casadi_copy(w18, 4, w15);
  casadi_copy(w18+4, 8, w03);
  /* #65: @2 = @15[3] */
  for (rr=(&w02), cs=w15+3; cs!=w15+4; cs+=1) *rr++ = *cs;
  /* #66: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #67: @2 = (@7*@2) */
  w02  = (w07*w02);
  /* #68: (@8[3] += @2) */
  for (rr=w08+3, cs=(&w02); rr!=w08+4; rr+=1) *rr += *cs++;
  /* #69: @2 = @15[2] */
  for (rr=(&w02), cs=w15+2; cs!=w15+3; cs+=1) *rr++ = *cs;
  /* #70: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #71: @2 = (@7*@2) */
  w02  = (w07*w02);
  /* #72: (@8[2] += @2) */
  for (rr=w08+2, cs=(&w02); rr!=w08+3; rr+=1) *rr += *cs++;
  /* #73: @2 = @15[1] */
  for (rr=(&w02), cs=w15+1; cs!=w15+2; cs+=1) *rr++ = *cs;
  /* #74: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #75: @2 = (@7*@2) */
  w02  = (w07*w02);
  /* #76: (@8[1] += @2) */
  for (rr=w08+1, cs=(&w02); rr!=w08+2; rr+=1) *rr += *cs++;
  /* #77: @2 = @15[0] */
  for (rr=(&w02), cs=w15+0; cs!=w15+1; cs+=1) *rr++ = *cs;
  /* #78: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #79: @7 = (@7*@2) */
  w07 *= w02;
  /* #80: (@8[0] += @7) */
  for (rr=w08+0, cs=(&w07); rr!=w08+1; rr+=1) *rr += *cs++;
  /* #81: @7 = @3[7] */
  for (rr=(&w07), cs=w03+7; cs!=w03+8; cs+=1) *rr++ = *cs;
  /* #82: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #83: @7 = (@5*@7) */
  w07  = (w05*w07);
  /* #84: @16 = @1; (@16[10] += @7) */
  casadi_copy(w01, 11, w16);
  for (rr=w16+10, cs=(&w07); rr!=w16+11; rr+=1) *rr += *cs++;
  /* #85: (@16[9] += @7) */
  for (rr=w16+9, cs=(&w07); rr!=w16+10; rr+=1) *rr += *cs++;
  /* #86: (@16[8] += @7) */
  for (rr=w16+8, cs=(&w07); rr!=w16+9; rr+=1) *rr += *cs++;
  /* #87: (@16[7] += @7) */
  for (rr=w16+7, cs=(&w07); rr!=w16+8; rr+=1) *rr += *cs++;
  /* #88: @7 = @3[2] */
  for (rr=(&w07), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #89: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #90: @0 = (@0*@7) */
  w00 *= w07;
  /* #91: (@16[2] += @0) */
  for (rr=w16+2, cs=(&w00); rr!=w16+3; rr+=1) *rr += *cs++;
  /* #92: @19 = vertcat(@8, @16) */
  rr=w19;
  for (i=0, cs=w08; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<11; ++i) *rr++ = *cs++;
  /* #93: @20 = @19[0, 1, 2, 3, 6, 11, 12, 13, 14] */
  for (cii=casadi_s0, rr=w20, cs=w19; cii!=casadi_s0+9; ++cii) *rr++ = cs[*cii];
  /* #94: (@17[:9] = @20) */
  for (rr=w17+0, cs=w20; rr!=w17+9; rr+=1) *rr = *cs++;
  /* #95: (@17[0, 1, 2, 3, 4, 5, 9, 13, 17] = @20) */
  for (cii=casadi_s1, rr=w17, cs=w20; cii!=casadi_s1+9; ++cii, ++cs) rr[*cii] = *cs;
  /* #96: @0 = ones(15x1,1nz) */
  w00 = 1.;
  /* #97: {NULL, @7} = vertsplit(@0) */
  w07 = w00;
  /* #98: @0 = @7[0] */
  for (rr=(&w00), cs=(&w07)+0; cs!=(&w07)+1; cs+=1) *rr++ = *cs;
  /* #99: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #100: @0 = (@5*@0) */
  w00  = (w05*w00);
  /* #101: @16 = @1; (@16[10] += @0) */
  casadi_copy(w01, 11, w16);
  for (rr=w16+10, cs=(&w00); rr!=w16+11; rr+=1) *rr += *cs++;
  /* #102: (@16[9] += @0) */
  for (rr=w16+9, cs=(&w00); rr!=w16+10; rr+=1) *rr += *cs++;
  /* #103: (@16[8] += @0) */
  for (rr=w16+8, cs=(&w00); rr!=w16+9; rr+=1) *rr += *cs++;
  /* #104: (@16[7] += @0) */
  for (rr=w16+7, cs=(&w00); rr!=w16+8; rr+=1) *rr += *cs++;
  /* #105: @8 = @16[7:11] */
  for (rr=w08, cs=w16+7; cs!=w16+11; cs+=1) *rr++ = *cs;
  /* #106: (@17[9:13] = @8) */
  for (rr=w17+9, cs=w08; rr!=w17+13; rr+=1) *rr = *cs++;
  /* #107: (@17[6:22:4] = @8) */
  for (rr=w17+6, cs=w08; rr!=w17+22; rr+=4) *rr = *cs++;
  /* #108: @0 = ones(15x1,1nz) */
  w00 = 1.;
  /* #109: {NULL, @7} = vertsplit(@0) */
  w07 = w00;
  /* #110: @0 = @7[0] */
  for (rr=(&w00), cs=(&w07)+0; cs!=(&w07)+1; cs+=1) *rr++ = *cs;
  /* #111: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #112: @0 = (@5*@0) */
  w00  = (w05*w00);
  /* #113: @16 = @1; (@16[10] += @0) */
  casadi_copy(w01, 11, w16);
  for (rr=w16+10, cs=(&w00); rr!=w16+11; rr+=1) *rr += *cs++;
  /* #114: (@16[9] += @0) */
  for (rr=w16+9, cs=(&w00); rr!=w16+10; rr+=1) *rr += *cs++;
  /* #115: (@16[8] += @0) */
  for (rr=w16+8, cs=(&w00); rr!=w16+9; rr+=1) *rr += *cs++;
  /* #116: (@16[7] += @0) */
  for (rr=w16+7, cs=(&w00); rr!=w16+8; rr+=1) *rr += *cs++;
  /* #117: @8 = @16[7:11] */
  for (rr=w08, cs=w16+7; cs!=w16+11; cs+=1) *rr++ = *cs;
  /* #118: (@17[13:17] = @8) */
  for (rr=w17+13, cs=w08; rr!=w17+17; rr+=1) *rr = *cs++;
  /* #119: (@17[7:23:4] = @8) */
  for (rr=w17+7, cs=w08; rr!=w17+23; rr+=4) *rr = *cs++;
  /* #120: @0 = ones(15x1,1nz) */
  w00 = 1.;
  /* #121: {NULL, @7} = vertsplit(@0) */
  w07 = w00;
  /* #122: @0 = @7[0] */
  for (rr=(&w00), cs=(&w07)+0; cs!=(&w07)+1; cs+=1) *rr++ = *cs;
  /* #123: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #124: @5 = (@5*@0) */
  w05 *= w00;
  /* #125: (@1[10] += @5) */
  for (rr=w01+10, cs=(&w05); rr!=w01+11; rr+=1) *rr += *cs++;
  /* #126: (@1[9] += @5) */
  for (rr=w01+9, cs=(&w05); rr!=w01+10; rr+=1) *rr += *cs++;
  /* #127: (@1[8] += @5) */
  for (rr=w01+8, cs=(&w05); rr!=w01+9; rr+=1) *rr += *cs++;
  /* #128: (@1[7] += @5) */
  for (rr=w01+7, cs=(&w05); rr!=w01+8; rr+=1) *rr += *cs++;
  /* #129: @8 = @1[7:11] */
  for (rr=w08, cs=w01+7; cs!=w01+11; cs+=1) *rr++ = *cs;
  /* #130: (@17[17:21] = @8) */
  for (rr=w17+17, cs=w08; rr!=w17+21; rr+=1) *rr = *cs++;
  /* #131: (@17[8:24:4] = @8) */
  for (rr=w17+8, cs=w08; rr!=w17+24; rr+=4) *rr = *cs++;
  /* #132: @21 = @17' */
  casadi_trans(w17,casadi_s2, w21, casadi_s2, iw);
  /* #133: output[2][0] = @21 */
  casadi_copy(w21, 21, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 16;
  if (sz_w) *sz_w = 128;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 16*sizeof(casadi_int);
  if (sz_w) *sz_w = 128*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
