/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_fun:(i0[11],i1[4],i2[],i3[8])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w0, w2, w4, w5, *w6=w+23;
  const casadi_real *cs, *wr1, *wr3;
  /* #0: @0 = 10000 */
  w0 = 10000.;
  /* #1: @1 = input[0][0] */
  wr1 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w2 = wr1[2];
  /* #3: @3 = input[3][0] */
  wr3 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w4 = wr3[0];
  /* #5: @2 = (@2-@4) */
  w2 -= w4;
  /* #6: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #7: @0 = (@0*@2) */
  w0 *= w2;
  /* #8: @2 = @1[1] */
  w2 = wr1[1];
  /* #9: @4 = 0.25 */
  w4 = 2.5000000000000000e-01;
  /* #10: @5 = @1[0] */
  w5 = wr1[0];
  /* #11: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #12: @4 = (@4+@5) */
  w4 += w5;
  /* #13: @4 = sqrt(@4) */
  w4 = sqrt( w4 );
  /* #14: @2 = (@2/@4) */
  w2 /= w4;
  /* #15: @4 = sq(@2) */
  w4 = casadi_sq( w2 );
  /* #16: @0 = (@0+@4) */
  w0 += w4;
  /* #17: @4 = 400000 */
  w4 = 400000.;
  /* #18: @5 = 4 */
  w5 = 4.;
  /* #19: @2 = pow(@2,@5) */
  w2  = pow(w2,w5);
  /* #20: @4 = (@4*@2) */
  w4 *= w2;
  /* #21: @0 = (@0+@4) */
  w0 += w4;
  /* #22: @4 = 10 */
  w4 = 10.;
  /* #23: @2 = @1[7] */
  w2 = wr1[7];
  /* #24: @5 = @1[8] */
  w5 = wr1[8];
  /* #25: @2 = (@2+@5) */
  w2 += w5;
  /* #26: @5 = @1[9] */
  w5 = wr1[9];
  /* #27: @2 = (@2+@5) */
  w2 += w5;
  /* #28: @5 = @1[10] */
  w5 = wr1[10];
  /* #29: @2 = (@2+@5) */
  w2 += w5;
  /* #30: @5 = @3[7] */
  w5 = wr3[7];
  /* #31: @2 = (@2-@5) */
  w2 -= w5;
  /* #32: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #33: @4 = (@4*@2) */
  w4 *= w2;
  /* #34: @0 = (@0+@4) */
  w0 += w4;
  /* #35: @4 = 0.03 */
  w4 = 2.9999999999999999e-02;
  /* #36: @6 = input[1][0] */
  casadi_copy(arg[1], 4, w6);
  /* #37: @2 = @6[0] */
  for (rr=(&w2), cs=w6+0; cs!=w6+1; cs+=1) *rr++ = *cs;
  /* #38: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #39: @5 = @6[1] */
  for (rr=(&w5), cs=w6+1; cs!=w6+2; cs+=1) *rr++ = *cs;
  /* #40: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #41: @2 = (@2+@5) */
  w2 += w5;
  /* #42: @5 = @6[2] */
  for (rr=(&w5), cs=w6+2; cs!=w6+3; cs+=1) *rr++ = *cs;
  /* #43: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #44: @2 = (@2+@5) */
  w2 += w5;
  /* #45: @5 = @6[3] */
  for (rr=(&w5), cs=w6+3; cs!=w6+4; cs+=1) *rr++ = *cs;
  /* #46: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #47: @2 = (@2+@5) */
  w2 += w5;
  /* #48: @4 = (@4*@2) */
  w4 *= w2;
  /* #49: @0 = (@0+@4) */
  w0 += w4;
  /* #50: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 27;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 27*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
