/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = 
  {0, 1, 2, 3, 4, 5, 6, 11,
  12, 13, 14};
static const casadi_int casadi_s1[11] = 
  {0, 1, 2, 3, 4, 5, 8, 9,
  10, 11, 12};
static const casadi_int casadi_s2[11] = 
  {0, 1, 2, 3, 4, 6, 8, 9,
  13, 17, 21};
static const casadi_int casadi_s3[6] = {0, 1, 7, 8, 9, 10};
static const casadi_int casadi_s4[6] = {6, 7, 13, 14, 15, 16};
static const casadi_int casadi_s5[6] = {5, 7, 10, 14, 18, 22};
static const casadi_int casadi_s6[43] = 
  {15, 15, 0, 1, 2, 3, 4, 6,
  8, 9, 9, 9, 9, 9, 13, 17,
  21, 25, 0, 1, 2, 3, 4, 5,
  4, 5, 6, 11, 12, 13, 14, 11,
  12, 13, 14, 11, 12, 13, 14, 11,
  12, 13, 14};
static const casadi_int casadi_s7[3] = {11, 1, 1};
static const casadi_int casadi_s8[3] = {4, 1, 1};
static const casadi_int casadi_s9[3] = {0, 0, 1};
static const casadi_int casadi_s10[3] = {8, 1, 1};
static const casadi_int casadi_s11[3] = {1, 1, 1};
static const casadi_int casadi_s12[3] = {15, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_fun_jac_hess:(i0[11],i1[4],i2[],i3[8])->(o0,o1[15],o2[15x15,25nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, *w01=w+1, w02, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, *w17=w+34, w18, w19, w20, w21, w22, w23;
  casadi_real *w24=w+44, *w25=w+48, *w26=w+59, *w27=w+84, *w28=w+91, *w29=w+106, *w30=w+108, *w31=w+110, *w32=w+116;
  const casadi_int *cii;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 18 */
  w00 = 18.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = 50000 */
  w05 = 50000.;
  /* #9: @6 = @1[1] */
  w06 = wr01[1];
  /* #10: @7 = 0.001 */
  w07 = 1.0000000000000000e-03;
  /* #11: @8 = @1[0] */
  w08 = wr01[0];
  /* #12: @7 = (@7+@8) */
  w07 += w08;
  /* #13: @8 = atan2(@6,@7) */
  w08  = atan2(w06,w07);
  /* #14: @9 = sq(@8) */
  w09 = casadi_sq( w08 );
  /* #15: @9 = (@5*@9) */
  w09  = (w05*w09);
  /* #16: @4 = (@4+@9) */
  w04 += w09;
  /* #17: @9 = 0.1 */
  w09 = 1.0000000000000001e-01;
  /* #18: @10 = @1[7] */
  w10 = wr01[7];
  /* #19: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #20: @12 = @1[8] */
  w12 = wr01[8];
  /* #21: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #22: @11 = (@11+@13) */
  w11 += w13;
  /* #23: @13 = @1[9] */
  w13 = wr01[9];
  /* #24: @14 = sq(@13) */
  w14 = casadi_sq( w13 );
  /* #25: @11 = (@11+@14) */
  w11 += w14;
  /* #26: @14 = @1[10] */
  w14 = wr01[10];
  /* #27: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #28: @11 = (@11+@15) */
  w11 += w15;
  /* #29: @11 = (@9*@11) */
  w11  = (w09*w11);
  /* #30: @4 = (@4+@11) */
  w04 += w11;
  /* #31: @11 = 30 */
  w11 = 30.;
  /* #32: @15 = (@10+@12) */
  w15  = (w10+w12);
  /* #33: @15 = (@15+@13) */
  w15 += w13;
  /* #34: @15 = (@15+@14) */
  w15 += w14;
  /* #35: @16 = @3[7] */
  w16 = wr03[7];
  /* #36: @15 = (@15-@16) */
  w15 -= w16;
  /* #37: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #38: @16 = (@11*@16) */
  w16  = (w11*w16);
  /* #39: @4 = (@4+@16) */
  w04 += w16;
  /* #40: @16 = 0.09 */
  w16 = 8.9999999999999997e-02;
  /* #41: @17 = input[1][0] */
  casadi_copy(arg[1], 4, w17);
  /* #42: @18 = @17[0] */
  for (rr=(&w18), cs=w17+0; cs!=w17+1; cs+=1) *rr++ = *cs;
  /* #43: @19 = sq(@18) */
  w19 = casadi_sq( w18 );
  /* #44: @20 = @17[1] */
  for (rr=(&w20), cs=w17+1; cs!=w17+2; cs+=1) *rr++ = *cs;
  /* #45: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #46: @19 = (@19+@21) */
  w19 += w21;
  /* #47: @21 = @17[2] */
  for (rr=(&w21), cs=w17+2; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #48: @22 = sq(@21) */
  w22 = casadi_sq( w21 );
  /* #49: @19 = (@19+@22) */
  w19 += w22;
  /* #50: @22 = @17[3] */
  for (rr=(&w22), cs=w17+3; cs!=w17+4; cs+=1) *rr++ = *cs;
  /* #51: @23 = sq(@22) */
  w23 = casadi_sq( w22 );
  /* #52: @19 = (@19+@23) */
  w19 += w23;
  /* #53: @19 = (@16*@19) */
  w19  = (w16*w19);
  /* #54: @4 = (@4+@19) */
  w04 += w19;
  /* #55: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #56: @17 = zeros(4x1) */
  casadi_clear(w17, 4);
  /* #57: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #58: @22 = (@16*@22) */
  w22  = (w16*w22);
  /* #59: @24 = @17; (@24[3] += @22) */
  casadi_copy(w17, 4, w24);
  for (rr=w24+3, cs=(&w22); rr!=w24+4; rr+=1) *rr += *cs++;
  /* #60: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #61: @21 = (@16*@21) */
  w21  = (w16*w21);
  /* #62: (@24[2] += @21) */
  for (rr=w24+2, cs=(&w21); rr!=w24+3; rr+=1) *rr += *cs++;
  /* #63: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #64: @20 = (@16*@20) */
  w20  = (w16*w20);
  /* #65: (@24[1] += @20) */
  for (rr=w24+1, cs=(&w20); rr!=w24+2; rr+=1) *rr += *cs++;
  /* #66: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #67: @18 = (@16*@18) */
  w18  = (w16*w18);
  /* #68: (@24[0] += @18) */
  for (rr=w24+0, cs=(&w18); rr!=w24+1; rr+=1) *rr += *cs++;
  /* #69: output[1][0] = @24 */
  casadi_copy(w24, 4, res[1]);
  /* #70: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #71: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #72: @15 = (@11*@15) */
  w15  = (w11*w15);
  /* #73: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #74: @14 = (@9*@14) */
  w14  = (w09*w14);
  /* #75: @14 = (@15+@14) */
  w14  = (w15+w14);
  /* #76: @25 = @1; (@25[10] += @14) */
  casadi_copy(w01, 11, w25);
  for (rr=w25+10, cs=(&w14); rr!=w25+11; rr+=1) *rr += *cs++;
  /* #77: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #78: @13 = (@9*@13) */
  w13  = (w09*w13);
  /* #79: @13 = (@15+@13) */
  w13  = (w15+w13);
  /* #80: (@25[9] += @13) */
  for (rr=w25+9, cs=(&w13); rr!=w25+10; rr+=1) *rr += *cs++;
  /* #81: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #82: @12 = (@9*@12) */
  w12  = (w09*w12);
  /* #83: @12 = (@15+@12) */
  w12  = (w15+w12);
  /* #84: (@25[8] += @12) */
  for (rr=w25+8, cs=(&w12); rr!=w25+9; rr+=1) *rr += *cs++;
  /* #85: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #86: @10 = (@9*@10) */
  w10  = (w09*w10);
  /* #87: @15 = (@15+@10) */
  w15 += w10;
  /* #88: (@25[7] += @15) */
  for (rr=w25+7, cs=(&w15); rr!=w25+8; rr+=1) *rr += *cs++;
  /* #89: @15 = sq(@6) */
  w15 = casadi_sq( w06 );
  /* #90: @10 = sq(@7) */
  w10 = casadi_sq( w07 );
  /* #91: @15 = (@15+@10) */
  w15 += w10;
  /* #92: @10 = (@6/@15) */
  w10  = (w06/w15);
  /* #93: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #94: @8 = (@5*@8) */
  w08  = (w05*w08);
  /* #95: @12 = (@10*@8) */
  w12  = (w10*w08);
  /* #96: @12 = (-@12) */
  w12 = (- w12 );
  /* #97: (@25[0] += @12) */
  for (rr=w25+0, cs=(&w12); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #98: @12 = (@7/@15) */
  w12  = (w07/w15);
  /* #99: @13 = (@12*@8) */
  w13  = (w12*w08);
  /* #100: (@25[1] += @13) */
  for (rr=w25+1, cs=(&w13); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #101: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #102: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #103: (@25[2] += @2) */
  for (rr=w25+2, cs=(&w02); rr!=w25+3; rr+=1) *rr += *cs++;
  /* #104: output[1][1] = @25 */
  if (res[1]) casadi_copy(w25, 11, res[1]+4);
  /* #105: @26 = zeros(15x15,25nz) */
  casadi_clear(w26, 25);
  /* #106: @25 = ones(15x1,11nz) */
  casadi_fill(w25, 11, 1.);
  /* #107: {@24, @27} = vertsplit(@25) */
  casadi_copy(w25, 4, w24);
  casadi_copy(w25+4, 7, w27);
  /* #108: @2 = @24[3] */
  for (rr=(&w02), cs=w24+3; cs!=w24+4; cs+=1) *rr++ = *cs;
  /* #109: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #110: @2 = (@16*@2) */
  w02  = (w16*w02);
  /* #111: (@17[3] += @2) */
  for (rr=w17+3, cs=(&w02); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #112: @2 = @24[2] */
  for (rr=(&w02), cs=w24+2; cs!=w24+3; cs+=1) *rr++ = *cs;
  /* #113: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #114: @2 = (@16*@2) */
  w02  = (w16*w02);
  /* #115: (@17[2] += @2) */
  for (rr=w17+2, cs=(&w02); rr!=w17+3; rr+=1) *rr += *cs++;
  /* #116: @2 = @24[1] */
  for (rr=(&w02), cs=w24+1; cs!=w24+2; cs+=1) *rr++ = *cs;
  /* #117: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #118: @2 = (@16*@2) */
  w02  = (w16*w02);
  /* #119: (@17[1] += @2) */
  for (rr=w17+1, cs=(&w02); rr!=w17+2; rr+=1) *rr += *cs++;
  /* #120: @2 = @24[0] */
  for (rr=(&w02), cs=w24+0; cs!=w24+1; cs+=1) *rr++ = *cs;
  /* #121: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #122: @16 = (@16*@2) */
  w16 *= w02;
  /* #123: (@17[0] += @16) */
  for (rr=w17+0, cs=(&w16); rr!=w17+1; rr+=1) *rr += *cs++;
  /* #124: @16 = @27[6] */
  for (rr=(&w16), cs=w27+6; cs!=w27+7; cs+=1) *rr++ = *cs;
  /* #125: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #126: @2 = (@11*@16) */
  w02  = (w11*w16);
  /* #127: @25 = @1; (@25[10] += @2) */
  casadi_copy(w01, 11, w25);
  for (rr=w25+10, cs=(&w02); rr!=w25+11; rr+=1) *rr += *cs++;
  /* #128: (@25[9] += @2) */
  for (rr=w25+9, cs=(&w02); rr!=w25+10; rr+=1) *rr += *cs++;
  /* #129: (@25[8] += @2) */
  for (rr=w25+8, cs=(&w02); rr!=w25+9; rr+=1) *rr += *cs++;
  /* #130: @16 = (@9*@16) */
  w16  = (w09*w16);
  /* #131: @2 = (@2+@16) */
  w02 += w16;
  /* #132: (@25[7] += @2) */
  for (rr=w25+7, cs=(&w02); rr!=w25+8; rr+=1) *rr += *cs++;
  /* #133: @2 = @27[0] */
  for (rr=(&w02), cs=w27+0; cs!=w27+1; cs+=1) *rr++ = *cs;
  /* #134: @16 = (@10*@2) */
  w16  = (w10*w02);
  /* #135: @16 = (-@16) */
  w16 = (- w16 );
  /* #136: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #137: @16 = (@5*@16) */
  w16  = (w05*w16);
  /* #138: @13 = (@10*@16) */
  w13  = (w10*w16);
  /* #139: @14 = (@10/@15) */
  w14  = (w10/w15);
  /* #140: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #141: @7 = (@7*@2) */
  w07 *= w02;
  /* #142: @18 = (@14*@7) */
  w18  = (w14*w07);
  /* #143: @18 = (@8*@18) */
  w18  = (w08*w18);
  /* #144: @13 = (@13-@18) */
  w13 -= w18;
  /* #145: @13 = (-@13) */
  w13 = (- w13 );
  /* #146: (@25[0] += @13) */
  for (rr=w25+0, cs=(&w13); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #147: @2 = (@2/@15) */
  w02 /= w15;
  /* #148: @13 = (@12/@15) */
  w13  = (w12/w15);
  /* #149: @7 = (@13*@7) */
  w07  = (w13*w07);
  /* #150: @2 = (@2-@7) */
  w02 -= w07;
  /* #151: @2 = (@8*@2) */
  w02  = (w08*w02);
  /* #152: @16 = (@12*@16) */
  w16  = (w12*w16);
  /* #153: @2 = (@2+@16) */
  w02 += w16;
  /* #154: (@25[1] += @2) */
  for (rr=w25+1, cs=(&w02); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #155: @2 = @27[1] */
  for (rr=(&w02), cs=w27+1; cs!=w27+2; cs+=1) *rr++ = *cs;
  /* #156: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #157: @0 = (@0*@2) */
  w00 *= w02;
  /* #158: (@25[2] += @0) */
  for (rr=w25+2, cs=(&w00); rr!=w25+3; rr+=1) *rr += *cs++;
  /* #159: @28 = vertcat(@17, @25) */
  rr=w28;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<11; ++i) *rr++ = *cs++;
  /* #160: @25 = @28[0, 1, 2, 3, 4, 5, 6, 11, 12, 13, 14] */
  for (cii=casadi_s0, rr=w25, cs=w28; cii!=casadi_s0+11; ++cii) *rr++ = cs[*cii];
  /* #161: (@26[0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12] = @25) */
  for (cii=casadi_s1, rr=w26, cs=w25; cii!=casadi_s1+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #162: (@26[0, 1, 2, 3, 4, 6, 8, 9, 13, 17, 21] = @25) */
  for (cii=casadi_s2, rr=w26, cs=w25; cii!=casadi_s2+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #163: @29 = ones(15x1,2nz) */
  casadi_fill(w29, 2, 1.);
  /* #164: {NULL, @30} = vertsplit(@29) */
  casadi_copy(w29, 2, w30);
  /* #165: @0 = @30[1] */
  for (rr=(&w00), cs=w30+1; cs!=w30+2; cs+=1) *rr++ = *cs;
  /* #166: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #167: @2 = (@11*@0) */
  w02  = (w11*w00);
  /* #168: @25 = @1; (@25[10] += @2) */
  casadi_copy(w01, 11, w25);
  for (rr=w25+10, cs=(&w02); rr!=w25+11; rr+=1) *rr += *cs++;
  /* #169: (@25[9] += @2) */
  for (rr=w25+9, cs=(&w02); rr!=w25+10; rr+=1) *rr += *cs++;
  /* #170: @0 = (@9*@0) */
  w00  = (w09*w00);
  /* #171: @0 = (@2+@0) */
  w00  = (w02+w00);
  /* #172: (@25[8] += @0) */
  for (rr=w25+8, cs=(&w00); rr!=w25+9; rr+=1) *rr += *cs++;
  /* #173: (@25[7] += @2) */
  for (rr=w25+7, cs=(&w02); rr!=w25+8; rr+=1) *rr += *cs++;
  /* #174: @2 = @30[0] */
  for (rr=(&w02), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #175: @15 = (@2/@15) */
  w15  = (w02/w15);
  /* #176: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #177: @6 = (@6*@2) */
  w06 *= w02;
  /* #178: @14 = (@14*@6) */
  w14 *= w06;
  /* #179: @15 = (@15-@14) */
  w15 -= w14;
  /* #180: @15 = (@8*@15) */
  w15  = (w08*w15);
  /* #181: @2 = (@12*@2) */
  w02  = (w12*w02);
  /* #182: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #183: @5 = (@5*@2) */
  w05 *= w02;
  /* #184: @10 = (@10*@5) */
  w10 *= w05;
  /* #185: @15 = (@15+@10) */
  w15 += w10;
  /* #186: @15 = (-@15) */
  w15 = (- w15 );
  /* #187: (@25[0] += @15) */
  for (rr=w25+0, cs=(&w15); rr!=w25+1; rr+=1) *rr += *cs++;
  /* #188: @12 = (@12*@5) */
  w12 *= w05;
  /* #189: @13 = (@13*@6) */
  w13 *= w06;
  /* #190: @8 = (@8*@13) */
  w08 *= w13;
  /* #191: @12 = (@12-@8) */
  w12 -= w08;
  /* #192: (@25[1] += @12) */
  for (rr=w25+1, cs=(&w12); rr!=w25+2; rr+=1) *rr += *cs++;
  /* #193: @31 = @25[0, 1, 7, 8, 9, 10] */
  for (cii=casadi_s3, rr=w31, cs=w25; cii!=casadi_s3+6; ++cii) *rr++ = cs[*cii];
  /* #194: (@26[6, 7, 13, 14, 15, 16] = @31) */
  for (cii=casadi_s4, rr=w26, cs=w31; cii!=casadi_s4+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #195: (@26[5, 7, 10, 14, 18, 22] = @31) */
  for (cii=casadi_s5, rr=w26, cs=w31; cii!=casadi_s5+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #196: @12 = ones(15x1,1nz) */
  w12 = 1.;
  /* #197: {NULL, @8} = vertsplit(@12) */
  w08 = w12;
  /* #198: @12 = @8[0] */
  for (rr=(&w12), cs=(&w08)+0; cs!=(&w08)+1; cs+=1) *rr++ = *cs;
  /* #199: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #200: @8 = (@11*@12) */
  w08  = (w11*w12);
  /* #201: @25 = @1; (@25[10] += @8) */
  casadi_copy(w01, 11, w25);
  for (rr=w25+10, cs=(&w08); rr!=w25+11; rr+=1) *rr += *cs++;
  /* #202: @12 = (@9*@12) */
  w12  = (w09*w12);
  /* #203: @12 = (@8+@12) */
  w12  = (w08+w12);
  /* #204: (@25[9] += @12) */
  for (rr=w25+9, cs=(&w12); rr!=w25+10; rr+=1) *rr += *cs++;
  /* #205: (@25[8] += @8) */
  for (rr=w25+8, cs=(&w08); rr!=w25+9; rr+=1) *rr += *cs++;
  /* #206: (@25[7] += @8) */
  for (rr=w25+7, cs=(&w08); rr!=w25+8; rr+=1) *rr += *cs++;
  /* #207: @17 = @25[7:11] */
  for (rr=w17, cs=w25+7; cs!=w25+11; cs+=1) *rr++ = *cs;
  /* #208: (@26[17:21] = @17) */
  for (rr=w26+17, cs=w17; rr!=w26+21; rr+=1) *rr = *cs++;
  /* #209: (@26[11:27:4] = @17) */
  for (rr=w26+11, cs=w17; rr!=w26+27; rr+=4) *rr = *cs++;
  /* #210: @8 = ones(15x1,1nz) */
  w08 = 1.;
  /* #211: {NULL, @12} = vertsplit(@8) */
  w12 = w08;
  /* #212: @8 = @12[0] */
  for (rr=(&w08), cs=(&w12)+0; cs!=(&w12)+1; cs+=1) *rr++ = *cs;
  /* #213: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #214: @11 = (@11*@8) */
  w11 *= w08;
  /* #215: @9 = (@9*@8) */
  w09 *= w08;
  /* #216: @9 = (@11+@9) */
  w09  = (w11+w09);
  /* #217: (@1[10] += @9) */
  for (rr=w01+10, cs=(&w09); rr!=w01+11; rr+=1) *rr += *cs++;
  /* #218: (@1[9] += @11) */
  for (rr=w01+9, cs=(&w11); rr!=w01+10; rr+=1) *rr += *cs++;
  /* #219: (@1[8] += @11) */
  for (rr=w01+8, cs=(&w11); rr!=w01+9; rr+=1) *rr += *cs++;
  /* #220: (@1[7] += @11) */
  for (rr=w01+7, cs=(&w11); rr!=w01+8; rr+=1) *rr += *cs++;
  /* #221: @17 = @1[7:11] */
  for (rr=w17, cs=w01+7; cs!=w01+11; cs+=1) *rr++ = *cs;
  /* #222: (@26[21:25] = @17) */
  for (rr=w26+21, cs=w17; rr!=w26+25; rr+=1) *rr = *cs++;
  /* #223: (@26[12:28:4] = @17) */
  for (rr=w26+12, cs=w17; rr!=w26+28; rr+=4) *rr = *cs++;
  /* #224: @32 = @26' */
  casadi_trans(w26,casadi_s6, w32, casadi_s6, iw);
  /* #225: output[2][0] = @32 */
  casadi_copy(w32, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    case 3: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s12;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 16;
  if (sz_w) *sz_w = 141;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 16*sizeof(casadi_int);
  if (sz_w) *sz_w = 141*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
