/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = 
  {0, 1, 2, 3, 4, 5, 6, 11,
  12, 13, 14};
static const casadi_int casadi_s1[11] = 
  {0, 1, 2, 3, 4, 5, 8, 9,
  10, 11, 12};
static const casadi_int casadi_s2[11] = 
  {0, 1, 2, 3, 4, 6, 8, 9,
  13, 17, 21};
static const casadi_int casadi_s3[6] = {0, 1, 7, 8, 9, 10};
static const casadi_int casadi_s4[6] = {6, 7, 13, 14, 15, 16};
static const casadi_int casadi_s5[6] = {5, 7, 10, 14, 18, 22};
static const casadi_int casadi_s6[43] = 
  {15, 15, 0, 1, 2, 3, 4, 6,
  8, 9, 9, 9, 9, 9, 13, 17,
  21, 25, 0, 1, 2, 3, 4, 5,
  4, 5, 6, 11, 12, 13, 14, 11,
  12, 13, 14, 11, 12, 13, 14, 11,
  12, 13, 14};
static const casadi_int casadi_s7[3] = {11, 1, 1};
static const casadi_int casadi_s8[3] = {4, 1, 1};
static const casadi_int casadi_s9[3] = {0, 0, 1};
static const casadi_int casadi_s10[3] = {8, 1, 1};
static const casadi_int casadi_s11[3] = {1, 1, 1};
static const casadi_int casadi_s12[3] = {15, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_0_fun_jac_hess:(i0[11],i1[4],i2[],i3[8])->(o0,o1[15],o2[15x15,25nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, *w01=w+1, w02, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, *w17=w+34, w18, w19, w20, w21, w22, *w23=w+43;
  casadi_real *w24=w+47, *w25=w+58, *w26=w+83, *w27=w+90, *w28=w+105, *w29=w+107, *w30=w+109, *w31=w+115;
  const casadi_int *cii;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 200 */
  w00 = 200.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = 0.1 */
  w05 = 1.0000000000000001e-01;
  /* #9: @6 = @1[1] */
  w06 = wr01[1];
  /* #10: @7 = 0.001 */
  w07 = 1.0000000000000000e-03;
  /* #11: @8 = @1[0] */
  w08 = wr01[0];
  /* #12: @8 = (@7+@8) */
  w08  = (w07+w08);
  /* #13: @9 = atan2(@6,@8) */
  w09  = atan2(w06,w08);
  /* #14: @10 = sq(@9) */
  w10 = casadi_sq( w09 );
  /* #15: @10 = (@5*@10) */
  w10  = (w05*w10);
  /* #16: @4 = (@4+@10) */
  w04 += w10;
  /* #17: @10 = @1[7] */
  w10 = wr01[7];
  /* #18: @11 = sq(@10) */
  w11 = casadi_sq( w10 );
  /* #19: @12 = @1[8] */
  w12 = wr01[8];
  /* #20: @13 = sq(@12) */
  w13 = casadi_sq( w12 );
  /* #21: @11 = (@11+@13) */
  w11 += w13;
  /* #22: @13 = @1[9] */
  w13 = wr01[9];
  /* #23: @14 = sq(@13) */
  w14 = casadi_sq( w13 );
  /* #24: @11 = (@11+@14) */
  w11 += w14;
  /* #25: @14 = @1[10] */
  w14 = wr01[10];
  /* #26: @15 = sq(@14) */
  w15 = casadi_sq( w14 );
  /* #27: @11 = (@11+@15) */
  w11 += w15;
  /* #28: @11 = (@5*@11) */
  w11  = (w05*w11);
  /* #29: @4 = (@4+@11) */
  w04 += w11;
  /* #30: @11 = 0.5 */
  w11 = 5.0000000000000000e-01;
  /* #31: @15 = (@10+@12) */
  w15  = (w10+w12);
  /* #32: @15 = (@15+@13) */
  w15 += w13;
  /* #33: @15 = (@15+@14) */
  w15 += w14;
  /* #34: @16 = @3[7] */
  w16 = wr03[7];
  /* #35: @15 = (@15-@16) */
  w15 -= w16;
  /* #36: @16 = sq(@15) */
  w16 = casadi_sq( w15 );
  /* #37: @16 = (@11*@16) */
  w16  = (w11*w16);
  /* #38: @4 = (@4+@16) */
  w04 += w16;
  /* #39: @17 = input[1][0] */
  casadi_copy(arg[1], 4, w17);
  /* #40: @16 = @17[0] */
  for (rr=(&w16), cs=w17+0; cs!=w17+1; cs+=1) *rr++ = *cs;
  /* #41: @18 = sq(@16) */
  w18 = casadi_sq( w16 );
  /* #42: @19 = @17[1] */
  for (rr=(&w19), cs=w17+1; cs!=w17+2; cs+=1) *rr++ = *cs;
  /* #43: @20 = sq(@19) */
  w20 = casadi_sq( w19 );
  /* #44: @18 = (@18+@20) */
  w18 += w20;
  /* #45: @20 = @17[2] */
  for (rr=(&w20), cs=w17+2; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #46: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #47: @18 = (@18+@21) */
  w18 += w21;
  /* #48: @21 = @17[3] */
  for (rr=(&w21), cs=w17+3; cs!=w17+4; cs+=1) *rr++ = *cs;
  /* #49: @22 = sq(@21) */
  w22 = casadi_sq( w21 );
  /* #50: @18 = (@18+@22) */
  w18 += w22;
  /* #51: @18 = (@7*@18) */
  w18  = (w07*w18);
  /* #52: @4 = (@4+@18) */
  w04 += w18;
  /* #53: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #54: @17 = zeros(4x1) */
  casadi_clear(w17, 4);
  /* #55: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #56: @21 = (@7*@21) */
  w21  = (w07*w21);
  /* #57: @23 = @17; (@23[3] += @21) */
  casadi_copy(w17, 4, w23);
  for (rr=w23+3, cs=(&w21); rr!=w23+4; rr+=1) *rr += *cs++;
  /* #58: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #59: @20 = (@7*@20) */
  w20  = (w07*w20);
  /* #60: (@23[2] += @20) */
  for (rr=w23+2, cs=(&w20); rr!=w23+3; rr+=1) *rr += *cs++;
  /* #61: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #62: @19 = (@7*@19) */
  w19  = (w07*w19);
  /* #63: (@23[1] += @19) */
  for (rr=w23+1, cs=(&w19); rr!=w23+2; rr+=1) *rr += *cs++;
  /* #64: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #65: @16 = (@7*@16) */
  w16  = (w07*w16);
  /* #66: (@23[0] += @16) */
  for (rr=w23+0, cs=(&w16); rr!=w23+1; rr+=1) *rr += *cs++;
  /* #67: output[1][0] = @23 */
  casadi_copy(w23, 4, res[1]);
  /* #68: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #69: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #70: @15 = (@11*@15) */
  w15  = (w11*w15);
  /* #71: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #72: @14 = (@5*@14) */
  w14  = (w05*w14);
  /* #73: @14 = (@15+@14) */
  w14  = (w15+w14);
  /* #74: @24 = @1; (@24[10] += @14) */
  casadi_copy(w01, 11, w24);
  for (rr=w24+10, cs=(&w14); rr!=w24+11; rr+=1) *rr += *cs++;
  /* #75: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #76: @13 = (@5*@13) */
  w13  = (w05*w13);
  /* #77: @13 = (@15+@13) */
  w13  = (w15+w13);
  /* #78: (@24[9] += @13) */
  for (rr=w24+9, cs=(&w13); rr!=w24+10; rr+=1) *rr += *cs++;
  /* #79: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #80: @12 = (@5*@12) */
  w12  = (w05*w12);
  /* #81: @12 = (@15+@12) */
  w12  = (w15+w12);
  /* #82: (@24[8] += @12) */
  for (rr=w24+8, cs=(&w12); rr!=w24+9; rr+=1) *rr += *cs++;
  /* #83: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #84: @10 = (@5*@10) */
  w10  = (w05*w10);
  /* #85: @15 = (@15+@10) */
  w15 += w10;
  /* #86: (@24[7] += @15) */
  for (rr=w24+7, cs=(&w15); rr!=w24+8; rr+=1) *rr += *cs++;
  /* #87: @15 = sq(@6) */
  w15 = casadi_sq( w06 );
  /* #88: @10 = sq(@8) */
  w10 = casadi_sq( w08 );
  /* #89: @15 = (@15+@10) */
  w15 += w10;
  /* #90: @10 = (@6/@15) */
  w10  = (w06/w15);
  /* #91: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #92: @9 = (@5*@9) */
  w09  = (w05*w09);
  /* #93: @12 = (@10*@9) */
  w12  = (w10*w09);
  /* #94: @12 = (-@12) */
  w12 = (- w12 );
  /* #95: (@24[0] += @12) */
  for (rr=w24+0, cs=(&w12); rr!=w24+1; rr+=1) *rr += *cs++;
  /* #96: @12 = (@8/@15) */
  w12  = (w08/w15);
  /* #97: @13 = (@12*@9) */
  w13  = (w12*w09);
  /* #98: (@24[1] += @13) */
  for (rr=w24+1, cs=(&w13); rr!=w24+2; rr+=1) *rr += *cs++;
  /* #99: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #100: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #101: (@24[2] += @2) */
  for (rr=w24+2, cs=(&w02); rr!=w24+3; rr+=1) *rr += *cs++;
  /* #102: output[1][1] = @24 */
  if (res[1]) casadi_copy(w24, 11, res[1]+4);
  /* #103: @25 = zeros(15x15,25nz) */
  casadi_clear(w25, 25);
  /* #104: @24 = ones(15x1,11nz) */
  casadi_fill(w24, 11, 1.);
  /* #105: {@23, @26} = vertsplit(@24) */
  casadi_copy(w24, 4, w23);
  casadi_copy(w24+4, 7, w26);
  /* #106: @2 = @23[3] */
  for (rr=(&w02), cs=w23+3; cs!=w23+4; cs+=1) *rr++ = *cs;
  /* #107: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #108: @2 = (@7*@2) */
  w02  = (w07*w02);
  /* #109: (@17[3] += @2) */
  for (rr=w17+3, cs=(&w02); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #110: @2 = @23[2] */
  for (rr=(&w02), cs=w23+2; cs!=w23+3; cs+=1) *rr++ = *cs;
  /* #111: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #112: @2 = (@7*@2) */
  w02  = (w07*w02);
  /* #113: (@17[2] += @2) */
  for (rr=w17+2, cs=(&w02); rr!=w17+3; rr+=1) *rr += *cs++;
  /* #114: @2 = @23[1] */
  for (rr=(&w02), cs=w23+1; cs!=w23+2; cs+=1) *rr++ = *cs;
  /* #115: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #116: @2 = (@7*@2) */
  w02  = (w07*w02);
  /* #117: (@17[1] += @2) */
  for (rr=w17+1, cs=(&w02); rr!=w17+2; rr+=1) *rr += *cs++;
  /* #118: @2 = @23[0] */
  for (rr=(&w02), cs=w23+0; cs!=w23+1; cs+=1) *rr++ = *cs;
  /* #119: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #120: @7 = (@7*@2) */
  w07 *= w02;
  /* #121: (@17[0] += @7) */
  for (rr=w17+0, cs=(&w07); rr!=w17+1; rr+=1) *rr += *cs++;
  /* #122: @7 = @26[6] */
  for (rr=(&w07), cs=w26+6; cs!=w26+7; cs+=1) *rr++ = *cs;
  /* #123: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #124: @2 = (@11*@7) */
  w02  = (w11*w07);
  /* #125: @24 = @1; (@24[10] += @2) */
  casadi_copy(w01, 11, w24);
  for (rr=w24+10, cs=(&w02); rr!=w24+11; rr+=1) *rr += *cs++;
  /* #126: (@24[9] += @2) */
  for (rr=w24+9, cs=(&w02); rr!=w24+10; rr+=1) *rr += *cs++;
  /* #127: (@24[8] += @2) */
  for (rr=w24+8, cs=(&w02); rr!=w24+9; rr+=1) *rr += *cs++;
  /* #128: @7 = (@5*@7) */
  w07  = (w05*w07);
  /* #129: @2 = (@2+@7) */
  w02 += w07;
  /* #130: (@24[7] += @2) */
  for (rr=w24+7, cs=(&w02); rr!=w24+8; rr+=1) *rr += *cs++;
  /* #131: @2 = @26[0] */
  for (rr=(&w02), cs=w26+0; cs!=w26+1; cs+=1) *rr++ = *cs;
  /* #132: @7 = (@10*@2) */
  w07  = (w10*w02);
  /* #133: @7 = (-@7) */
  w07 = (- w07 );
  /* #134: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #135: @7 = (@5*@7) */
  w07  = (w05*w07);
  /* #136: @13 = (@10*@7) */
  w13  = (w10*w07);
  /* #137: @14 = (@10/@15) */
  w14  = (w10/w15);
  /* #138: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #139: @8 = (@8*@2) */
  w08 *= w02;
  /* #140: @16 = (@14*@8) */
  w16  = (w14*w08);
  /* #141: @16 = (@9*@16) */
  w16  = (w09*w16);
  /* #142: @13 = (@13-@16) */
  w13 -= w16;
  /* #143: @13 = (-@13) */
  w13 = (- w13 );
  /* #144: (@24[0] += @13) */
  for (rr=w24+0, cs=(&w13); rr!=w24+1; rr+=1) *rr += *cs++;
  /* #145: @2 = (@2/@15) */
  w02 /= w15;
  /* #146: @13 = (@12/@15) */
  w13  = (w12/w15);
  /* #147: @8 = (@13*@8) */
  w08  = (w13*w08);
  /* #148: @2 = (@2-@8) */
  w02 -= w08;
  /* #149: @2 = (@9*@2) */
  w02  = (w09*w02);
  /* #150: @7 = (@12*@7) */
  w07  = (w12*w07);
  /* #151: @2 = (@2+@7) */
  w02 += w07;
  /* #152: (@24[1] += @2) */
  for (rr=w24+1, cs=(&w02); rr!=w24+2; rr+=1) *rr += *cs++;
  /* #153: @2 = @26[1] */
  for (rr=(&w02), cs=w26+1; cs!=w26+2; cs+=1) *rr++ = *cs;
  /* #154: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #155: @0 = (@0*@2) */
  w00 *= w02;
  /* #156: (@24[2] += @0) */
  for (rr=w24+2, cs=(&w00); rr!=w24+3; rr+=1) *rr += *cs++;
  /* #157: @27 = vertcat(@17, @24) */
  rr=w27;
  for (i=0, cs=w17; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<11; ++i) *rr++ = *cs++;
  /* #158: @24 = @27[0, 1, 2, 3, 4, 5, 6, 11, 12, 13, 14] */
  for (cii=casadi_s0, rr=w24, cs=w27; cii!=casadi_s0+11; ++cii) *rr++ = cs[*cii];
  /* #159: (@25[0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12] = @24) */
  for (cii=casadi_s1, rr=w25, cs=w24; cii!=casadi_s1+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #160: (@25[0, 1, 2, 3, 4, 6, 8, 9, 13, 17, 21] = @24) */
  for (cii=casadi_s2, rr=w25, cs=w24; cii!=casadi_s2+11; ++cii, ++cs) rr[*cii] = *cs;
  /* #161: @28 = ones(15x1,2nz) */
  casadi_fill(w28, 2, 1.);
  /* #162: {NULL, @29} = vertsplit(@28) */
  casadi_copy(w28, 2, w29);
  /* #163: @0 = @29[1] */
  for (rr=(&w00), cs=w29+1; cs!=w29+2; cs+=1) *rr++ = *cs;
  /* #164: @0 = (2.*@0) */
  w00 = (2.* w00 );
  /* #165: @2 = (@11*@0) */
  w02  = (w11*w00);
  /* #166: @24 = @1; (@24[10] += @2) */
  casadi_copy(w01, 11, w24);
  for (rr=w24+10, cs=(&w02); rr!=w24+11; rr+=1) *rr += *cs++;
  /* #167: (@24[9] += @2) */
  for (rr=w24+9, cs=(&w02); rr!=w24+10; rr+=1) *rr += *cs++;
  /* #168: @0 = (@5*@0) */
  w00  = (w05*w00);
  /* #169: @0 = (@2+@0) */
  w00  = (w02+w00);
  /* #170: (@24[8] += @0) */
  for (rr=w24+8, cs=(&w00); rr!=w24+9; rr+=1) *rr += *cs++;
  /* #171: (@24[7] += @2) */
  for (rr=w24+7, cs=(&w02); rr!=w24+8; rr+=1) *rr += *cs++;
  /* #172: @2 = @29[0] */
  for (rr=(&w02), cs=w29+0; cs!=w29+1; cs+=1) *rr++ = *cs;
  /* #173: @15 = (@2/@15) */
  w15  = (w02/w15);
  /* #174: @6 = (2.*@6) */
  w06 = (2.* w06 );
  /* #175: @6 = (@6*@2) */
  w06 *= w02;
  /* #176: @14 = (@14*@6) */
  w14 *= w06;
  /* #177: @15 = (@15-@14) */
  w15 -= w14;
  /* #178: @15 = (@9*@15) */
  w15  = (w09*w15);
  /* #179: @2 = (@12*@2) */
  w02  = (w12*w02);
  /* #180: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #181: @2 = (@5*@2) */
  w02  = (w05*w02);
  /* #182: @10 = (@10*@2) */
  w10 *= w02;
  /* #183: @15 = (@15+@10) */
  w15 += w10;
  /* #184: @15 = (-@15) */
  w15 = (- w15 );
  /* #185: (@24[0] += @15) */
  for (rr=w24+0, cs=(&w15); rr!=w24+1; rr+=1) *rr += *cs++;
  /* #186: @12 = (@12*@2) */
  w12 *= w02;
  /* #187: @13 = (@13*@6) */
  w13 *= w06;
  /* #188: @9 = (@9*@13) */
  w09 *= w13;
  /* #189: @12 = (@12-@9) */
  w12 -= w09;
  /* #190: (@24[1] += @12) */
  for (rr=w24+1, cs=(&w12); rr!=w24+2; rr+=1) *rr += *cs++;
  /* #191: @30 = @24[0, 1, 7, 8, 9, 10] */
  for (cii=casadi_s3, rr=w30, cs=w24; cii!=casadi_s3+6; ++cii) *rr++ = cs[*cii];
  /* #192: (@25[6, 7, 13, 14, 15, 16] = @30) */
  for (cii=casadi_s4, rr=w25, cs=w30; cii!=casadi_s4+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #193: (@25[5, 7, 10, 14, 18, 22] = @30) */
  for (cii=casadi_s5, rr=w25, cs=w30; cii!=casadi_s5+6; ++cii, ++cs) rr[*cii] = *cs;
  /* #194: @12 = ones(15x1,1nz) */
  w12 = 1.;
  /* #195: {NULL, @9} = vertsplit(@12) */
  w09 = w12;
  /* #196: @12 = @9[0] */
  for (rr=(&w12), cs=(&w09)+0; cs!=(&w09)+1; cs+=1) *rr++ = *cs;
  /* #197: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #198: @9 = (@11*@12) */
  w09  = (w11*w12);
  /* #199: @24 = @1; (@24[10] += @9) */
  casadi_copy(w01, 11, w24);
  for (rr=w24+10, cs=(&w09); rr!=w24+11; rr+=1) *rr += *cs++;
  /* #200: @12 = (@5*@12) */
  w12  = (w05*w12);
  /* #201: @12 = (@9+@12) */
  w12  = (w09+w12);
  /* #202: (@24[9] += @12) */
  for (rr=w24+9, cs=(&w12); rr!=w24+10; rr+=1) *rr += *cs++;
  /* #203: (@24[8] += @9) */
  for (rr=w24+8, cs=(&w09); rr!=w24+9; rr+=1) *rr += *cs++;
  /* #204: (@24[7] += @9) */
  for (rr=w24+7, cs=(&w09); rr!=w24+8; rr+=1) *rr += *cs++;
  /* #205: @17 = @24[7:11] */
  for (rr=w17, cs=w24+7; cs!=w24+11; cs+=1) *rr++ = *cs;
  /* #206: (@25[17:21] = @17) */
  for (rr=w25+17, cs=w17; rr!=w25+21; rr+=1) *rr = *cs++;
  /* #207: (@25[11:27:4] = @17) */
  for (rr=w25+11, cs=w17; rr!=w25+27; rr+=4) *rr = *cs++;
  /* #208: @9 = ones(15x1,1nz) */
  w09 = 1.;
  /* #209: {NULL, @12} = vertsplit(@9) */
  w12 = w09;
  /* #210: @9 = @12[0] */
  for (rr=(&w09), cs=(&w12)+0; cs!=(&w12)+1; cs+=1) *rr++ = *cs;
  /* #211: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #212: @11 = (@11*@9) */
  w11 *= w09;
  /* #213: @5 = (@5*@9) */
  w05 *= w09;
  /* #214: @5 = (@11+@5) */
  w05  = (w11+w05);
  /* #215: (@1[10] += @5) */
  for (rr=w01+10, cs=(&w05); rr!=w01+11; rr+=1) *rr += *cs++;
  /* #216: (@1[9] += @11) */
  for (rr=w01+9, cs=(&w11); rr!=w01+10; rr+=1) *rr += *cs++;
  /* #217: (@1[8] += @11) */
  for (rr=w01+8, cs=(&w11); rr!=w01+9; rr+=1) *rr += *cs++;
  /* #218: (@1[7] += @11) */
  for (rr=w01+7, cs=(&w11); rr!=w01+8; rr+=1) *rr += *cs++;
  /* #219: @17 = @1[7:11] */
  for (rr=w17, cs=w01+7; cs!=w01+11; cs+=1) *rr++ = *cs;
  /* #220: (@25[21:25] = @17) */
  for (rr=w25+21, cs=w17; rr!=w25+25; rr+=1) *rr = *cs++;
  /* #221: (@25[12:28:4] = @17) */
  for (rr=w25+12, cs=w17; rr!=w25+28; rr+=4) *rr = *cs++;
  /* #222: @31 = @25' */
  casadi_trans(w25,casadi_s6, w31, casadi_s6, iw);
  /* #223: output[2][0] = @31 */
  casadi_copy(w31, 25, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    case 3: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    case 1: return casadi_s12;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 16;
  if (sz_w) *sz_w = 140;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 16*sizeof(casadi_int);
  if (sz_w) *sz_w = 140*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
