/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {15, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_0_fun_jac:(i0[11],i1[4],i2[],i3[8])->(o0,o1[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, *w01=w+1, w02, w04, w05, w06, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, *w17=w+34, w18, w19, w20, w21, w22;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 1000 */
  w00 = 1000.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @4 = sq(@2) */
  w04 = casadi_sq( w02 );
  /* #7: @4 = (@0*@4) */
  w04  = (w00*w04);
  /* #8: @5 = @1[1] */
  w05 = wr01[1];
  /* #9: @6 = @1[0] */
  w06 = wr01[0];
  /* #10: @7 = 0.5 */
  w07 = 5.0000000000000000e-01;
  /* #11: @8 = fmax(@6,@7) */
  w08  = casadi_fmax(w06,w07);
  /* #12: @5 = (@5/@8) */
  w05 /= w08;
  /* #13: @9 = sq(@5) */
  w09 = casadi_sq( w05 );
  /* #14: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #15: @4 = (@4+@9) */
  w04 += w09;
  /* #16: @9 = 20 */
  w09 = 20.;
  /* #17: @10 = @1[7] */
  w10 = wr01[7];
  /* #18: @11 = @1[8] */
  w11 = wr01[8];
  /* #19: @12 = (@10+@11) */
  w12  = (w10+w11);
  /* #20: @13 = @1[9] */
  w13 = wr01[9];
  /* #21: @12 = (@12+@13) */
  w12 += w13;
  /* #22: @14 = @1[10] */
  w14 = wr01[10];
  /* #23: @12 = (@12+@14) */
  w12 += w14;
  /* #24: @15 = @3[7] */
  w15 = wr03[7];
  /* #25: @12 = (@12-@15) */
  w12 -= w15;
  /* #26: @15 = sq(@12) */
  w15 = casadi_sq( w12 );
  /* #27: @15 = (@9*@15) */
  w15  = (w09*w15);
  /* #28: @4 = (@4+@15) */
  w04 += w15;
  /* #29: @15 = sq(@10) */
  w15 = casadi_sq( w10 );
  /* #30: @16 = sq(@11) */
  w16 = casadi_sq( w11 );
  /* #31: @15 = (@15+@16) */
  w15 += w16;
  /* #32: @16 = sq(@13) */
  w16 = casadi_sq( w13 );
  /* #33: @15 = (@15+@16) */
  w15 += w16;
  /* #34: @16 = sq(@14) */
  w16 = casadi_sq( w14 );
  /* #35: @15 = (@15+@16) */
  w15 += w16;
  /* #36: @15 = (@7*@15) */
  w15  = (w07*w15);
  /* #37: @4 = (@4+@15) */
  w04 += w15;
  /* #38: @15 = 0.09 */
  w15 = 8.9999999999999997e-02;
  /* #39: @17 = input[1][0] */
  casadi_copy(arg[1], 4, w17);
  /* #40: @16 = @17[0] */
  for (rr=(&w16), cs=w17+0; cs!=w17+1; cs+=1) *rr++ = *cs;
  /* #41: @18 = sq(@16) */
  w18 = casadi_sq( w16 );
  /* #42: @19 = @17[1] */
  for (rr=(&w19), cs=w17+1; cs!=w17+2; cs+=1) *rr++ = *cs;
  /* #43: @20 = sq(@19) */
  w20 = casadi_sq( w19 );
  /* #44: @18 = (@18+@20) */
  w18 += w20;
  /* #45: @20 = @17[2] */
  for (rr=(&w20), cs=w17+2; cs!=w17+3; cs+=1) *rr++ = *cs;
  /* #46: @21 = sq(@20) */
  w21 = casadi_sq( w20 );
  /* #47: @18 = (@18+@21) */
  w18 += w21;
  /* #48: @21 = @17[3] */
  for (rr=(&w21), cs=w17+3; cs!=w17+4; cs+=1) *rr++ = *cs;
  /* #49: @22 = sq(@21) */
  w22 = casadi_sq( w21 );
  /* #50: @18 = (@18+@22) */
  w18 += w22;
  /* #51: @18 = (@15*@18) */
  w18  = (w15*w18);
  /* #52: @4 = (@4+@18) */
  w04 += w18;
  /* #53: output[0][0] = @4 */
  if (res[0]) res[0][0] = w04;
  /* #54: @17 = zeros(4x1) */
  casadi_clear(w17, 4);
  /* #55: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #56: @21 = (@15*@21) */
  w21  = (w15*w21);
  /* #57: (@17[3] += @21) */
  for (rr=w17+3, cs=(&w21); rr!=w17+4; rr+=1) *rr += *cs++;
  /* #58: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #59: @20 = (@15*@20) */
  w20  = (w15*w20);
  /* #60: (@17[2] += @20) */
  for (rr=w17+2, cs=(&w20); rr!=w17+3; rr+=1) *rr += *cs++;
  /* #61: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #62: @19 = (@15*@19) */
  w19  = (w15*w19);
  /* #63: (@17[1] += @19) */
  for (rr=w17+1, cs=(&w19); rr!=w17+2; rr+=1) *rr += *cs++;
  /* #64: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #65: @15 = (@15*@16) */
  w15 *= w16;
  /* #66: (@17[0] += @15) */
  for (rr=w17+0, cs=(&w15); rr!=w17+1; rr+=1) *rr += *cs++;
  /* #67: output[1][0] = @17 */
  casadi_copy(w17, 4, res[1]);
  /* #68: @1 = zeros(11x1) */
  casadi_clear(w01, 11);
  /* #69: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #70: @14 = (@7*@14) */
  w14  = (w07*w14);
  /* #71: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #72: @9 = (@9*@12) */
  w09 *= w12;
  /* #73: @14 = (@14+@9) */
  w14 += w09;
  /* #74: (@1[10] += @14) */
  for (rr=w01+10, cs=(&w14); rr!=w01+11; rr+=1) *rr += *cs++;
  /* #75: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #76: @13 = (@7*@13) */
  w13  = (w07*w13);
  /* #77: @13 = (@13+@9) */
  w13 += w09;
  /* #78: (@1[9] += @13) */
  for (rr=w01+9, cs=(&w13); rr!=w01+10; rr+=1) *rr += *cs++;
  /* #79: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #80: @11 = (@7*@11) */
  w11  = (w07*w11);
  /* #81: @11 = (@11+@9) */
  w11 += w09;
  /* #82: (@1[8] += @11) */
  for (rr=w01+8, cs=(&w11); rr!=w01+9; rr+=1) *rr += *cs++;
  /* #83: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #84: @10 = (@7*@10) */
  w10  = (w07*w10);
  /* #85: @10 = (@10+@9) */
  w10 += w09;
  /* #86: (@1[7] += @10) */
  for (rr=w01+7, cs=(&w10); rr!=w01+8; rr+=1) *rr += *cs++;
  /* #87: @10 = (@7<=@6) */
  w10  = (w07<=w06);
  /* #88: @6 = (@6<=@7) */
  w06  = (w06<=w07);
  /* #89: @6 = (@10+@6) */
  w06  = (w10+w06);
  /* #90: @10 = (@10/@6) */
  w10 /= w06;
  /* #91: @6 = (@5/@8) */
  w06  = (w05/w08);
  /* #92: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #93: @5 = (2.*@5) */
  w05 = (2.* w05 );
  /* #94: @6 = (@6*@5) */
  w06 *= w05;
  /* #95: @10 = (@10*@6) */
  w10 *= w06;
  /* #96: @10 = (-@10) */
  w10 = (- w10 );
  /* #97: (@1[0] += @10) */
  for (rr=w01+0, cs=(&w10); rr!=w01+1; rr+=1) *rr += *cs++;
  /* #98: @5 = (@5/@8) */
  w05 /= w08;
  /* #99: (@1[1] += @5) */
  for (rr=w01+1, cs=(&w05); rr!=w01+2; rr+=1) *rr += *cs++;
  /* #100: @2 = (2.*@2) */
  w02 = (2.* w02 );
  /* #101: @0 = (@0*@2) */
  w00 *= w02;
  /* #102: (@1[2] += @0) */
  for (rr=w01+2, cs=(&w00); rr!=w01+3; rr+=1) *rr += *cs++;
  /* #103: output[1][1] = @1 */
  if (res[1]) casadi_copy(w01, 11, res[1]+4);
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_0_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 43;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 43*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
