/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tv_nmpc_cost_ext_cost_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {11, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

static const casadi_real casadi_zeros[11] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0.};

/* tv_nmpc_cost_ext_cost_0_fun:(i0[11],i1[4],i2[],i3[8])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w02, w04, w05, w06, w07, w08, w09, *w10=w+27;
  const casadi_real *cs, *wr01, *wr03;
  /* #0: @0 = 18 */
  w00 = 18.;
  /* #1: @1 = input[0][0] */
  wr01 = arg[0] ? arg[0] : casadi_zeros;
  /* #2: @2 = @1[2] */
  w02 = wr01[2];
  /* #3: @3 = input[3][0] */
  wr03 = arg[3] ? arg[3] : casadi_zeros;
  /* #4: @4 = @3[0] */
  w04 = wr03[0];
  /* #5: @2 = (@2-@4) */
  w02 -= w04;
  /* #6: @2 = sq(@2) */
  w02 = casadi_sq( w02 );
  /* #7: @0 = (@0*@2) */
  w00 *= w02;
  /* #8: @2 = 50000 */
  w02 = 50000.;
  /* #9: @4 = @1[1] */
  w04 = wr01[1];
  /* #10: @5 = 0.001 */
  w05 = 1.0000000000000000e-03;
  /* #11: @6 = @1[0] */
  w06 = wr01[0];
  /* #12: @5 = (@5+@6) */
  w05 += w06;
  /* #13: @4 = atan2(@4,@5) */
  w04  = atan2(w04,w05);
  /* #14: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #15: @2 = (@2*@4) */
  w02 *= w04;
  /* #16: @0 = (@0+@2) */
  w00 += w02;
  /* #17: @2 = 0.1 */
  w02 = 1.0000000000000001e-01;
  /* #18: @4 = @1[7] */
  w04 = wr01[7];
  /* #19: @5 = sq(@4) */
  w05 = casadi_sq( w04 );
  /* #20: @6 = @1[8] */
  w06 = wr01[8];
  /* #21: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #22: @5 = (@5+@7) */
  w05 += w07;
  /* #23: @7 = @1[9] */
  w07 = wr01[9];
  /* #24: @8 = sq(@7) */
  w08 = casadi_sq( w07 );
  /* #25: @5 = (@5+@8) */
  w05 += w08;
  /* #26: @8 = @1[10] */
  w08 = wr01[10];
  /* #27: @9 = sq(@8) */
  w09 = casadi_sq( w08 );
  /* #28: @5 = (@5+@9) */
  w05 += w09;
  /* #29: @2 = (@2*@5) */
  w02 *= w05;
  /* #30: @0 = (@0+@2) */
  w00 += w02;
  /* #31: @2 = 30 */
  w02 = 30.;
  /* #32: @4 = (@4+@6) */
  w04 += w06;
  /* #33: @4 = (@4+@7) */
  w04 += w07;
  /* #34: @4 = (@4+@8) */
  w04 += w08;
  /* #35: @8 = @3[7] */
  w08 = wr03[7];
  /* #36: @4 = (@4-@8) */
  w04 -= w08;
  /* #37: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #38: @2 = (@2*@4) */
  w02 *= w04;
  /* #39: @0 = (@0+@2) */
  w00 += w02;
  /* #40: @2 = 0.09 */
  w02 = 8.9999999999999997e-02;
  /* #41: @10 = input[1][0] */
  casadi_copy(arg[1], 4, w10);
  /* #42: @4 = @10[0] */
  for (rr=(&w04), cs=w10+0; cs!=w10+1; cs+=1) *rr++ = *cs;
  /* #43: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #44: @8 = @10[1] */
  for (rr=(&w08), cs=w10+1; cs!=w10+2; cs+=1) *rr++ = *cs;
  /* #45: @8 = sq(@8) */
  w08 = casadi_sq( w08 );
  /* #46: @4 = (@4+@8) */
  w04 += w08;
  /* #47: @8 = @10[2] */
  for (rr=(&w08), cs=w10+2; cs!=w10+3; cs+=1) *rr++ = *cs;
  /* #48: @8 = sq(@8) */
  w08 = casadi_sq( w08 );
  /* #49: @4 = (@4+@8) */
  w04 += w08;
  /* #50: @8 = @10[3] */
  for (rr=(&w08), cs=w10+3; cs!=w10+4; cs+=1) *rr++ = *cs;
  /* #51: @8 = sq(@8) */
  w08 = casadi_sq( w08 );
  /* #52: @4 = (@4+@8) */
  w04 += w08;
  /* #53: @2 = (@2*@4) */
  w02 *= w04;
  /* #54: @0 = (@0+@2) */
  w00 += w02;
  /* #55: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tv_nmpc_cost_ext_cost_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tv_nmpc_cost_ext_cost_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tv_nmpc_cost_ext_cost_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tv_nmpc_cost_ext_cost_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tv_nmpc_cost_ext_cost_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 31;
  return 0;
}

CASADI_SYMBOL_EXPORT int tv_nmpc_cost_ext_cost_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 31*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
